### ISSUE TITLE
Test sur 1 gabarit loisirs + 1 page Hub

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#1]
Bonjour,

Je n'ai pas trouvé le format 1 photo dont j'ai besoin dans les articles en dehors des projets loisirs.

Comment remplacer l'URL de la vidéo ? J'ai touché à l'éditeur mais cela ajoute une vidéo, je veux simplement changer le lien You Tube fourni dans le module.

Dans la fiche d'identité loisirs, il manque avant le site Internet : Espaces et installations

Dès que je change une photo, la photo est déformée. Je ne comprends pas comment utiliser l'éditeur pour éviter la déformation. Il n'y a pas de zone de sélection apparente.

Je ne sais pas où trouver le footer dans les components

Concernant le header, je n'ai pas trouvé comment ajouter la photo qui est collée au menu normalement 
et Le sport des territoires doit apparaître en premier avant le Sport pour tous

Il faut retirer UCPA dans le menu (Le groupe)

Il y a un problème de mise en forme dans le module aller + loin, "avec l'UCPA" doit apparaître à la ligne.

Les noms des modules vont être changer pour faciliter l'usage.

Merci

Laëtitia.

**Comment by nicolastrenti** [comment]
Les différents points soulevés ont été scindés dans différents tickets pour améliorer le suivi.
