### ISSUE TITLE
Version desktop / snippet photo gauche + texte + 3 CTA

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#100]
Le filet de fin n'est pas à la bonne place 

![fireshot capture 23 - mentions legales_ - https___ucpa-corpo recette ampize](https://user-images.githubusercontent.com/40030677/42516040-7515f270-845d-11e8-93e1-dedbaca5b8d0.png)

**Comment by LucDelmon** [comment]
Bonjour, c'est corrigé
