### ISSUE TITLE
Version desktop / snippet articles liés x 3 sans fond et avec fond 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#101]
La colonne après le chevron rouge est plus large dans les 2 snippets articles liés x 3 sans fond et avec fond que dans l'article lié seul ou articles liés X 3 loisirs (l'espace entre le chevron et le texte est mieux proportionné dans ces deux derniers snippets).

![fireshot capture 24 - mentions legales_ - https___ucpa-corpo recette ampize](https://user-images.githubusercontent.com/40030677/42516984-056d1b18-845f-11e8-9459-0b62294a3648.png)

Peut-on uniformiser ?

merci

**Comment by LucDelmon** [comment]
Bonjour, c'est corrigé

**Comment by LaetitiaVerdier** [comment]
Merci
