### ISSUE TITLE
Version desktop / photo gauche + texte

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#102]
Les espaces paragraphe demeurent trop grands avant les deux intertitres

![image](https://user-images.githubusercontent.com/40030677/42517354-cd4f9ade-845f-11e8-8c87-933bbe9fbf13.png)

**Comment by LucDelmon** [comment]
Bonjour, vous parlez de l'espace entre les 2 paragraphes uniquement ?

**Comment by LucDelmon** [comment]
Si c'est le cas, c'est corrigé

**Comment by LaetitiaVerdier** [comment]
Avant le texte réussir le pari 
et avant le texte y arriver

Merci

**Comment by LucDelmon** [comment]
c'est fait
