### ISSUE TITLE
Version desktop / snippet partenaires dispositifs solidaires

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#103]
Nous avons besoin de rapprocher le nom du partenaire de son logo et de mettre un espace entre chaque partenaire

![image](https://user-images.githubusercontent.com/40030677/42517538-378282ae-8460-11e8-8572-47400491ef29.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est résolu
