### ISSUE TITLE
Version mobile / snippet articles liés x 3

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#104]
Nous avons besoin :
- d'un espace entre la photo et le titre de l'article en noir (ex: Séjours dans l'exemple ci-dessous)
- et un espace entre la photo et le filet rouge quand l'article est sélectionné (ex : Politique ESS ci-dessous)

![sans titre](https://user-images.githubusercontent.com/40030677/42518374-fe7e7164-8461-11e8-9632-c9e328bf752d.png)

**Comment by LucDelmon** [comment]
c'est fait, j'ai aussi rajouté un espace après le paragraphe car on ne distinguais plus clairement la correspondance entre photo et paragraphes

**Comment by LaetitiaVerdier** [comment]
Merci beaucoup
