### ISSUE TITLE
Version mobile / snippet article lié

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#105]
La taille de la photo ne convient pas, elle est trop petite

![image](https://user-images.githubusercontent.com/40030677/42518676-b61d8648-8462-11e8-9316-9b657e8fd868.png)

**Comment by LucDelmon** [comment]
Bonjour, vous avez surement chargé le snippet alors que j'étais en train d'essayer de corriger la #99

**Comment by LucDelmon** [comment]
Vous souhaiteriez qu'elle prenne toute la largeur mais quel garde la même taille en desktop ?

**Comment by LaetitiaVerdier** [comment]
Voici le résultat que nous souhaitons sur mobile. 

Effectivement, nous ne voulons pas modifier le desktop.

![image](https://user-images.githubusercontent.com/40030677/42562484-2003ce3e-84fc-11e8-8f90-ea46adb9fce1.png)

**Comment by LucDelmon** [comment]
La hauteur de l'image est lié au format de l'image que vous choissisez.

L'image prend automatiquement tout la largeur possible. La hauteur se déduit automatiquement.

La différence entre ce que vous demandez est ce qui est présent est juste le choix de l'image.

**Comment by LaetitiaVerdier** [comment]
C'est bien noté alors cependant dans ma capture initiale la photo ne prend par toute la largeur

**Comment by LucDelmon** [comment]
Non, mais ce n'est pas le cas dans la 2 éme capture non plus

**Comment by LaetitiaVerdier** [comment]
Effectivement mais il semble bien plus large en aperçu du moins

**Comment by LucDelmon** [comment]
Oui j'ai diminué les marges par deux

**Comment by LaetitiaVerdier** [comment]
d'accord,

je vais faire un essai avec un autre format de photo

Merci

**Comment by LaetitiaVerdier** [comment]
Bonjour Luc,

Je vous confirme que le format de la photo souhaité correspond au visuel de la petite fille qui court (cf. ci-dessous), pouvez-vous remplacer le visuel du snippet. Ainsi nous serons bien à un format 1200 x 591 px

![image](https://user-images.githubusercontent.com/40030677/42580185-4899bb3c-852a-11e8-93c2-d3304733d85d.png)


![image](https://user-images.githubusercontent.com/40030677/42580254-674695aa-852a-11e8-878a-34e5342189fd.png)

Merci

**Comment by LucDelmon** [comment]
c'est fait

**Comment by LaetitiaVerdier** [comment]
Merci
