### ISSUE TITLE
Version mobile / snippet articles liés loisirs x 3

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#106]
L'espace entre le filets et l'article sélectionné en rouge doit être réduit et inférieur aux espaces prévus entre les 3 articles

![sans titre2](https://user-images.githubusercontent.com/40030677/42518838-0d5b6f42-8463-11e8-8b81-ea2372b5ff01.png)

**Comment by LucDelmon** [comment]
c'est fait

**Comment by LaetitiaVerdier** [comment]
Le résultat de ce snippet en version mobile n'est pas celui souhaité.

L'espace entre le filet et Valdeblore (et les 2 autres titres) est trop important et doit être réduit  et l'espace entre le filet suivant et le mot "génération" doit être augmenté ce qui permet à la lecture de bien séparer nos 3 articles liés.

De même, l'espace blanc en version mobile au-dessus du titre "Articles liés" est trop grand et ne correspond pas

**Comment by LaetitiaVerdier** [comment]
Le résultat de ce snippet en version mobile n'est pas celui souhaité.

L'espace entre le filet et Valdeblore (et les 2 autres titres) est trop important et doit être réduit et l'espace entre le filet suivant et le mot "génération" doit être augmenté ce qui permet à la lecture de bien séparer nos 3 articles liés.

De même, l'espace blanc en version mobile au-dessus du titre "Articles liés" est trop grand et ne correspond pas


![screenshot_2018-07-12-10-34-03_resized](https://user-images.githubusercontent.com/40030677/42622375-8e98fd00-85c0-11e8-95f0-e964f750e55e.png)

![screenshot_2018-07-12-10-22-48_resized](https://user-images.githubusercontent.com/40030677/42622385-9210b586-85c0-11e8-9d47-4a6abf4f2e99.png)

**Comment by LucDelmon** [comment]
c'est corrigé,

l'espace au dessus est de 66 pixel comme demandé. ( C'est pareil dans tout les autres snippets en mobile)

**Comment by LaetitiaVerdier** [comment]
Merci

**Comment by LaetitiaVerdier** [comment]
<img width="787" alt="capture d ecran 2018-07-12 a 12 19 50" src="https://user-images.githubusercontent.com/40030677/42627751-38c77f9c-85ce-11e8-993b-d7310d09a7d8.png">

**Comment by LucDelmon** [comment]
c'esta fait, il faut juste recharger le snippet

**Comment by LaetitiaVerdier** [comment]
C''est super.

merci
