### ISSUE TITLE
Version mobile / snippet fiche d'identité loisirs

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#108]
La dernière phrase ne doit pas être collée au bloc fiche d'identité.

![image](https://user-images.githubusercontent.com/40030677/42519275-f01ca378-8463-11e8-9e70-37b9ed8b6919.png)

**Comment by LucDelmon** [comment]
C'est corrigé

**Comment by LaetitiaVerdier** [comment]
Je viens de regarder sur le mobile l'article Aren'Ice et le bloc est toujours collé à la dernière phrase.

**Comment by LucDelmon** [comment]
Bonjour, de quel phrase parlez-vous ? celle juste avant le bloc ?

**Comment by LaetitiaVerdier** [comment]
OUi tout à fait : 70000 spectateurs

**Comment by LucDelmon** [comment]
c'est fait
