### ISSUE TITLE
Version mobile / snippet chiffres clés + texte

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#110]
Le snippet chiffres clés + texte doit être calé sur le même modèle que 3 chiffres clés qui parfait.

Il manque :
- un espace en haut du bloc
- l'espace en bas du bloc est trop grand 
- la taille du cercle + picto est trop grand
- plus d'espace avant le sous-titre "A savoir"

![image](https://user-images.githubusercontent.com/40030677/42519475-6e841a20-8464-11e8-87d4-df9d97ff6c11.png)

**Comment by LucDelmon** [comment]
c'est fait
