### ISSUE TITLE
Version mobile / Snippet Aller plus loin

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#111]
Merci de mettre les deux CTA 
- à la même taille que les autres CTA en version mobile
- les deux l'un en dessous de l'autre centrés
- Allez doit être remplacé par Aller dans le titre

![image](https://user-images.githubusercontent.com/40030677/42519827-2b02c886-8465-11e8-916b-c399bde6e57a.png)

**Comment by LucDelmon** [comment]
C'est fait.

A noter que c'est vous qui m'aviez demandé de mettre les CTAs sur une ligne dans la #84

**Comment by LaetitiaVerdier** [comment]
Ce n'est pas ce que j'avais demandé, je faisais référence au texte "Toutes nos implantations" et non pas au CTA mais je conçois la méprise à la relecture de mon écrit : "les call-to-action ne doivent pas passer sur 2 lignes, peut-être doit-on revoir la taille du corps de texte"

Ça n'était pas très clair effectivement
