### ISSUE TITLE
Snippet Aller plus loin avec l’UCPA + CTA Nous contacter

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#113]
Bonjour,

Pour le CTA Nous contacter du snippet Aller plus loin, nous allons renvoyer sur le formulaire de contacts global.

Est-il possible de mettre le lien par défaut automatiquement pour que les contributeurs n'aient pas à faire de manipulations ?

Merci

**Comment by LucDelmon** [comment]
C'est fait

**Comment by LaetitiaVerdier** [comment]
Merci Luc

Peut-on faire pareil pour renvoyer sur la page liste des projets de référence loisirs dans le CTA "Tous les projets de référence" du snippet articles liés loisirs x3 ?

Merci encore

**Comment by LucDelmon** [comment]
c'est fait

**Comment by LaetitiaVerdier** [comment]
merci Luc
