### ISSUE TITLE
Animation de tous les snippets articles liés

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#115]
Est-il possible d'accélérer l'animation des snippets articles liés pour que cela soit comme l'animation du menu ?

Merci

**Comment by LucDelmon** [comment]
L'animation du menu est  faites d'une manière totalement différente mais il est possible d'accélérer  la vitesse d'animation.

Actuellement les images apparaissent en 1.5 sec et les traits se déplacent en 0.8 sec. 

Quelles vitesses voulez-vous ?

**Comment by LaetitiaVerdier** [comment]
Pour les images, 0,8 sec et pour les traits 0,4 sec.

**Comment by LucDelmon** [comment]
c'est fait
