### ISSUE TITLE
Critères de tri des pages listes / paramétrage 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#116]
Voici les critères de tri souhaités pour les pages liste :

Actualités : critère par date - les plus récents en premier
Offres de formation : critère par ordre alphabétique de la formation
Dispositifs solidaires : critère par ordre alphabétique du nom du dispositif
Projets de référence : critère par régions - respecter l'ordre alphabétique 

Merci

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait

**Comment by LaetitiaVerdier** [comment]
Merci
