### ISSUE TITLE
Version desktop / Snippet fiche d'identité loisirs

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#117]
Bonjour,

J'ai rechargé les snippets hier soir et créer un nouvel article :
https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires/projets-de-reference/projet-de-reference/aren-ice

Dans le snippet fiche d'identité, il y a une différence d'espaces entre les paragraphes, le dernier étant trop grand. 

De plus, les espaces avant le bloc et à la fin de l'article ne sont pas du tout identiques l'un par rapport à l'autre et aux autres snippets :

![image](https://user-images.githubusercontent.com/40030677/42620203-993e452c-85ba-11e8-83cb-8eb249f87881.png)

Merci

**Comment by LaetitiaVerdier** [comment]
Le problème d'espaces avant le bloc et à la fin de l'article qui ne sont pas du tout identiques l'un par rapport à l'autre est également visible sur la version mobile

**Comment by LucDelmon** [comment]
Bonjour, il n'y a pas de différence d'espace pour le dernier paragraphes.  C'est juste que le dernier espace est un espace entre 2 paragraphes et celui d'avant un espace entre un Titre ( en gras) et un paragraphe.

**Comment by LaetitiaVerdier** [comment]
On a des espaces trop grands sur la version mobile de tous les snippets Texte + photo gauche ou droite ou avec CTA.

**Comment by LaetitiaVerdier** [comment]
Dans ce snippet, il s'agit uniquement d'une mise en avant en capitale et non d'un titre, l'écart doit donc être le même que pour du texte courant

![image](https://user-images.githubusercontent.com/40030677/42621476-32b23e9a-85be-11e8-8db4-66d4115a2bfe.png)

**Comment by LucDelmon** [comment]
c'est bon pour l'espacement autour de ce texte

**Comment by LucDelmon** [comment]
J'ai fais une correction qui supprime des espaces en trop qui arrivent après les snippets.

C'est directement visible. Le problème est-il corrigé ?

**Comment by LaetitiaVerdier** [comment]
Pour le snippet fiche d'identité les espaces entre les différents paragraphes sont maintenant égaux, par contre trop grands. Pourquoi ?

**Comment by LucDelmon** [comment]
Ce sont les mêmes qu'avant

**Comment by LucDelmon** [comment]
A part la partie en Gras qui est devenu un paragraphe et qui récupére les mêmes espace que les autres

**Comment by LaetitiaVerdier** [comment]
Merci on reste comme ça
