### ISSUE TITLE
Version mobile / problème espaces

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#118]
On a des espaces trop grands avant le titre type "activités aquatiques" ou "la glisse pour tous" (dans le nouvel article Aren'Ice) et à la fin après la dernière ligne du texte sur la version mobile de tous les snippets Texte + photo gauche ou droite ou avec CTA.

**Comment by LaetitiaVerdier** [comment]
Quelques screenshots illustratifs 

![screenshot_2018-07-12-10-18-58_resized](https://user-images.githubusercontent.com/40030677/42622225-3102ab14-85c0-11e8-8cd7-da9aea250d24.png)

![screenshot_2018-07-12-10-20-24_resized](https://user-images.githubusercontent.com/40030677/42622231-333ab28c-85c0-11e8-93f4-51138858b547.png)

![screenshot_2018-07-12-10-20-35_resized](https://user-images.githubusercontent.com/40030677/42622246-4039ad6c-85c0-11e8-9cca-556959f920a2.png)

**Comment by LucDelmon** [comment]
Je viens de faire un correctif qui supprime des  paragraphes entre les snippets.

Le problème est-il tj présent ?

**Comment by LaetitiaVerdier** [comment]
Non c'est beaucoup mieux.

L'espace entre le filet et le titre de la vidéo du snippet vidéo est trop petit sur le mobile.

**Comment by LucDelmon** [comment]
J'ai aggrandi l'espace.
