### ISSUE TITLE
Chevauchement snippet vidéo et snippet suivant

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#119]
Bonjour,

J'ai essayé de changer le snippet vidéo dans l'article Aren'ice, cela produit un chevauchement d'images.

![image](https://user-images.githubusercontent.com/40030677/42633332-7c9593f0-85e0-11e8-8377-2de89a5771c6.png)

**Comment by LucDelmon** [comment]
c'est corrigé

**Comment by LaetitiaVerdier** [comment]
Cela se chevauche toujours dans mon article Aren'ice où j'essaie de l'intégrer avant le bloc photo gauche + texte.

**Comment by LucDelmon** [comment]
Il faut recharger la page ( faire un refresh navigateur) pour recharger la css

**Comment by LaetitiaVerdier** [comment]
Je l'ai déjà fait mais je recommence.

**Comment by LucDelmon** [comment]
Je parle vraiment de recharger tout le logiciel avec un F5.

**Comment by LaetitiaVerdier** [comment]
Tout est bon.

Merci
