### ISSUE TITLE
Animations / modules

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#120]
Bonjour Nicolas, Luc,

Françoise me dit qu'il était question de prévoir les animations suivantes dans les modules photo + texte :
![ucpa_modules_articles_animation 1](https://user-images.githubusercontent.com/40030677/42637381-4f6341d8-85eb-11e8-899f-00ec92c15513.jpg)

Cela vous dit-il quelques chose ?

Merci.

Laëtitia.

**Comment by nicolastrenti** [comment]
Oui, mais comme je l'ai précisé dans mon point d'avancement du 06/07, ça n'est pas possible techniquement : 

"concernant les animations au scroll (coloration progressive des trames, etc...), nous avons exploré différentes pistes possibles et nous ne sommes pas en mesure techniquement de répondre à ce besoin : l'animation de ce type, calquée sur le scroll, n'est pas possible en CSS pure, et les contraintes d'AMP en terme de javascript ne nous offrent pas d'autre option, désolé..."

**Comment by LaetitiaVerdier** [comment]
Je le lui avais transmis mais Françoise espérait qu'il s'agissait d'autre chose. Merci Nicolas
