### ISSUE TITLE
Page Hub texte cliquable + photo gauche + fond + PJ 

### ISSUE THREAD

**Issue by LucDelmon** [ampize/ampize-ucpa-corpo-recette#121]
Le snippet Page Hub texte cliquable + photo gauche + fond + PJ  a été créé.

J'attends vos retours.

**Comment by LaetitiaVerdier** [comment]
Il est bon pour nous à l'exception du visuel du rapport annuel que nous avons besoin d'aligner sur le T de Télécharger

![image](https://user-images.githubusercontent.com/40030677/42639335-128841f0-85f0-11e8-9240-f629698dc3ce.png)


Merci

**Comment by LucDelmon** [comment]
c'est bon

**Comment by LaetitiaVerdier** [comment]
merci
