### ISSUE TITLE
Snippet / A propos

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#122]
Le picto est déformé dans mon article ARPE

![image](https://user-images.githubusercontent.com/40030677/42639238-d1e9a666-85ef-11e8-94d4-2f119dcab2bc.png)

**Comment by LucDelmon** [comment]
C'est corrigé mais il faut recharger le snippet

**Comment by LaetitiaVerdier** [comment]
Merci
