### ISSUE TITLE
Bandeau alerte

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#123]
Laetitia,

Le bandeau alerte a été intégré, tu peux le voir sur la page d'accueil actuellement.

J'ai ajouté au support de formation les indications nécessaires pour savoir comment le paramétrer (slide 38).

OK pour toi ?

**Comment by LaetitiaVerdier** [comment]
Bonjour Nicolas,

Le bandeau me convient et le tuto est clair.

Peut-on avoir une option pour l'afficher sur toutes les pages si besoin exceptionnel ?

Merci

**Comment by nicolastrenti** [comment]
Oui, c'est possible, en ajoutant le code en question dans le footer du site, qui est commun à toutes les pages.
J'ai ajouté une slide au support de formation pour décrire cette manipulation (diapo 39).

**Comment by LaetitiaVerdier** [comment]
top 

merci beaucoup
