### ISSUE TITLE
Alignement / page liste

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#124]
Bonjour,

Merci d'aligner la photo sur le texte et le filet rouge dans les listes dispositifs solidaires et formations comme c'est la cas sur la page liste projets de référence

![image](https://user-images.githubusercontent.com/40030677/42640123-e49aeba6-85f1-11e8-81df-a531c47ac893.png)

**Comment by LucDelmon** [comment]
c'est fait
