### ISSUE TITLE
Cartographie

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#125]
Laetitia,

Nous avons terminé la cartographie : 
https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires/toutes-nos-implantations

Comme indiqué précédemment, elle se base sur le type de contenu "Implantations" (j'ai effectué le renommage que tu m'avais demandé).

Le chapeau que nous avons mis au dessus de la carte peut bien sûr être modifié.

Qu'en penses-tu ?

**Comment by LaetitiaVerdier** [comment]
C'est très chouette.

Nous avons deux / trois ajustements à la marge que je t'envoie dans l'après-midi.

Pour le référencement, est-il intéressant d'avoir le nom des collectivités partenaires sous la carte ? (cf. pièce jointe)

![image](https://user-images.githubusercontent.com/40030677/42688532-dac63030-869c-11e8-84a8-4a5b48265dbd.png)

**Comment by LaetitiaVerdier** [comment]
Voici la modification que nous souhaiterions pour l'affichage sur la cartographie.

Format photo souhaité : Largeur = 295px / Hauteur = 130px.

**Titre CAP** : DIN OT Bold 15px - color #0f1f28
**Typologie d'équipement** (Complexe aquatique) : DIN OT Regular 10px - color #a5a8aa (ou couleur grise de référence des maquettes de Françoise)
**URL** minuscules : DIN OT Regular 10px - color #a5a8aa (ou couleur grise de référence des maquettes de Françoise)

![carto-avec-photo_corrections-option1](https://user-images.githubusercontent.com/40030677/42694276-1f1d6568-86b2-11e8-9a51-999f73c5990d.jpg)

**Comment by LaetitiaVerdier** [comment]
Nicolas, 

J'ai un changement sur le point de la photo. L'ajout d'une photo n'est pas indispensable car nous ne pouvons pas en avoir une sur mobile, je n'y avais pas pensé.

Peux-tu au lieu de mettre l'URL apparent, mettre le texte : Accéder au site qui renvoi sur l'URL

Je pense qu'avoir une liste des espaces sous la cartographie peut nous aider en référencement naturel.

Merci encore.

Laëtitia.

**Comment by LucDelmon** [comment]
On ne met donc pas de photo ?

**Comment by LaetitiaVerdier** [comment]
On peut laisser une option mais que cela soit non-obligatoire ?

**Comment by LucDelmon** [comment]
c'est déjà le cas, vous remarquerez qu'il y  a des points sur la carte sans photo

**Comment by LaetitiaVerdier** [comment]
Oui tout à fait.

Mon erreur était de vouloir le rendre obligatoire dans mon mail de 16h05.

**Comment by LucDelmon** [comment]
Ok et on garde l'affichage en mobile avec les même dimensions ?

**Comment by LaetitiaVerdier** [comment]
J'imagine qu'il faut revoir les proportions typo pour le mobile.

Je ne me rends pas compte du résultat, je trouve votre proposition plutôt lisible sur le mobile.

Par contre, comme il n'y a pas de photo nécessairement, je veux bien remettre le texte : "Accéder au site" à la ligne.

Est-ce possible d'avoir une option : "Lire l'article" avec un lien vers l'article fiche projet pour les 15 projets de référence préparés ?

Merci

**Comment by LucDelmon** [comment]
Les typo que vous demandez sont celles qui sont actuellement sur mobile.

Je pense que sur desktop il faut voir plus grand. 15px c'est petit en Desktop pour un titre

**Comment by LaetitiaVerdier** [comment]
Tu as mon entière confiance à ce sujet car depuis le début les tailles sur mobile fournies par le studio ne vont pas.

Merci encore

Je viens de voir qu'il est possible de cliquer sur le nom de l'équipement pour accéder à l'article. 

Ca me va, peut-on le passer en orange quand un article est lié ?

merci

**Comment by LucDelmon** [comment]
Je ne crois pas que l'on ai déjà utilisé du Orange sur le site.

Quel serait le code couleur ?

**Comment by LaetitiaVerdier** [comment]
La couleur est rouge orangée comme celle que vous avez sur les liens cliquables ou les articles liés.

**Comment by LucDelmon** [comment]
Pour l'image,

Vous souhaitez que je force le format Largeur = 295px / Hauteur = 130px ? Ca déformera l'image si elle n'est pas dans ce format la.

**Comment by LaetitiaVerdier** [comment]
Oui tout à fait.

Merci

**Comment by LucDelmon** [comment]
Pour le texte "Accéder au site" je garde la couleur grise même sur 2 lignes ?

**Comment by LucDelmon** [comment]
C'est fait.

Par contre les images actuelle ne collent pas avec le format.

Je pense qu'il va falloir choisir une couleur différente entre la catégorie et le lien " accéder au site" car on voit difficilement la différence

**Comment by LaetitiaVerdier** [comment]
Effectivement, cela ne fonctionne pas.

Nous allons donc rester sur une version sobre ci-dessous

corps ​: ​16 pt
​couleur : ​#9fa5a9

<img width="1322" alt="capture d ecran 2018-07-16 a 17 19 24" src="https://user-images.githubusercontent.com/40030677/42768031-b8af6c80-891e-11e8-9c05-904b525228fe.png">

Merci

**Comment by LucDelmon** [comment]
c'est fait

**Comment by LaetitiaVerdier** [comment]
Merci Luc
