### ISSUE TITLE
Page Hub texte cliquable + photo droite

### ISSUE THREAD

**Issue by LucDelmon** [ampize/ampize-ucpa-corpo-recette#126]
Le snippet Page Hub texte cliquable + photo droite est fait

**Comment by LaetitiaVerdier** [comment]
Bonjour Luc,

J'ai essayé de changer les titres en éditant le lien des zones de texte cliquables mais n'y suis pas parvenue.

Idem pour l'autre snippet avec PJ (rapport annuel)

Merci

**Comment by LucDelmon** [comment]
C'est corrigé.

L'édition de titre ne marche pas quand le lien est vide.

J'ai mis des liens par défaut

**Comment by LaetitiaVerdier** [comment]
Merci Luc
