### ISSUE TITLE
Snippet chiffre clé + texte

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#127]
Bonjour

Est-il possible de ne pas conserver le slider quand on a un seul chiffre clé + texte au lieu de 3 

![image](https://user-images.githubusercontent.com/40030677/42645806-48b61888-85ff-11e8-9a7d-4e1804f947c8.png)

**Comment by LucDelmon** [comment]
Non,

 par contre il est possible de faire un snippet qui ne contient  qu'un chiffre clé et pas de slider

**Comment by LaetitiaVerdier** [comment]
Bonjour,

Je suis désolée. Effectivement, il est nécessaire d'avoir l'option.

Le snippet peut-il s'appeler "Chiffre clé + texte x 1" et l'autre "Chiffres clés + texte x 3" ?

Est-il possible de faire apparaître les snippets par ordre alphabétique en attendant d'avoir une preview de chaque snippet ?

C'est plus facile pour les contributeurs.

Merci

**Comment by LucDelmon** [comment]
Bonjour, l'ordre alphabétique a été mis en place hier

**Comment by LucDelmon** [comment]
c'est bon pour les 2 snippets

**Comment by LaetitiaVerdier** [comment]
Merci Luc
