### ISSUE TITLE
Snippet / partenaires

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#128]
Bonjour,

Peut-on mettre le filet rouge du snippet du dispositif partenaires au même niveau que celui du snippet "photo gauche + texte" ?

![image](https://user-images.githubusercontent.com/40030677/42687881-8f25ecd0-869a-11e8-8a7d-c507e4396280.png)

Merci

**Comment by LucDelmon** [comment]
c'est fait
