### ISSUE TITLE
Fonction / menu header

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#129]
Quand on est sur le site recette, sur un article de fond comme ARPE en pièce jointe et que l'on veut sélectionner des éléments du sous-menu type "Mission d'accessibilité", on ne peut pas.

![menu-header](https://user-images.githubusercontent.com/40030677/42688170-8be53200-869b-11e8-8da1-0033f88f1d4a.png)

Peut-on résoudre cela ?

Merci

**Comment by LucDelmon** [comment]
c'est fait

**Comment by LaetitiaVerdier** [comment]
Merci

**Comment by LaetitiaVerdier** [comment]
Bonjour,

J'ai toujours le même problème sur les articles des pages listes comme Aren'ice ou Vélodrome....

Merci

**Comment by LucDelmon** [comment]
Bonjour,

Je n'avais pas bien enregistré la solution. 

le problème est réglé.

**Comment by LaetitiaVerdier** [comment]
Merci Luc.
