### ISSUE TITLE
Nom des modules

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#13]
Les noms des modules vont être changer pour faciliter l'usage.

**Comment by nicolastrenti** [comment]
Voici les nouveaux noms des template : 

- Article texte 1 colonne large > Texte 1 colonne
- Article texte 2 colonnes > texte 2 colonnes
- Article + photo colonne droite > Texte + Photo droite
- Article + photo colonne gauche > Texte + Photo gauche
- Article + Photo colonne gauche + 3 CTA > Formation texte + CTA + Photo gauche
- Article + photo colonne droite + 1 CTA > Page Hub texte + photo droite + CTA
- Article hub + photo colonne gauche + CTA + fond > Page Hub texte + photo gauche + CTA + Fond
- Article + logos partenaires > Dispositif solidaire partenaires

- Chapeau Article > Actualité chapeau
- Chapeau loisirs > Loisirs chapeau
- Chapeau solidarité > Dispositif solidaire chapeau
- Chapeau Hub > Page Hub chapeau

- 3 articles liés + 3 photos + fond > articles liés x3 + photos + fond
- 3 articles liés + 3 photo > articles liés x3 + photos 
- 1 article lié + 1 photo > article lié
- 3 articles liés loisirs + photo full screen + CTA > Loisirs articles liés x3

- photo > Photo full screen 
  
- Infos public solidarité > Dispositif solidaire publics

- Fiche identité loisirs > Loisirs fiche d'identité

- 3 chiffres clés hub > Page Hub chiffres clés
- 1 chiffre clé + article > chiffre clé + texte

**Comment by nicolastrenti** [comment]
Les noms des modules ont été mis à jour

**Comment by LaetitiaVerdier** [comment]
Merci
