### ISSUE TITLE
Chevauchement snippet - footer / projet de référence Aren'ice

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#130]
Bonjour,

Le snippet articles liés loisirs x3 chevauche le footer au niveau du visuel sur mon article publié.

https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires/projets-de-reference/projet-de-reference/aren-ice

![image](https://user-images.githubusercontent.com/40030677/42691832-d936a274-86a9-11e8-9f30-92d7c8279a15.png)

**Comment by LucDelmon** [comment]
Effectivement, le problème était encore présent sur les très grands écrans.

c'est corrigé

**Comment by LaetitiaVerdier** [comment]
merci
