### ISSUE TITLE
Desktop/page contacts alignement 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#131]
Dans le formulaire de contacts, le menu déroulant et les contacts doivent être alignés sur le chevron, actuellement c'est beaucoup trop large et il manque un espace entre le contact et le footer

![image](https://user-images.githubusercontent.com/40030677/42694904-226cb88e-86b4-11e8-8317-b24eea34ed41.png)

Merci

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait
