### ISSUE TITLE
Picto / snippet Page hub chiffres clés

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#132]
Bonjour,

Pouvez-vous centrer dans la hauteur le picto du troisième chiffre clé - présentement la main ?

![image](https://user-images.githubusercontent.com/40030677/42757634-105cca0e-8901-11e8-8da9-95dbd9fa4ef2.png)

Merci

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait.

Cordialement
