### ISSUE TITLE
Snippets / Home Page

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#133]
Bonjour,

Voici les retours compilés pour la Home page :

**Visuel header**
- la durée de chargement du visuel header est très longue et nous empêche de voir l'animation, pouvez-vous y remédier ?

**Dans la partie Actualités** 
-  je souhaite conserver les dates en français 
- le format photo droite n'est pas le bon. Comment puis-je le modifier car il ne s'agit pas d'un snippet
- l'espace entre la date du 12 juin et le titre "sensations foil" est trop grand
- l'espace entre le titre "sensations foil" et la date suivante du 31 mai est trop grand également
- le CTA doit renvoyer automatiquement sur la page liste "actualités"

**Dans le sport de demain**
- il manque le picto à droite du premier titre
- la taille de typo des intertitres "tendances" et "études" est trop grande
![image](https://user-images.githubusercontent.com/40030677/42758900-65bb7398-8905-11e8-8fd0-5c0d603deedc.png)
- il y a trop d'espace entre les deux articles => 
![image](https://user-images.githubusercontent.com/40030677/42758948-8c16fa8a-8905-11e8-86ae-a102aa47f8f2.png)

Dans la partie "Et si le sport devenait plus qu'une passion ?"
- l'écart entre les 2 CTA doit être identique à celui appliqué dans le snippet "Aller plus loin"

**Sur le burger mobile** 
- il manque l'entrée Accueil

**Snippet Articles liés sur le mobile**
- l'espace est trop grand après le mots "inégalités" sur le mobile. Il est très bien sur le desktop.

Merci beaucoup.

**Comment by LucDelmon** [comment]
Qu'entendez-vous par le format photo droite n'est pas le bon

**Comment by LaetitiaVerdier** [comment]
Je ne peux pas changer la photo et le format est carré 518 x 571 px.

Si le format reprend celui intégré dans l'espace actualités. il devrait apparaître correctement par la suite car l'article sensations foil n'est plus valide.

**Comment by LucDelmon** [comment]
Je ne comprends pas,

Pour changer l'image, il faut modifier l'actualité dans internal content et choisir une nouvelle image.

Ensuite, les images n'ont pas de format. Ici ou ailleurs sur le site les images sont en responsives. Elles occupent toute la largeur disponible .

La hauteur est determiné automatiquement à partir du format de l'image.

En résumé pour changer de format il faut simplement uploader une image dans le format voulu et il sera respecté .

**Comment by LaetitiaVerdier** [comment]
Oui je comprends bien.

Ma question est donc de savoir si nous avons la main sur l'espace actualités de la home page ou si la mise en forme et la remontée d'informations est totalement conditionnée par la contribution dans l'espace Actualités. Si c'est le cas, la photo qui se trouve à droite du premier titre reprend-elle le visuel de la page liste "actualités" correspondant à l'article du même nom (ici : sensations foil) ?

**Comment by LucDelmon** [comment]
Non, tout est conditionné par l'internal content.

Pour avoir un format différent la solution serait de rajouter un champ image dans l'internal content

**Comment by LaetitiaVerdier** [comment]
J'ai bien compris mais visiblement on ne se comprend pas par message interposé.

Ce que je veux savoir c'est quel visuel est repris dans le champs actualité de la home ? 
Est-ce bien le champs image ci-dessous qui est repris ? 

![image](https://user-images.githubusercontent.com/40030677/42768522-0eb72e32-8920-11e8-836a-59ca032a5a98.png)

**Comment by LucDelmon** [comment]
Oui mais ce visuel est également reprit dans la page de liste d'actualités

**Comment by LucDelmon** [comment]
La Majorité des problèmes sont corrigés.

Il reste a traiter:

- Le problème de chargement du visuel
- Le problème des dates en francais 

Je n'ai pas compris le problème de l'entrée Acceuil sur Burger mobile.

**Comment by LucDelmon** [comment]
Pour le chargement du visuel. Il n'y a pas de solutions miracles.

Une fois que le site sera déployé et consulté l'image sera stocké dans le cache google avec plusieurs niveaux de qualité. Google adressera automatiquement l'image correspondant au niveau de connexion de l'utilisateur.

Par sécurité on peut toujours rajouter un délai avant le lancement de l'animation pour être sur.

**Comment by LaetitiaVerdier** [comment]
Merci Luc, effectivement on peut laisser un petit délai pour le lancement de l'animation.

Pour l'entrée "Accueil", sur la version mobile, il n'est possible de retourner sur la page accueil du site que via le logo. Pour des questions d'accessibilité, je voulais savoir s'il était possible d'ajouter Accueil avant la partie Sport des territoires par exemple.

Bien à vous,

**Comment by LucDelmon** [comment]
C'est fait pour l'animation. Elle attendait déjà 1 sec avant de se lancer. Maintenant elle attends 2

**Comment by LucDelmon** [comment]
Pour l'entrée Acceuil, je l'ai fait sur la home page. Dites moi si ca vous va et je le met partout

**Comment by LaetitiaVerdier** [comment]
Pour l'entrée Accueil. C'est parfait.

Pour la Home sur mobile : 
- le titre "Se construire par le sport" doit être dans une taille de typo supérieure au titre classique comme "Conception & Réalisation" en dessous du header et sur deux lignes.
![screenshot_2018-07-17-14-30-16](https://user-images.githubusercontent.com/40030677/42817626-ecf35370-89ce-11e8-8f49-8965671c6816.png)

- dans la partie actualités, il y a trop d'espace entre la photo et son titre "L'UCPA est choisie"
![screenshot_2018-07-17-14-30-01](https://user-images.githubusercontent.com/40030677/42817632-ee96494e-89ce-11e8-97d9-f07e206b8ac5.png)

- dans le sport de demain, "Tendances" et "Etudes" sont trop visibles
![screenshot_2018-07-17-14-29-24](https://user-images.githubusercontent.com/40030677/42817634-f08d2560-89ce-11e8-9d46-c3033f160940.png)

Merci

**Comment by LucDelmon** [comment]
Bonjour,

c'est corrigé

**Comment by LaetitiaVerdier** [comment]
Merci
