### ISSUE TITLE
Éditeur texte dans la barre d'outils

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#135]
Bonjour,

Pouvez-vous ajouter l'option "exposant" dans la barre d'outils. En effet, nous avons beaucoup de mètre carré et cube ?

Merci

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,

Malheureusement, on ne peut pas, car ça imposerait de le rajouter pour tous nos clients et ça alourdirait la barre pour d'autres utilisateurs qui n'ont pas forcément l'intérêt de cette option.

Peut-être peux-tu ajouter à ton guide de contribution cette petite astuce : 
- pour le carré ² : appuyer sur la touche "Alt" puis composer le code 253 avec le clavier numérique et relâcher la touche "Alt". Le carré apparaît.
- pour le cube ³ : idem avec le code 252.

Nicolas

**Comment by LaetitiaVerdier** [comment]
Merci pour ce tips.

C'est noté.

Laëtitia.

**Comment by LaetitiaVerdier** [comment]
y a-t-il un raccourci pour les espaces insécables ?

Merci

**Comment by nicolastrenti** [comment]
alt+255 sous windows normalement :)

**Comment by LaetitiaVerdier** [comment]
Merci encore
