### ISSUE TITLE
Disparition / Snippet Formation chapeau 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#136]
Bonjour,

Je ne trouve plus le snippet "Formation chapeau" dans les templates.

![image](https://user-images.githubusercontent.com/40030677/42765709-e964cd44-8918-11e8-912f-c0fce2681822.png)

Laëtitia.

**Comment by LucDelmon** [comment]
Bonjour,

Je ne pense pas que ce snippet ait un jour existé

**Comment by LaetitiaVerdier** [comment]
Bonjour Luc,

Si c'est le cas, c'est un malencontreux oubli de notre part.

Nous en avons besoin pour faire tous les articles sur la formation car il y a les boutons de partage en plus et un titre par rapport au snippet "Texte + photo droite" actuel.

Tous les articles ont été rédigés sur la base de ce template.

Pouvez-vous en créer un appelé "Formation chapeau" ?

Merci et désolée.

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,

Pas de souci pour ajouter ce snippet mais je vérifierai (dès que j'aurai un peu de temps) s'il était dans le devis initial. Si ce n'est pas le cas, nous devrons ajouter 2 heures aux évolutions, car il s'agit de développements supplémentaires pour nous.

**Comment by LaetitiaVerdier** [comment]
Bonjour Nicolas,

Merci.

Aucun problème.

On ne peut pas s'en passer de toute façon.

**Comment by LucDelmon** [comment]
Il est fait

**Comment by LaetitiaVerdier** [comment]
Merci Luc
