### ISSUE TITLE
Photo / Portrait du snippet témoignage

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#137]
Bonjour,

Le rendu final doit être un cercle de 219 x 219 px, quand nous intégrons une photo portrait, elle se déforme toujours en oval.

![image](https://user-images.githubusercontent.com/40030677/42767453-58e2af8e-891d-11e8-95c6-25d26f6dbed7.png)

Pouvez-vous y remédier ?

Merci

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,
Nous ne pouvons pas "cropper" à la volée la photo de façon à ce qu'elle soit carrée, c'est à vous de le faire auparavant (par exemple dans l'éditeur d'image).
On avait déjà abordé ce point dans cette issue : #83

**Comment by LaetitiaVerdier** [comment]
Bonjour Nicolas,

Effectivement, mon problème reste entier car le rond devient systématiquement ou presque un oval quand les contributeurs, autre que moi, chargent les photos.

Je vais leur rappeler de prendre une photo carrée 219 x 219 px mais je pense qu'il y aura des disparités.

Ils ont du mal avec l'éditeur et j'ai dû cropper déjà plusieurs photos pour eux. 

Bien à toi,

Laëtitia
