### ISSUE TITLE
Problème taille picto / Snippets Loisirs Chapeau 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#139]
Bonjour,

Le picto change de taille quand il est modifier. Pouvez-vous résoudre cela ?

![picto 1](https://user-images.githubusercontent.com/40030677/42809136-2ac9863e-89b5-11e8-962b-0b254aad154c.JPG)

Merci

**Comment by LaetitiaVerdier** [comment]
Idem 

La taille du picto est très petite dans le dernier à propos créé par ma collaboratrice sous actualités.

Pourtant sur le snippet la taille est bonne mais le format change quand le nouveau picto est chargé

![image](https://user-images.githubusercontent.com/40030677/42813859-9e540928-89c2-11e8-9711-a22e7025e823.png)

Merci

**Comment by LucDelmon** [comment]
Concernant le premier problème.

Une fois le nouveau picto chargé, il faut cliquer a nouveau dessus et choisir resize dans les options.

Le menu suivant s'ouvre.

![image](https://user-images.githubusercontent.com/35261367/42823221-4f333218-89dd-11e8-9996-fdb44fb0a211.png)

Il faut ensuite indiquer les dimensions souhaitées et elles seront conservées.

Sinon je peux toujours forcer des dimensions mais il faudra que tout les pictos soient de la même taille.

**Comment by LucDelmon** [comment]
Pour le snippet A propos c'est un autre problème.

La taille du picto est fixé. Même si vous la modifiez elle reviendra toujours a cette taille.

J'avais fait cela car le picto est présent en mobile et la taille doit être différente sur le mobile ( je forcais une taille différente).

J'ai modifié le template, il est maintenant possible de choisir la taille du picto de le même manière que pour chapeau loisir( avec le menu ou en bougeant les coins bleus).

La taille est conservé pour la publication.

En mobile la taille est divisé par 2.

**Comment by LucDelmon** [comment]
Par contre j'ai remarqué que vos pictos ont une très haute définition ( aux alentours de 1000*1000).

C'est très mauvais pour les performances. Il ne faut pas charger une image aussi grosse pour un picto. Le chargement de la page web se verra ralentit. De plus cela rend la manipulation très difficile avec Froala car l'image arrive avec sa taille initiale et prend tout l'écran.

**Comment by LaetitiaVerdier** [comment]
Merci C'est noté.

Pour les pictos, je vais demander à ce qu'ils soient alléger. Merci pour l'alerte Françoise et moi ne l'avions pas vu.

**Comment by LaetitiaVerdier** [comment]
Pour les pictos, nous souhaiterions un cellule de 100x100 px dans laquelle viendrait s'importer le picto **centré** et contraindre la taille du picto.

La cellule pour le mobile doit être ramenée à 90%.

**Comment by LucDelmon** [comment]
Bonjour,

Actuellement il est possible de mettre la taille de picto que l'on veut  ( en la modifiant à l'édition). Le picto est ensuite automatiquement réduit en mobile.

Vous êtes sur de vouloir perdre ca et de forcer la taille du picto a 100*100 ?

**Comment by LaetitiaVerdier** [comment]
Bonjour Luc,

Non c'est bon j'ai intégré cette information à leur tuto.

On peu laisser comme ça.

Laëtitia.

**Comment by LucDelmon** [comment]
Ok, par contre la taille en mobile est actuellement de 50%. Vous voulez passer a 90%?

**Comment by LaetitiaVerdier** [comment]
Je ne sais pas car en fonction des cas de modules je n'ai pas toujours la même taille sur mobile.

Certains s'affichent très grands et d'autres aux bonnes dimensions.

**Comment by LaetitiaVerdier** [comment]
Nous avons rechargé les pictos allégés sur toutes les pages.

Je pense que du coup. 

Il faudra vérifier les pages liste

Sinon tout est bon.
