### ISSUE TITLE
Trop d'espaces blancs

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#14]
Globalement, il y a trop de blancs (d'espaces) avant les tirets et après.

**Comment by nicolastrenti** [comment]
Les espaces ont été réduits dans les snippets (nécessite de réinjecter les snippets modifiés dans un texte riche pour voir les modifications)

**Comment by LaetitiaVerdier** [comment]
Merci je vais tester
