### ISSUE TITLE
Page liste dispositifs solidaires / Modifications

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#140]
Bonjour,

Je ne sais pas comment modifier les pages liste.

Dans le cas des dispositifs solidaires, je souhaite faire des changements.

Le texte sous le titre doit être remplacer par : 
Grâce à de multiples actions sur le terrain, les équipes UCPA s'engagent concrètement et durablement pour l'accès au sport de tous.

Le CTA "Voir toutes nos implantations" doit être supprimé.

Sous le filet, il manque les chevrons à droite qui figurent aussi sur la page liste "Projets de référence"

Le texte "Dispositifs solidaires" au-dessus des articles doit être changé par : Découvrez nos dispositifs

![image](https://user-images.githubusercontent.com/40030677/42876938-79cc7b0a-8a88-11e8-9a90-fdfd2dea73c5.png)

Merci

**Comment by nicolastrenti** [comment]
C'est fait.
Pour info, les pages Listes sont modifiables par l'intermédiaire du menu "Templates" dans le menu du site. Par contre, il ne s'agit pas de l'éditeur de texte riche classique, mais d'un éditeur de code html.

**Comment by LaetitiaVerdier** [comment]
Merci
