### ISSUE TITLE
Snippet dispositifs solidaires partenaires

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#141]
J'ai besoin de remplacer le texte ipsem lorum par ce texte : 
Tous les dispositifs sont élaborés en concertation avec nos partenaires qui accompagnent les publics au quotidien et ont une connaissance fine de leurs attentes et problématiques spécifiques.

Pouvez-vous me confirmer que nous ne sommes pas limités dans le nombre de partenaires et logos dans cet espace car nous en avons souvent plus ?

Merci

**Comment by nicolastrenti** [comment]
Le texte a été modifié.

Pour la question du nombre de logos et de partenaires, deux solutions : 
- soit nous laissons comme ça, auquel cas le contributeur doit passer en mode "code view" dans l'éditeur et sélection, copier et coller plusieurs fois les lignes suivantes (qui correspondent au logo + au nom du partenaire) : 
![image](https://user-images.githubusercontent.com/1919354/42878647-11e01d48-8a8e-11e8-871f-f7cd32c6d451.png)
- soit nous en mettons d'office plusieurs (5 ?) dans le snippet et le contributeur supprime ceux en trop le cas échéant (sélection dans l'éditeur de texte riche puis touche "Suppr")

**Comment by LaetitiaVerdier** [comment]
Merci Nicolas.

Je préfère que l'on en mette 5 d'office et que je fasse la manip dans le code s'il y en a plus.

Merci

**Comment by nicolastrenti** [comment]
C'est fait Laetitia
