### ISSUE TITLE
double footer

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#142]
Bonjour, 

Deux footer se sont insérés l'un sur l'autre : 
![image](https://user-images.githubusercontent.com/39916838/42879239-2ed8946e-8a90-11e8-97b0-33d645c1e8c6.png)

je l'ai remarqué dans l'espace Actualiés. Je ne sais pas pour les autres espaces.

**Comment by nicolastrenti** [comment]
Bonjour Angèle, 

Je ne constate pas le problème. Sur quel page as-tu ce double footer ? En preview ou sur le site en ligne ?
Merci !

**Comment by ANGELEROBLOT** [comment]
La page actualité est normal, un seul footer. Mais tous les articles de la partie actualité ont un double footer : 
![image](https://user-images.githubusercontent.com/39916838/42880081-44a97fee-8a93-11e8-86d8-4b1ffc55d534.png)

je vois cela à la fois en mode preview et sur le site en ligne

**Comment by nicolastrenti** [comment]
C'est corrigé, on avait oublié un footer en trop dans cette page effectivement.
