### ISSUE TITLE
Editeur photo

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#143]
Tous les contributeurs rencontrent des difficultés avec l'éditeur d'images.

Avez-vous des développements en cours ? 

Par exemple, le nom des visuels ne s'affiche pas et c'est un vrai handicap pour nous.

Merci

**Comment by nicolastrenti** [comment]
Laetitia,

Qu'entends-tu par "nom des visuels" ?
Tu parles peut-être du nom des fichiers dans cet écran de la Médiathèque ?
![image](https://user-images.githubusercontent.com/1919354/42879488-22bcf304-8a91-11e8-887c-6885f80f7eb1.png)

**Comment by LaetitiaVerdier** [comment]
Oui c'est tout à fait ça.

**Comment by nicolastrenti** [comment]
Ce que je peux te proposer de mieux, en attendant une refonte plus complète de la médiathèque, c'est l'affichage du nom du fichier quand on survole l'icône qui permet de sélectionner une image : 

![image](https://user-images.githubusercontent.com/1919354/42951241-0c1c6914-8b76-11e8-83df-abfb1258795d.png)

**Comment by LaetitiaVerdier** [comment]
Oui ça me va.

Merci
