### ISSUE TITLE
Lien CTA ou hypertexte

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#144]
J'ai essayé d'en faire plusieurs mais cela ne fonctionne pas apparemment

J'ai voulu, par exemple, renvoyer le CTA "Voir tous les dispositifs" de la page hub Le sport pour tous

https://ucpa-corpo.recette.ampize.me/le-sport-pour-tous#le-sport-pour-tous/dispositifs-solidaires

Peux-tu me donner la règle à observer dans ce cas ?

Merci

**Comment by nicolastrenti** [comment]
A priori, la manipulation suivante doit te permettre de mettre en place les liens : 

Après avoir inséré un snippets, cliquer n'importe où sur le libellé qui doit faire office de lien.
La barre suivante apparaît alors : 
![image](https://user-images.githubusercontent.com/1919354/42880243-ee5220a0-8a93-11e8-8adc-c4e75e778c93.png)
Cliquer sur "Edit link".
Dans la fenêtre qui s'ouvre, coller l'URL de la page cible, sans le "https://ucpa-corpo.recette.ampize.me" devant.
Par exemple, pour faire un lien vers "https://ucpa-corpo.recette.ampize.me/le-sport-pour-tous/mission-d-accessibilite", je saisis juste "/le-sport-pour-tous/mission-d-accessibilite" ; 

![image](https://user-images.githubusercontent.com/1919354/42880330-2bf69f58-8a94-11e8-8ef4-dfbfc3fd6e10.png)

Cliquer sur "Update" et sauvegarder.

Le lien ne sera pas effectif en preview, mais bien correct une fois le site publié.

**Comment by LaetitiaVerdier** [comment]
C'est ce que j'ai fait

Donc cela doit fonctionner.

Je n'ai juste pas de moyen de vérifier.
