### ISSUE TITLE
nom de rubrique / Actualités

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#145]
Tous les noms de rubrique de la page actualités ne sont pas à jour ni en preview, ni sur le site en ligne. 
Voila ce qui apparait : 
![image](https://user-images.githubusercontent.com/39916838/42880269-082b9998-8a94-11e8-9230-f64f43537379.png)

Voici les noms validés et rentrés dans l'espace de travail Ampize.me: 
Séjours et tendances
Espaces sportifs
Institutionel
Economie Sociale et Solidaire
Solidarité
Formation
Evénements

Je n'ai pas encore écris des articles pour toutes les catégories, mais il est sûre qu'il y a un problème avec "Séjours et tendances" car j'ai déjà écris 3 articles dans cette rubrique et ils n'apparaissent nul part.

**Comment by nicolastrenti** [comment]
Angèle,

Le libellé exact attendu actuellement est "séjours & tendances" et non "Séjours et tendances" (voir support de formation p36 pour les libellés exacts attendus). Nous nous basons sur ces libellés pour les filtres, il faut donc les respecter scrupuleusement.
Si certains sont à modifier, il faut nous l'indiquer, mais il faut impérativement à ce stade qu'on parte sur la bonne orthographe et qu'on ne revienne plus en arrière.
Typiquement, dans la liste que tu fournis, "Institutionel" n'est pas correctement orthographié je pense (2 "n").

**Comment by ANGELEROBLOT** [comment]
D'accord. 

Peux-tu, s'il te plait, me fournir la liste des noms de rubrique que vous avez ? 

Car celle que je t'avais fourni est celle qui est au dessus ...

**Comment by nicolastrenti** [comment]
séjours & tendances
économie Sociale et Solidaire
événements
formation
institutionnel
solidarité
espaces sportifs

**Comment by ANGELEROBLOT** [comment]
D'accord, merci. 

Je t'avais envoyé la liste définitive le 20 juin, par mail : 
Dernières actualités
Séjours et tendances
Espaces sportifs
Institutionnel
Economie Sociale et Solidaire
Solidarité
Formation
Evénements
Je me suis donc basé sur cette liste pour rentrer mes articles, puisque tu m'avais confirmé avoir modifié le naming. 
Peux-tu s'il te plait, rentrer ces noms ? 
Merci

**Comment by nicolastrenti** [comment]
Très bien, on part donc sur ces libellés. Il n'y aura donc pas d'accent sur le premier "E" de "Evénements" et "Economie Sociale et Solidaire", on est OK là-dessus ? Désolé d'insister mais c'est deux lettres différentes pour nous :)

**Comment by ANGELEROBLOT** [comment]
Oui tout à fait! Merci Nicolas

**Comment by nicolastrenti** [comment]
C'est bon désormais normalement, Angèle :)

**Comment by ANGELEROBLOT** [comment]
Merci Nicolas :)
