### ISSUE TITLE
Disparition pictos / Actualités

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#146]
Suite aux conseils de Laetitia, je "change size" les pictogrammes en 100x100 : 
![image](https://user-images.githubusercontent.com/39916838/42889752-79bbc59e-8aab-11e8-9a44-f356cdb06af1.png)

Il apparait correctement dans l'espace de travail sur mon article "l'ucpa est choisie pour gérer le stade nautique georges vallerey". 

Cependant, en preview ou sur le site le picto n'apparait plus : 
![image](https://user-images.githubusercontent.com/39916838/42889862-ae6ae612-8aab-11e8-99d6-a75260f57f05.png)

ce phénomène se produit sur tous les articles où j'ai "change size" les picto. Ceux que je n'ai pas retouché apparaissent toujours.

**Comment by nicolastrenti** [comment]
J'ignore comment cela se produit. J'ai testé sur "Une Ecole de Mer sortie de Terre" en spécifiant la largeur 100px et je n'ai pas eu de souci. 

Attention, si vous précisez une largeur ET une hauteur, tu vas perdre les proportions de l'image. C'est le cas pour le vélo par exemple, qui n'est pas une image carrée à la base et qui se retrouve déformée si on met 100 en largeur et 100 en hauteur. En général, imposer une largeur suffit.

Pour tes articles sur lequel le problème apparaît, voici la procédure pour faire réapparaître les images : 
- dans l'éditeur, cliquer sur l'image
- cliquer sur l'icône "Style" et choisir "Fixed size"
- republier l'article

Autre point, déjà souligné par Luc à Laetitia : pour de tels pictos qui feront 100x100 à l'affichage, uploader des images de plus de 1000px de large est fortement déconseillé, car cela ralentira le site inutilement (et nuira à la qualité du picto, fortement redimensionné par le navigateur).

**Comment by ANGELEROBLOT** [comment]
Merci Nicolas. 

Je fais les manip. 

Laetitia me dit de te dire qu'elle a demandé aux graphistes d'alléger tous les pictos. cependant aucun ne fait plus de 500px
