### ISSUE TITLE
Cas particulier / Offres de formation

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#147]
Bonjour,

A l'usage, nous rencontrons un dilemme sur deux snippets utilisés pour les articles "offres de formation" comme l'article activités aquatiques de la natation.

Concrètement, nous avons besoin d'avoir un deuxième "A propos" où l'on peut ajouter le CTA "Voir nos offres de formation" en dessous du texte de l'A propos.
![image](https://user-images.githubusercontent.com/40030677/42937426-454a46a6-8b4f-11e8-808a-c8ed7f54a8d2.png)

Si vous avez besoin de le nommer, on peut mettre "A propos + CTA"

De même, nous souhaitons supprimer le CTA Voir les offres de formation dans le snippet "Formation texte + CTA + Photo gauche

Merci pour votre aide.

Laëtitia.

**Comment by nicolastrenti** [comment]
J'ai ajouté un snippet "A propos + CTA" et supprimé le CTA "Voir les offres de formation" du snippet "Formation texte + CTA + Photo gauche".

Peux-tu me dire si ça te convient ?

**Comment by LaetitiaVerdier** [comment]
Très bien 

Merci
