### ISSUE TITLE
Problème lien / Management d'espaces sportifs

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#148]
Bonjour,

Quand je clique sur l'article Management d'espaces sportifs, je tombe sur :
https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires/**conception-et-realisation-d-espaces-sportifs**

Pouvez-vous remettre le bon lien ?

Merci

**Comment by LaetitiaVerdier** [comment]
Je viens de changer le naming dans les settings mais ne suis pas sûre que cela soit bon car quand je me connecte j'ai ce message comme pour la conception d'espaces d'ailleurs 

![image](https://user-images.githubusercontent.com/40030677/42938294-12c81386-8b52-11e8-8ebd-cff6291c4781.png)

**Comment by nicolastrenti** [comment]
C'est résolu !

**Comment by LaetitiaVerdier** [comment]
Merci c'est super.

Je ne sais pas si tu as eu le temps de voir mais le site prend forme.

Nous sommes très contents.

**Comment by nicolastrenti** [comment]
Oui, c'est carrément top, le site a fière allure, on est très contents aussi !
Luc est en congés pendant les 15 prochains jours, je prends donc le relais sur les corrections d'anomalies. Si certaines sont vraiment urgentes, n'hésite pas à le signaler pour que je les traite en priorité.

**Comment by LaetitiaVerdier** [comment]
Tant mieux.

C'est un vrai beau travail d'équipe.

Je n'ai que des éloges sur le site corpo.

Il faudra absolument que nous fêtions cela ensemble avec toute l'équipe UCPA, toi et Luc notamment que nous sollicitons beaucoup mais n'avons jamais rencontré ;-)

Pour l'UCPA, il s'agit d'un beau projet qui se concrétise et pour moi d'un an de travail qui prend fin...

Comment je peux te signaler une demande urgente ? Je te le mets dans l'objet du ticket ?

Bien à toi,

Laëtitia.

**Comment by nicolastrenti** [comment]
Oui, tu peux rajouter [URGENT] dans l'objet du ticket.
Merci !
