### ISSUE TITLE
Problème affichage / page liste Projets de référence

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#149]
Nous avons les premières lignes qui s'affichent bien mais pas la suite :
![fireshot capture 25 - projets de reference_ - https___ucpa-corpo recette ampize](https://user-images.githubusercontent.com/40030677/42950720-eae525de-8b74-11e8-81c4-2747b5c3c2d8.png)

**Comment by nicolastrenti** [comment]
C'est effectivement lié aux titres de longueurs différentes (parfois sur 2 lignes, parfois sur 1 ligne). On va trouver une solution pour uniformiser la hauteur, ça éviter cette mise en page chaotique.

**Comment by LaetitiaVerdier** [comment]
Top.

merci

**Comment by LucDelmon** [comment]
C'est fait
