### ISSUE TITLE
Alignement bloc noir / home page

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#150]
Bonjour,

Sur la Home, le bloc noir de la partie DÉVELOPPER LES LOISIRS POUR TOUS AU CŒUR DES TERRITOIRES n'est pas aligné sur le bord de droite, il déborde du cadre 

![image](https://user-images.githubusercontent.com/40030677/42954126-3d515002-8b7c-11e8-8d86-2dedd71bd869.png)

**Comment by nicolastrenti** [comment]
C'est bon normalement.

**Comment by LaetitiaVerdier** [comment]
Ca n'est pas bon de mon côté.

Le bloc déborde à droite

**Comment by nicolastrenti** [comment]
OK, désolé, c'est moi qui avais mal compris la première fois.
En fait, j'avais aligné le haut du titre de gauche avec le haut du bloc de droite (je peux revenir en arrière sur ce point si nécessaire).
Désormais, j'ai bien fait en sorte que le bloc de droite ne déborde pas sur la droite.

**Comment by LaetitiaVerdier** [comment]
C'est bon pour nous 

merci
