### ISSUE TITLE
Page liste / Contacts

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#151]
Bonjour,

J'ai rentré tous les contacts. Comme certains noms de service ont changé, certains n'apparaissent pas.

Je vous remets ici ceux qui manquent pour que vous puissiez les ajouter :
 
Pôle achats
Pôle égalité des chances
Service clients
Pôle formation

Merci

**Comment by nicolastrenti** [comment]
Ça doit être bon désormais !

**Comment by LaetitiaVerdier** [comment]
Oui tout est bon.

Merci
