### ISSUE TITLE
Home page - photo full screen loisirs sportifs

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#152]
Bonjour Nicolas,

Sur la home, nous avons un problème de taille de visuel pour la partie Loisirs sportifs. Sur la maquette le visuel est full screen soit 2544 x 702 px pour le desktop et 640 x 470 px pour le mobile, format identique aux images des header.

![image](https://user-images.githubusercontent.com/40030677/43011376-89525ba0-8c43-11e8-9143-2bd21f62b440.png)

Est-il possible de faire la modification ?

Merci

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,
J'ai fait la modif pour mettre l'image en full screen.
Par contre, actuellement, c'est le même format en desktop et mobile. Comment souhaites-tu qu'on gère les choses ? Tu préférerais que la même image soit croppée de manière automatique ou que tu charges toi-même deux images différentes, l'une pour le desktop et l'autre pour le mobile ?

**Comment by LaetitiaVerdier** [comment]
Je préfère que l'on garde notre habitude d'avoir une pour le mobile et une pour le desktop.

J'ai fait le mobile ci-dessous
![hp-loisirs-sportifs-ucpa-m](https://user-images.githubusercontent.com/40030677/43070187-72622eec-8e6f-11e8-85d0-03c8a7507d84.jpg)

Merci

**Comment by nicolastrenti** [comment]
C'est fait, j'ai mis l'image ci-dessus pour la version mobile.

**Comment by LaetitiaVerdier** [comment]
Merci beaucoup
