### ISSUE TITLE
Page contacts / emplacement photo

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#153]
Nous souhaitons conserver le format photo utilisé dans le snippet témoignage de 219 x 219 px pour la page contact.

Est-ce possible ?

Merci

<img width="1373" alt="capture d ecran 2018-07-20 a 17 53 22" src="https://user-images.githubusercontent.com/40030677/43012662-0bdd07fc-8c47-11e8-8275-18916df87ef8.png">
<img width="1403" alt="capture d ecran 2018-07-20 a 17 51 52" src="https://user-images.githubusercontent.com/40030677/43012666-0d68ce9e-8c47-11e8-8195-1151b8d3b006.png">

**Comment by nicolastrenti** [comment]
C'est fait, j'ai repris les tailles des photos du snippet témoignage.

**Comment by LaetitiaVerdier** [comment]
Merci
