### ISSUE TITLE
[URGENT] Partie Groupe du site + Formations

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#154]
Bonjour Nicolas,

Je vais intégrer les articles du Groupe et de Formations.

Par contre, sais-tu comment je peux faire pour les regarder sur https://ucpa-corpo.recette.ampize.me/formations

A ce jour, il me faudrait leur URL directe car je ne peux pas les rattacher à la page Hub sans le lien étant donné qu'il n'y a pas menu déroulant me permettant de les sélectionner comme pour le sport pour tous par exemple.

![image](https://user-images.githubusercontent.com/40030677/43065594-9b41c078-8e62-11e8-84e3-245283d7dfed.png)

**Comment by nicolastrenti** [comment]
Bonjour Laetitia, 

Pour chacune des pages de l'arborescence, dans le Site Builder, tu peux trouver leur URL en allant dans les Page Settings, onglet URL. Il y a un champ "Vanity URL" qui correspond à l'URL à laquelle la page est accessible.

![image](https://user-images.githubusercontent.com/1919354/43066786-e4d06da4-8e65-11e8-888b-047857841e79.png)

![image](https://user-images.githubusercontent.com/1919354/43066819-fb73cab0-8e65-11e8-97b8-1f60d5f37970.png)

**Comment by LaetitiaVerdier** [comment]
Top merci Nicolas
