### ISSUE TITLE
Chapeau / Pages listes thématiques - Actualités

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#155]
J'ai intégré dans le HTLM le texte suivant en chapeau de la page liste mère Actualités, je ne sais pas comment le dupliquer dans les autres pages listes téhmatiques :+1: 

Retrouvez ici toute l'actualité du groupe UCPA : les nouveaux séjours sportifs ou colonies de vacances, les nouveaux équipements confiés à l'UCPA et tous nos événements sportifs, solidaires et institutionnels. L'équipe du service presse se tient à votre disposition pour répondre à vos questions et demandes spécifiques.

![image](https://user-images.githubusercontent.com/40030677/43077535-0a2be3cc-8e88-11e8-9539-6b084e3cd09c.png)

Ex : séjours et tendances 
https://ucpa-corpo.recette.ampize.me/accueil/actualites/voir-plus-d-articles?category=S%C3%A9jours%20et%20tendances

J'ai besoin d'intégrer ce même texte partout, à la place de : 

Sur un catamaran ou une planche à voile, l'UCPA propose pour la 1ère fois au grand public d'expérimenter le foil, véritable ovni capable de voler sur l'eau

Merci

**Comment by nicolastrenti** [comment]
C'est fait.
Pour info, pour les pages "Voir plus d'articles", on a mis ce texte dans le bloc "Chapeau" de la page (cliquer sur l'icône HTML pour modifier le code).

**Comment by LaetitiaVerdier** [comment]
Merci Nicolas
