### ISSUE TITLE
Problème / Affichage de pictos

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#156]
Nicolas,

Nous avons de nouveau un problème avec les pictos.

Pourtant, nous avons rechargé tous les nouveaux pictos en version allégée, suite à vos conseils. Cependant, ils n'apparaissent plus dans les "A propos" et sont immenses sur le mobile

![image](https://user-images.githubusercontent.com/40030677/43080619-61ee09ac-8e90-11e8-8546-9baa209d01bc.png)

peux-tu jeter un oeil ?

Merci

**Comment by nicolastrenti** [comment]
Peux-tu me donner l'URL d'une page qui pose problème avec ce snippet stp ? Merci !

**Comment by LaetitiaVerdier** [comment]
https://ucpa-corpo.recette.ampize.me/le-groupe

**Comment by nicolastrenti** [comment]
Laetitia,

Pour résoudre ce problème : 
- Cliquer sur le picto
- Cliquer sur l'icône "Style"
- Choisir "Fixed size"
- Préciser si nécessaire une "width"  (100)

![image](https://user-images.githubusercontent.com/1919354/43126012-d6e1be5c-8f2b-11e8-9a7a-6ae3309ba272.png)

J'ai fait la manipulation sur la page Groupe.
