### ISSUE TITLE
Intégration pièce jointe / CTA - Article gouvernance

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#157]
Bonjour,

Voici l'article dans lequel, je souhaite ajouter une pièce jointe derrière le CTA 
![image](https://user-images.githubusercontent.com/40030677/43082432-5a8079e4-8e94-11e8-9d6e-6fb1a223419b.png)

https://testbo.ampize.me/site-builder/Site5ab36083948db

Je te joins le fichier concerné.

![gouvernance-ucpa](https://user-images.githubusercontent.com/40030677/43082844-501b7426-8e95-11e8-8bc9-15c24c380d5b.JPG)

Merci

**Comment by nicolastrenti** [comment]
Dans quel format est cette PJ à la base ? Tu souhaites l'intégrer en tant qu'image ?

**Comment by LaetitiaVerdier** [comment]
Non pas spécialement.

En PDF serait mieux.

**Comment by nicolastrenti** [comment]
Tu peux m'envoyer le fichier original par mail dans ce cas s'il-te-plaît ? merci !

**Comment by LaetitiaVerdier** [comment]
J'ai demandé qu'on me le fasse car mon acrobat ne fonctionne plus.

**Comment by LaetitiaVerdier** [comment]
Voici le PDF

Merci
[gouvernance-2017.pdf](https://github.com/ampize/ampize-ucpa-corpo-recette/files/2220144/gouvernance-2017.pdf)

**Comment by nicolastrenti** [comment]
Laetitia,

J'ai ajouté le PDF sur notre serveur.
Voici l'URL du lien à indiquer derrière le CTA : resource/ucpa/pdf/gouvernance-2017.pdf

**Comment by LaetitiaVerdier** [comment]
Merci Nicolas
