### ISSUE TITLE
Diaporama

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#158]
Dans la partie histoire, j'ai besoin d'avoir 10 slides dans le diaporama.

Aujourd'hui, j'en ai uniquement 3. 

Comment dois-je faire pour en ajouter ?

Merci

**Comment by nicolastrenti** [comment]
Voici la procédure : 
- insérer le snippet en question dans le texte riche
- aller dans "Code view" (dernière icône de la barre d'outil de l'éditeur)
- trouver la portion de code correspondant au diaporama (ctrl + F puis rechercher diaporama)
- juste avant la balise de fermeture `</amp-carrousel>` copier-coller autant de fois que nécessaire le code suivant (qui correspond à 1 slide) : 

![image](https://user-images.githubusercontent.com/1919354/43085338-0e8af2ec-8e9b-11e8-95ec-d76fcafbc367.png)

Pour 6 slides par exemple, le code aura l'allure suivante : 

![image](https://user-images.githubusercontent.com/1919354/43085325-056fc174-8e9b-11e8-8e80-4470eae101ed.png)

- cliquer à nouveau sur l'icône "Code view" pour revenir en mode classique

Si c'est trop compliqué, n'hésite pas à me le dire, je le ferai pour toi

**Comment by LaetitiaVerdier** [comment]
C'est tout bon.

Merci
