### ISSUE TITLE
Absence - Vanity URL / UCPA c'est quoi ?

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#159]
Nicolas,

Je n'ai pas de vanity URL pour la partie l'UCPA, c'est quoi ? sous Groupe > Découvrir

Bien à toi,

Laëtitia.

**Comment by nicolastrenti** [comment]
C'est ajouté !

**Comment by LaetitiaVerdier** [comment]
Merci
