### ISSUE TITLE
Page liste / Offres de formation

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#160]
Il manque les chevrons sur la page liste Offres de formation à droite

https://ucpa-corpo.recette.ampize.me/formations/offres-de-formation

cf. https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires/projets-de-reference

Il y a également un problème d'affichage des articles sur la page liste Offres de formation.

Bien à toi,

Laëtitia.

**Comment by nicolastrenti** [comment]
Ça doit être bon désormais !

**Comment by LaetitiaVerdier** [comment]
Merci Nicolas
