### ISSUE TITLE
Article UCPA Formation

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#161]
J'ai une page 404 au lieu de mon article fini 

https://ucpa-corpo.recette.ampize.me/formations/secteurs

Merci

**Comment by nicolastrenti** [comment]
C'est corrigé !

**Comment by LaetitiaVerdier** [comment]
J'ai le même problème avec les diplômes

/formations/diplomes

Merci
