### ISSUE TITLE
URGENT / CTA page liste

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#162]
Bonjour Nicolas,

J'ai besoin de mettre les liens pour les différentes pages liste

Pour la liste, **/le-sport-des-territoires/projets-de-reference**
J'ai besoin de mettre le lien suivant derrière le CTA Voir toutes nos implantations avec l'option ouverture dans une nouvelle fenêtre : /le-sport-des-territoires/toutes-nos-implantations

Pour la liste, **/le-sport-pour-tous/dispositifs-solidaires**
J'ai besoin de mettre ce lien, idem dans une nouvelle fenêtre : /le-sport-pour-tous/mission-d-accessibilite

Pour la liste, **/formations/offres-de-formation** 
J'ai besoin de mettre ce lien, idem dans une nouvelle fenêtre : /formations/secteurs

Question relative à /formations/secteurs, je ne suis pas certaine que cela soit très clair pour le référencement car il s'agit de notre organisme de formation UCPA Formation

Merci

**Comment by LaetitiaVerdier** [comment]
J'ai oublié celui-ci
**/le-sport-des-territoires/toutes-nos-implantations**
J'ai besoin de mettre ce lien, idem dans une nouvelle fenêtre pour le CTA : /le-sport-des-territoires/projets-de-reference

**Comment by nicolastrenti** [comment]
Hello Laetitia,

C'est pris en compte.
Pour la page UCPA Formation, la nouvelle URL est /formations/organisme-formation-UCPA-formation
J'ai fait la modif du lien qui était sur la page /formations, mais je ne sais pas si tu avais référencé cette page ailleurs.

**Comment by LaetitiaVerdier** [comment]
D'accord, du coup tu peux le changer sur le CTA de la page /formations/offres-de-formation
/formations/organisme-formation-UCPA-formation

Sinon dis-moi comment faire et je l'ajoute à mon tuto.

Merci

**Comment by nicolastrenti** [comment]
Normalement c'est bon

**Comment by LaetitiaVerdier** [comment]
Merci
