### ISSUE TITLE
Version mobile / Problème affichage sur toutes les pages listeActualités 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#163]
Nicolas,

Dans toutes les pages liste sur le mobile : Actualités + actualités thématiques / Projets de référence / Dispositifs solidaires / Formations et Implantations

- le titre touche le header et le texte touche le filet rouge
![screenshot_2018-07-25-15-29-26_resized](https://user-images.githubusercontent.com/40030677/43203901-bd67d0f2-901f-11e8-88bf-88b3de4f9528.png)

- les images / visuels ne sont pas au bon format car normalement les visuels sont carrés comme dans les articles liés x 3
- dans actualités, nous avons un problème avec le menu déroulant qui masque le premier article et les catégories doivent être alignées à gauche (cf. s'inspirer du menu déroulant se trouvant dans **contact**)

**Comment by nicolastrenti** [comment]
Pour les 2 premiers points, j'ai fait une modification sur la page Actualités (et uniquement cette liste pour l'instant).
Tu peux me dire si ça te semble mieux avant que je reporte la modif sur les autres listes ?

**Comment by LaetitiaVerdier** [comment]
C'est top.

Parfait

**Comment by nicolastrenti** [comment]
J'ai apporté les modifs sur toutes les listes, il reste juste le point relatif au menu déroulant.

**Comment by LaetitiaVerdier** [comment]
Merci

**Comment by nicolastrenti** [comment]
Le menu déroulant des actualités en mobile est corrigé.
