### ISSUE TITLE
Version mobile / snippet A propos + A propos et CTA

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#164]
Les maquettes prévoyaient un filet rouge entre le titre et l'article sur la version mobile.

![image](https://user-images.githubusercontent.com/40030677/43204622-ad9ad33e-9021-11e8-84a8-0e2d362c91a9.png)

Cela est-il possible ?

Si c'était trop compliqué à mettre en place.

Peux-tu augmenter l'espace entre le titre et l'article ?

Merci

**Comment by nicolastrenti** [comment]
Peux-tu me donner l'URL d'une page où ce snippet a été intégré ? Car normalement le filet rouge devrait être présent.

**Comment by LaetitiaVerdier** [comment]
https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires

**Comment by nicolastrenti** [comment]
C'est corrigé sur cette page. Peut-être qu'elle avait été alimentée avec une ancienne version du snippet.
Si tu rencontres le problème sur d'autres pages n'hésite pas à le signaler.

**Comment by LaetitiaVerdier** [comment]
Ah mince.

C'est bien noté.

Merci
