### ISSUE TITLE
URGENT ! fermeture intempestive

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#165]
Bonjour, 

Je suis en pleine intégration des communiqués de presse sur l'espace Actualités. L'article que je suis en train d'intégrer s'est fermé deux fois de suite, sans raison, j'ai perdu le contenu écrit. Maintenant je suis bloquée, je l'intègre pour la troisième fois et il ne s'enregistre pas. Il mouline sans fin. 

J'ai besoin d'aide rapidement s'il vous plait. 

Merci 

Angèle

**Comment by nicolastrenti** [comment]
Bonjour Angèle,
Peux-tu recharger le back-office dans ton navigateur (ctrl + F5) avant de réessayer la création d'une Actu (en faisant des sauvegardes intermédiaires de ton contenu pour éviter de tout perdre à chaque fois) ?

**Comment by ANGELEROBLOT** [comment]
Merci Nicolas
