### ISSUE TITLE
Version mobile / espace entre le header et le titre de certains articles

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#166]
Est-il possible de réduire l'espace entre le header et le titre ?

https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires/conception-realisation-espaces-sportifs

![screenshot_2018-07-25-15-55-37_resized](https://user-images.githubusercontent.com/40030677/43205272-4744bd5a-9023-11e8-9d3c-3bb7f2a87f5e.png)

**Comment by nicolastrenti** [comment]
J'ai réduit l'espace, ça te semble mieux ?

**Comment by LaetitiaVerdier** [comment]
C'est beaucoup mieux
