### ISSUE TITLE
Problème titre / toutes pages hub du corpo

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#167]
Nicolas,

Habituellement, nous avons une partie en Bold et une partie plus fine, tous les titres prinicpaux sont passées en BOLD intégralement

![image](https://user-images.githubusercontent.com/40030677/43209486-fe7f8b54-902c-11e8-8bde-b3da249a6a3a.png)

**Comment by nicolastrenti** [comment]
Pour mettre des portions de ce type de titre en "allégé", il faut passer en mode "View code" et encadrer les parties allégées par une balise span avec la class h1-light, de cette façon :

![image](https://user-images.githubusercontent.com/1919354/43210098-89f201e8-902e-11e8-9731-444f98880de5.png)

**Comment by LaetitiaVerdier** [comment]
C'était le cas sur le sport pour tous et le sport des territoires, ainsi que la formation mais depuis ce matin ils sont tous en bold

**Comment by nicolastrenti** [comment]
Peux-tu recharger la page en vidant le cache (ctrl + F5), je pense que c'est bon désormais : 
https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires

Merci !

**Comment by LaetitiaVerdier** [comment]
Oui merci beaucoup
