### ISSUE TITLE
Qualité photo / page 404

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#168]
Françoise me dit que la qualité photo de la page est moyenne.

Voici les fichiers.

2 options pour la page 404 :
avec filtre pour accentuer la lisibilité, et sans le filtre s'il existe déjà sur la page du site, format desktop et mobile

![00078170_2544x1435](https://user-images.githubusercontent.com/40030677/43212097-679532be-9033-11e8-9659-bb6feff28437.jpg)
![00078170_2544x1435_sans_filtre](https://user-images.githubusercontent.com/40030677/43212098-688de288-9033-11e8-947a-6cc66af8c3e6.jpg)
![00078170_640x1048](https://user-images.githubusercontent.com/40030677/43212099-6981512a-9033-11e8-915d-fae3950f2922.jpg)
![00078170_640x1048_sans_filtre](https://user-images.githubusercontent.com/40030677/43212101-6aa81462-9033-11e8-80b3-dc404e771328.jpg)

Merci

**Comment by nicolastrenti** [comment]
C'est fait

**Comment by LaetitiaVerdier** [comment]
Merci
