### ISSUE TITLE
Problème affichage menu / L'UCPA c'est quoi + Découvrir le Groupe

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#169]
Dans l'article publié, le menu n'apparaît pas 

https://ucpa-corpo.recette.ampize.me/le-groupe/decouvrir/l-ucpa-c-est-quoi

Toutes les pages de la partie Groupe comme l'utilité sociale ou la gouvernance par exemple arrivent sur une page 404

Peux-tu résoudre le problème ?

Merci

**Comment by nicolastrenti** [comment]
C'est résolu pour le menu.
Pour les 404 également.
Pour info, concernant ces 404, cela se produit quand, dans les vanity URL des pages, il y a un caractère "/" au début de la chaîne. J'avais commencé à saisir les vanity URL avec un "/" au début, mais a priori c'est incompatible avec notre système de routage. Je les supprime donc au fur et à mesure.
Un exemple de vanity URL correct désormais : 

![image](https://user-images.githubusercontent.com/1919354/43255141-4a77c340-90c9-11e8-8cb0-dd8f41c974f6.png)

Par contre, dans tes liens vers des pages, il faut absolument qu'il y ait un "/" au début. Pour la page ci-dessus, le lien à indiquer est donc : 

/le-groupe/domaines-d-activite/formations-aux-metiers-du-sport-et-de-l-animation

**Comment by LaetitiaVerdier** [comment]
Merci.

C'est bien noté
