### ISSUE TITLE
Trame des photos

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#17]
La trame (avec des les pictos à gauche et droite de la photo) doit être équilibrée de chaque côté 
![image](https://user-images.githubusercontent.com/40030677/41108739-912dccd2-6a75-11e8-9cf7-be4673207b9f.png)

**Comment by LucDelmon** [comment]
Ce problème est-il toujours présent ? Je n'arrive pas à le reproduire.

**Comment by LaetitiaVerdier** [comment]
Pas sur les contenus de ce matin.

Je vous préviens si je rencontre de nouveau le problème.

Merci
