### ISSUE TITLE
Problème URL / Ecole des DJ

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#170]
Je ne sais pas pourquoi mais l'URL de l'article est étrange 
https://ucpa-corpo.recette.ampize.me/accueil/formations/offres-de-formation/detailoffres/metier-dj-copy-on-thu-jul-26-2018-10-37-08-gmt-0200-heure-d-ete-d-europe-centrale

**Comment by nicolastrenti** [comment]
J'imagine que le contenu en question a été obtenu en dupliquant un autre contenu, et que l'URL content sur l'offre n'a pas été modifié par la suite.
Je l'ai corrigé, le contenu est maintenant accessible via l'URL : https://ucpa-corpo.recette.ampize.me/accueil/formations/offres-de-formation/detailoffres/metier-dj

**Comment by LaetitiaVerdier** [comment]
Merci
