### ISSUE TITLE
Problème fil d'ariane / page sans contenus

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#171]
Bonjour,

J'ai des pages sans contenus comme :
https://ucpa-corpo.recette.ampize.me/le-groupe/decouvrir

Le contenu est au niveau du dessous comme l'article C'est quoi l'UCPA ?

Le problème c'est que Découvrir apparaît dans le fil d'ariane de la partie Groupe, idem pour Projet.

Que peut-on faire ?

![image](https://user-images.githubusercontent.com/40030677/43256743-0dcb5cfe-90ce-11e8-9586-da6469e97ecf.png)

Merci

**Comment by nicolastrenti** [comment]
Les liens vers "Découvrir" et "Notre projet" ont été désactivés dans le fil d'ariane

**Comment by LaetitiaVerdier** [comment]
Merci

**Comment by LaetitiaVerdier** [comment]
Par contre, j'ai un problème sur le mobile car il n'y a ces deux items à cliquer et pas les niveaux d'informations du dessous.

Peux-tu trouver une solution pour que les sous-parties apparaissent et que les liens vers "Découvrir" et "Notre projet" soient aussi désactivés dans le burger ?

Merci

**Comment by nicolastrenti** [comment]
Non, là ça me paraît vraiment trop complexe à gérer, on rentre dans un besoin ultra-spécifique.
La seule solution que je vois c'est de n'afficher que "Le groupe" sans aucune sous-page (comme en desktop en fait).

**Comment by LaetitiaVerdier** [comment]
Oui cela peut être une bonne option.

**Comment by nicolastrenti** [comment]
C'est fait !

**Comment by LaetitiaVerdier** [comment]
Merci
