### ISSUE TITLE
Lien Boutons de partage / Rejoignez l'UCPA

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#172]
Bonjour,

Voici les liens pour le partage :
Facebook ➜ https://www.facebook.com/UCPA
Instagram ➜ http://instagram.com/ucpa
Twitter ➜ https://twitter.com/groupe_ucpa
Youtube ➜ https://www.youtube.com/user/UCPAOfficiel
LinkedIn ➜ https://www.linkedin.com/company/ucpa/

**Comment by nicolastrenti** [comment]
C'est fait !

**Comment by LaetitiaVerdier** [comment]
merci
