### ISSUE TITLE
Header / menu déroulant Formations

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#176]
Nicolas,

Comme échangé, nous aimerions avoir la possibilité de sélectionner les champs suivants dès le header pour la formation.

Wording du menu déroulant :
**UCPA Formation** => /formations/organisme-formation-UCPA-formation
**Diplômes** => /formations/diplomes
**Financements** => /formations/financements 
**Nos formations** => /formations/offres-de-formation 

Merci

**Comment by nicolastrenti** [comment]
C'est fait !

**Comment by LaetitiaVerdier** [comment]
Par contre, peux-tu changer le wording comme indiqué ci-dessous : 

**Diplômes du sport** sans article devant. 
**Formations** au lieu de offres de formation.

Les espaces blancs semblent plus grands que ceux sous Sport des territoires ou Sport pour tous, peux-tu les réduire ?

Merci encore

**Comment by nicolastrenti** [comment]
C'est fait.
Pour info, le wording du menu est directement calqué sur les titres de pages. Tu peux les modifier dans l'arborescence des pages si tu le souhaites.

**Comment by LaetitiaVerdier** [comment]
Super.

Merci beaucoup

**Comment by LaetitiaVerdier** [comment]
Quand je clique dans le menu déroulant sur Formations je tombe sur une page 404, peux-tu regarder ce qui bloque dans l'URL il faut garder : formations/offres-de-formation
