### ISSUE TITLE
Page liste / dispositifs solidaires

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#177]
Bonjour Nicolas,

Il y a un problème d'affichage de la page liste avec des trous :

https://ucpa-corpo.recette.ampize.me/le-sport-pour-tous/dispositifs-solidaires

![image](https://user-images.githubusercontent.com/40030677/43309433-124f887e-9185-11e8-8849-229f0addd720.png)

**Comment by nicolastrenti** [comment]
C'est corrigé !

**Comment by LaetitiaVerdier** [comment]
merci
