### ISSUE TITLE
Problème vidéo / espace actualités

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#178]
Bonjour, 

Cette vidéo ne s’intègre pas alors qu'elle fonctionne bien sur youtube : 
![image](https://user-images.githubusercontent.com/39916838/43322045-deac5f96-91ad-11e8-9ca0-2d6ae83b0c01.png)
Sur le meme article il y a une autre vidéo qui elle fonctionne correctement : https://ucpa-corpo.recette.ampize.me/accueil/actualites/actualite/sensations-foil-faire-voler-un-catamaran-ou-une-planche-a-voile

Merci pour votre aide, 

Angèle

**Comment by nicolastrenti** [comment]
Bonjour Angèle,

Peux-tu stp me donner l'URL YouTube de la vidéo en question ?

**Comment by ANGELEROBLOT** [comment]
https://www.youtube.com/watch?v=iDrIOmR7y_o

**Comment by nicolastrenti** [comment]
C'est corrigé, je pense qu'il y a eu un petit problème au moment du copier-coller du lien.

**Comment by ANGELEROBLOT** [comment]
Merci Nicolas

**Comment by nicolastrenti** [comment]
Angèle,

J'ai un petit doute : c'est normal selon toi que le texte dépasse de cette façon sur la droite ?

![image](https://user-images.githubusercontent.com/1919354/43324043-6fdef71c-91b3-11e8-80bf-3fe4435832fe.png)

Ou c'est un souci sur ce snippet ?

**Comment by ANGELEROBLOT** [comment]
Effectivement il y a un problème, il est bien aligné à gauche mais décalé à droite. Il doit s'arrêter au niveau du filet noir. 

Merci Nicolas.

Angèle

**Comment by nicolastrenti** [comment]
C'est corrigé sur cette actu et sur le snippet en question.
Si tu vois d'autres contenus où ce snippet a été utilisé, n'hésite pas à me les signaler pour que je les corrige également.

**Comment by ANGELEROBLOT** [comment]
Merci beaucoup Nicolas !

Voila où ça merdouille :+1: 

Pour la partie actualité :
https://ucpa-corpo.recette.ampize.me/accueil/actualites/actualite/terre-glace-feu-arenice-ouvre-public-5-novembre
https://ucpa-corpo.recette.ampize.me/accueil/actualites/actualite/groupeer-check-revolutionne-transport-en-car-mineurs
https://ucpa-corpo.recette.ampize.me/accueil/actualites/actualite/le-village-sportif-ucpa-de-tignes-a-ete-inaugure
https://ucpa-corpo.recette.ampize.me/accueil/actualites/actualite/ecole-dj-ucpa-poitiers-ouvre
https://ucpa-corpo.recette.ampize.me/accueil/actualites/actualite/apprentissage-solution-insertion-sociale-professionnelle-jeunes
https://ucpa-corpo.recette.ampize.me/accueil/actualites/actualite/ucpa-nouveau-gestionnaire-animateur-base-loisirs-cascades-trevoux
https://ucpa-corpo.recette.ampize.me/accueil/actualites/actualite/communaute-urbaine-grand-reims-fait-confiance-ucpa-conception-gestion-futur-complexe-aqualudique
https://ucpa-corpo.recette.ampize.me/accueil/actualites/actualite/aren-ice-1-an-d-ouverture-bilan-et-perspectives
https://ucpa-corpo.recette.ampize.me/accueil/actualites/actualite/l-ucpa-a-ete-choisie-pour-la-gestion-de-la-future-patinoire-d-angers
https://ucpa-corpo.recette.ampize.me/accueil/actualites/actualite/ucpa-ouvre-son-expertise-sportive-aux-familles

+ les 15 articles de la page liste "projets de référence"
+
https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires/ancrage-territorial
https://ucpa-corpo.recette.ampize.me/le-groupe/projet-educatif-et-sportif-ucpa
https://ucpa-corpo.recette.ampize.me/le-groupe/projet-educatif-ucpa-enfants-ados-jeunes
https://ucpa-corpo.recette.ampize.me/le-groupe/decouvrir/l-ucpa-c-est-quoi
https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires/management-espaces-sportifs
https://ucpa-corpo.recette.ampize.me/le-groupe/decouvrir/histoire
https://ucpa-corpo.recette.ampize.me/le-groupe/decouvrir/reperes-economiques-et-juridiques
https://ucpa-corpo.recette.ampize.me/le-groupe/domaines-d-activite
https://ucpa-corpo.recette.ampize.me/formations/organisme-formation-UCPA-formation
https://ucpa-corpo.recette.ampize.me/nous-rejoindre/pourquoi-travailler-a-l-UCPA
https://ucpa-corpo.recette.ampize.me/nous-rejoindre/metiers
https://ucpa-corpo.recette.ampize.me/accueil/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/ateliers-de-remobilisation-par-l-equitation
https://ucpa-corpo.recette.ampize.me/accueil/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/cap-loisirs-sportifs
https://ucpa-corpo.recette.ampize.me/accueil/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/vacances-sportives-handisport
https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires/projets-de-reference/projet-de-reference/ile-de-loisirs-de-vaires-torcy


Bien à toi

Angèle

**Comment by nicolastrenti** [comment]
C'est fait Angèle !

**Comment by ANGELEROBLOT** [comment]
Merci Nicolas, 

Les articles Actualités sont bons. Mais pas les autres.

**Comment by nicolastrenti** [comment]
Je pense que j'avais oublié de re-publier le site, ça doit être bon là.

**Comment by ANGELEROBLOT** [comment]
Effectivement :)

Merci beaucoup Nicolas
