### ISSUE TITLE
Disparition header / article

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#179]
Il manque le header sur cet article

https://ucpa-corpo.recette.ampize.me/le-groupe/projet-educatif-ucpa-enfants-ados-jeunes

**Comment by LaetitiaVerdier** [comment]
le menu a aussi disparu sur cet article 

https://ucpa-corpo.recette.ampize.me/le-groupe/pedagogie-ucpa

**Comment by nicolastrenti** [comment]
C'est corrigé. En copiant-collant les menus sur toutes les pages il y a eu quelques soucis à la sauvegarde, désolé.

**Comment by LaetitiaVerdier** [comment]
d'accord merci
