### ISSUE TITLE
Texte générique / Page Toutes nos implantations

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#180]
Nicolas,

Voici le titre à mettre à la place de "Le sport des territoires" +> Nos implantations

https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires/toutes-nos-implantations

Voici le texte à mettre à la place de "Sortir de chez soi, de son confort, de ses habitudes. Choisir l'activité qui fait vibrer. Partager le même espace et les mêmes sensations. Vivre des bons moments avec le moniteur et progresser. Sentir qu'on participe, avec d'autres, à une aventure. Goûter au bonheur de moments vrais et revenir plus confiant."

+> Dans tous les équipements managés par les équipes UCPA, les usagers peuvent retrouver les quatre leviers majeurs de notre projet éducatif et sportif : l’autonomie des personnes, la création de lien social, le développement du bien-être et la sensibilisation aux comportements responsables.

Le CTA est toujours le même que celui présent : +> renvoyer sur /le-sport-des-territoires/projets-de-reference

Merci

**Comment by nicolastrenti** [comment]
C'est fait !
