### ISSUE TITLE
Point footer du site

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#181]
Nicolas,

Voici, après relecture, ce qui doit changer dans le footer :

**LE GROUPE UCPA**
Découvrez l'UCPA => /le-groupe
Domaines d’activité => /le-groupe/domaines-d-activite
Mission d'accessibilité => /le-sport-pour-tous/mission-d-accessibilite
Dispositifs solidaires => /le-sport-pour-tous/dispositifs-solidaires
Projets de référence => /le-sport-des-territoires/projets-de-reference
_Projet éducatif et sportif => à supprimer_

**NOUS REJOINDRE**
Consultez nos offres d'emploi sur UCPA recrutement
Pourquoi nous rejoindre => /nous-rejoindre/pourquoi-travailler-a-l-UCPA
Métiers => /nous-rejoindre/metiers

**FORMATIONS**
Découvrez nos formations => /formations/offres-de-formation 
UCPA Formation => /formations/organisme-formation-UCPA-formation
_Animation et direction de séjours => à supprimer_
Financements => /formations/financements

**NOS AUTRES SITES**
Découvrez nos séjours => UCPA.com
Rejoignez la communauté UCPA

Merci

**Comment by nicolastrenti** [comment]
Laetitia,

"Consultez nos offres d'emploi sur UCPA recrutement" doit pointer vers quelle page ?
Pareil pour "Rejoignez la communauté UCPA" ?

Merci !

**Comment by LaetitiaVerdier** [comment]
Bonjour,

http://recrutement.ucpa.com/
communaute.ucpa.com

**Comment by nicolastrenti** [comment]
C'est fait !

**Comment by LaetitiaVerdier** [comment]
Merci
