### ISSUE TITLE
Home page / Partie Sport de demain

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#183]
Nicolas,

Je finalise la Home Page et me demande si tu as un moyen de sauvegarder le snippet ci-dessous et de le réactiver plus tard car nous avons mis le Sport de demain de côté pour le moment.

![fireshot capture 31 - accueil - https___ucpa-corpo recette ampize me_](https://user-images.githubusercontent.com/40030677/43835741-45346dee-9b13-11e8-8802-ddbd6a74c7e1.png)

**Comment by nicolastrenti** [comment]
Laetitia,
J'en ai fait un snippet "Le Sport de demain (accueil)", qu'il vous suffira de réintégrer dans la home page une fois que cette section sera prête.
En attendant, j'ai supprimé la portion de code en question de la home.
