### ISSUE TITLE
Home page / Témoignage

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#184]
Je suis sur ton tutoriel et ai compris comment changer le verbatim du header home.

Par contre, peux-tu me dire comment ajouter le lien vers l'article dédié ?

Merci

**Comment by nicolastrenti** [comment]
Dans le "template override" du bloc Menu de la home, il faut que tu modifies le lien à la ligne 298 du code : 

![image](https://user-images.githubusercontent.com/1919354/43889500-a6199394-9bc4-11e8-842f-c5fdfb431477.png)

Il faut que tu remplaces le symbole # juste après 'a href="' par le lien de la page en question, qui doit commencer par un "/"

**Comment by LaetitiaVerdier** [comment]
merci c'est très clair.
