### ISSUE TITLE
Page Hub mobile / Sport pour tous et Sport des territoires

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#185]
Bonjour Nicolas,

Nous avons toujours un espace trop grand au-dessus du picto du A propos sur le mobile des deux pages HUB Sport pour tous et Sport des territoires, peux-tu le réduire ?

Merci

**Comment by nicolastrenti** [comment]
C'est corrigé (l'espace sur le snippet avait été diminué, mais pas sur ces pages dans lesquelles le snippet en question avait déjà été inséré au préalable).

**Comment by LaetitiaVerdier** [comment]
ah mince.

Merci.

Je n'y ai pas pensé sinon je l'aurai refait moi-même.
