### ISSUE TITLE
Picto Dispositifs solidaires

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#188]
Le picto de la main sur le cœur est trop grand sur le desktop et le mobile

https://ucpa-corpo.recette.ampize.me/le-sport-pour-tous/dispositifs-solidaires

Peux-tu le diminuer ?

Merci

**Comment by nicolastrenti** [comment]
J'ai réduit la taille en desktop et mobile, ça te semble mieux ?

**Comment by LaetitiaVerdier** [comment]
oui merci
