### ISSUE TITLE
Page liste actualités / desktop et mobile

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#189]
Dans les listes thématiques type Séjours et tendances ou Formation, il manque le filet noir de séparation qui vient entre le chapeau et le premier titre cf.visuel

![image](https://user-images.githubusercontent.com/40030677/43842452-b4551130-9b25-11e8-92ac-88209c1f8409.png)

**Comment by nicolastrenti** [comment]
Filet ajouté !

**Comment by LaetitiaVerdier** [comment]
merci
