### ISSUE TITLE
Articles liés projets : photo décalée

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#19]
Dans les articles liés projets, la photo est décalé sur la gauche 
![image](https://user-images.githubusercontent.com/40030677/41108831-d1e638ea-6a75-11e8-88a8-99a71de6315f.png)

**Comment by LucDelmon** [comment]
Bonjour,

Ou avez-vous ce problème ?

Je n'arrive pas à le reproduire

**Comment by LaetitiaVerdier** [comment]
L'article n'existe plus.

Il a été supprimé dans internal content quand des modifications ont été apportées. 

Il s'agissait du snippet "Loisirs articles liésx3", je viens de refaire un test et il n'y a plus de problème.

![image](https://user-images.githubusercontent.com/40030677/41459274-64cf42c8-7089-11e8-94ac-996dd545fcab.png)
