### ISSUE TITLE
Problème menu déroulant noir / Formations

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#190]
Il y a un filet blanc qui apparaît au survol de chaque item, peux-tu le supprimer ?

![sans titre](https://user-images.githubusercontent.com/40030677/43842620-0da566c2-9b26-11e8-9c30-024a8a234a82.png)

Merci

**Comment by nicolastrenti** [comment]
Corrigé
