### ISSUE TITLE
Temps d'affichage de la typo Din ot

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#191]
Bonjour Nicolas,

Quand je circule sur le site d'un article à l'autre, je trouve que le temps de latence avant que la typo UCPA (Din OT) ne s'affiche demeure longue. On a l'impression de voir du Times New Roman à l'écran pendant quelques secondes.

Est-ce quelque chose sur lequel tu peux intervenir ?

Merci

**Comment by nicolastrenti** [comment]
Je pense que c'est lié au fait que nous sommes sur l'environnement de recette. Les ressources devraient se charger plus rapidement une fois que nous aurons transféré le site sur l'environnement final.

**Comment by LaetitiaVerdier** [comment]
D'accord.

Merci
