### ISSUE TITLE
Lien articles liés / projets de référence

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#193]
Nicolas,

Tous les liens fonctionnaient avant mon départ en congés et en prenant quelques articles comme Pailleron je m'aperçois que les liens des articles liés ne fonctionnent plus

Crois-tu que quelqu'un y a touché ou est-ce un problème technique ?

Merci

**Comment by nicolastrenti** [comment]
Laetitia,

Pour les liens en questions, je constate que les URLs indiquées ne sont pas bonnes : elles ne commencent pas par un "/". 
Il ne peut pas s'agir d'un problème technique, en l'état le lien n'est pas valable.
Soit les liens en question ne fonctionnaient pas à l'époque, soit ils ont été modifiés (mais je n'ai pas de moyen de vérifier).

**Comment by LaetitiaVerdier** [comment]
Bon de toute façon ça ne change rien au fait que cela ne fonctionne pas...

Je vais les refaire.

Merci

**Comment by LaetitiaVerdier** [comment]
Juste pour te prévenir que c'est fait.

**Comment by nicolastrenti** [comment]
Ok, parfait. Tu as dû repasser sur beaucoup de contenus ?

**Comment by LaetitiaVerdier** [comment]
Tous les liens des projets de référence avaient changé, il y avait un HTTP:// devant chaque lien qui était bon. 

Soit 7 liens x 15 articles projets. 

Tout est bon sur le sport pour tous.

**Comment by LaetitiaVerdier** [comment]
J'intègre mon dernier article et j'ai tout fini sauf l'accessibilité en footer.

Je ne sais pas quoi mettre et ne peux pas m'inspirer d'UCPA.com
