### ISSUE TITLE
TITRE / Article Arpe

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#194]
Nicolas,

En contribution, le titre de article apparaît correctement mais en preview il est coupé :
https://ucpa-corpo.recette.ampize.me/accueil/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/ateliers-de-remobilisation-par-l-equitation

**Comment by nicolastrenti** [comment]
Oui, effectivement, la preview n'est pas forcément fidèle au rendu final sur des cas particuliers de titres longs. J'ai forcé le retour à la ligne pour cet article.

**Comment by LaetitiaVerdier** [comment]
merci

**Comment by LaetitiaVerdier** [comment]
Toutes les photos de cet article apparaissent maintenant déformées

**Comment by nicolastrenti** [comment]
Je ne saurais pas du tout te dire à quoi ça peut être dû, mais c'est rentré dans l'ordre en repassant sur chaque image, en cliquant sur "Change size" puis en validant sans indiquer de dimension.

**Comment by LaetitiaVerdier** [comment]
;-) j'ai fini le dernier article. Je change le témoignage sur la Home Page et ne touche plus à rien ;-)

**Comment by nicolastrenti** [comment]
Demain, on basculera les données sur l'environnement qui nous servira pour la prod (si tu me confirmes qu'il n'y aura plus de modif demain sur les contenus).

Nous serons ainsi prêts pour la mise en prod de lundi.

**Comment by LaetitiaVerdier** [comment]
je te confirme. J'ai envoyé un mail à tous les contributeurs pour leur dire ne plus toucher à rien. 
De mon côté, je fais ma dernière modification dans les 30 minutes sur la Home...

Merci pour tout Nicolas.
