### ISSUE TITLE
Bloc contact dans le snippet actualité chapeau

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#195]
Quand je clique sur le mail je ne peux pas supprimer le brouillon si je change d'avis, je suis obligée d'envoyer un mail pour pouvoir sortir de la fenêtre.

Peux-tu dans ce snippet remplacer mon mail et celui d'Angèle par l'adresse générique presse@ucpa.asso.fr ?

Merci

**Comment by LaetitiaVerdier** [comment]
et aussi sur la page liste actualités.

**Comment by LaetitiaVerdier** [comment]
Je crois avoir trouvé pour le snippet où changer le mail par contre pas pour la page liste actualités

**Comment by nicolastrenti** [comment]
C'est fait pour les listes d'actu.

Pour info, c'est dans le bloc Chapeau, il faut cliquer sur l'icône HTML puis modifier les lignes suivantes : 

![image](https://user-images.githubusercontent.com/1919354/43908466-56911c46-9bf8-11e8-84e5-9dbe97f26753.png)

**Comment by LaetitiaVerdier** [comment]
merci
