### ISSUE TITLE
Dernier ticket avant MEP

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#196]
J'ai changé le verbatim de la home et mis le lien vers lequel je souhaite renvoyer mais les trois petits points ont disparu de la home et le lien de renvoi aussi.

Peux-tu regarder ?
Merci encore

**Comment by nicolastrenti** [comment]
C'est corrigé.

Sur la home, tu avais mis le lien de ton article à la place de la source de l'image, alors qu'il fallait le mettre dans la balise "a" : 

![image](https://user-images.githubusercontent.com/1919354/43944285-afba0838-9c7e-11e8-911b-b950515edb6e.png)

C'est à la place du # encadré en bleu qu'il faut mettre le lien de l'article.

**Comment by LaetitiaVerdier** [comment]
Je suis désolée, j'étais fatiguée et ça mène à faire des erreurs.

Merci d'avoir fait la modification.

**Comment by nicolastrenti** [comment]
Pas de souci, c'est des choses qui arrivent :)
