### ISSUE TITLE
Informations SEO

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#197]
Bonjour Laetitia,

Afin d'optimiser le référencement, il est souhaitable de préciser certaines infos dans les paramètres du site, notamment : 
- un titre (j'imagine "UCPA Association")
- une description (taille recommandée : entre 50 et 250 caractère. Par exemple, sur UCPA Vacances, la description actuelle est : "Partez en vacances avec l'UCPA et profitez de l'ensemble des séjours sportifs et activités en France et à 'étranger pour tous les âges.")
- des keywords (facultatifs, car de moins en moins utilisés par les moteurs de recherche)

Peux-tu me fournir ces infos ? Je les ajouterai sur le site. Merci !

**Comment by LaetitiaVerdier** [comment]
Bonjour Nicolas,

Voici les éléments demandés. 

Titre : UCPA Association

Description : Éducateur sportif de métier, le groupe associatif UCPA, reconnu d’utilité sociale, oeuvre depuis plus de 50 ans en faveur d’un sport ouvert à tous et vecteur de vivre-ensemble. Découvrez sa mission, ses activités, ses métiers, ses actualités et ses projets. 

Merci 

Laëtitia.
