### ISSUE TITLE
 Page liste contacts

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#198]
Bonjour,

Les adresses mail de la page contact ne sont pas actives.
https://www.ucpa.asso.fr/accueil/contact

Idem pour le bloc contact de la page liste actualités 
https://www.ucpa.asso.fr/actualites

Pouvez-vous débloquer cela ?

Merci

**Comment by LucDelmon** [comment]
Bonjour, qu'entendez-vous par non-actives ?

Sur les pages que vous mentionnez tout fonctionne pour moi. Quand je clique mon client mail s'allume avec l'adresse mail en destinataire

**Comment by LaetitiaVerdier** [comment]
Bonjour,

Sur le desktop, ça ne fonctionne pas chez moi. 

J'ai fait une demande à la DSI pour comprendre pourquoi.

Sur la version mobile, les images des contacts ne s'affichent pas.

**Comment by LucDelmon** [comment]
Il faut avoir une boite mail configuré pour que cela fonctionne. Ca dépend des personnes et des plateformes.

Je regardes pour les images.

**Comment by LucDelmon** [comment]
Il n'y a tout simplement plus d'images associés aux contacts dans les contenus internes.

Le lien à peut être sauté lors de la mise en prod.

Il faudrait les réindiquer

**Comment by LaetitiaVerdier** [comment]
En attendant que je refasse le nécessaire, pouvez-vous mettre ce qui était prévu en cas d'absence de photo sur la maquette ?

![image](https://user-images.githubusercontent.com/40030677/44266207-f4d8ae00-a229-11e8-886a-71b78d0cbc8c.png)

**Comment by LaetitiaVerdier** [comment]
L'enveloppe mail n'apparaît nulle part à côté de e-mail ni dans les blocs contacts ni sur la page liste et l'adresse mail de la Direction territoriale a disparu : ddt@ucpa.asso.fr

**Comment by LucDelmon** [comment]
C'est déjà le cas,

En fait cette image était également indisponible pendant le problème des fonts. Elle n'est donc pas encore dans le cache google. Il faut attendre que le cache se mette a jour en ajoutant "no-cache=true" a la fin de l'URL vous pouvez voir la page tel qu'elle sera quand google aura rafraichi son cache.

https://www.ucpa.asso.fr/contact?no-cache=true

**Comment by LucDelmon** [comment]
pareil pour l'envelope mail. Toutes ces images ne sont pas encore chargé dans le cache google. On ne peut qu'attendre .

**Comment by LaetitiaVerdier** [comment]
Parfait. 

Merci Luc.
