### ISSUE TITLE
Page Nos implantations

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#199]
Bonjour,

La page Nos implantations affiche une erreur 404 au lieu de la cartographie :

https://www.ucpa.asso.fr/le-sport-des-territoires/toutes-nos-implantations

De plus, le CTA VOIR NOS PROJETS DE RÉFÉRENCE de la page ne renvoie pas sur la page liste projets 

Merci de votre retour.

Laëtitia.

**Comment by LucDelmon** [comment]
Bonjour, 

le lien est corrigé.

Pour la 404 c'est lié problème qui nous empêche de charger les fonts. On investigue dessus.

**Comment by LucDelmon** [comment]
C'est bon

**Comment by LaetitiaVerdier** [comment]
Merci Luc,

Par contre le CTA VOIR NOS PROJETS DE RÉFÉRENCE de la page ne renvoie sur rien

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,
As-tu toujours le problème pour ce CTA ? Ça a l'air bon de mon côté.
Merci !

**Comment by LaetitiaVerdier** [comment]
Bonjour Nicolas,

Oui cela fonctionne bien.
