### ISSUE TITLE
Problème de visualisation

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#2]
Bonjour,

Nous n'arrivons pas à accéder à ce site : https://ucpa-corpo.recette.ampize.me

![image](https://user-images.githubusercontent.com/40030677/41103689-0a99395a-6a6a-11e8-8b48-86370b7d9d52.png)

**Comment by LucDelmon** [comment]
Bonjour,

nous avons corrigé un problème de droit qui vous empêchez de publier le site.

Le site est maintenant visible sur https://ucpa-corpo.recette.ampize.me.
