### ISSUE TITLE
Facebook / bouton de partage

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#201]
Dans les boutons de partage, j'ai un message d'erreur pour Facebook : 
Erreur d’accès à l’application

Pouvez-vous regarder ?

Merci

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,

Tu as raison, j'ai oublié de vous prévenir sur ce point.
Pour le partage sur Facebook, il est nécessaire de créer une app Facebook : https://developers.facebook.com/apps/
(mais vous en avez sans doute déjà une pour l'UCPA)

Une fois l'app créée, il faut me communiquer son ID d'app, qui est un paramètre obligatoire pour le partage sur Facebook pour que je le renseigne dans AMPize.

Merci !
Nicolas

**Comment by LaetitiaVerdier** [comment]
J'ai fait la demande et te tiens informé.

Merci

**Comment by LaetitiaVerdier** [comment]
Voilà, tu peux utiliser cet ID :  234220593909143

Bien à toi

**Comment by nicolastrenti** [comment]
Laetitia,
J'ai essayé d'utiliser l'identifiant en question (par exemple sur cette page : https://www.ucpa.asso.fr/accueil/actualites/actualite/l-ucpa-est-choisie-pour-gerer-le-stade-nautique-georges-vallerey), mais Facebook indique que cette application n'est pas configurée : 

Application non configurée: Cette application est actuellement en cours de développement, et vous ne pouvez pas y accéder.

Peux-tu vérifier auprès de tes équipes si l'application a bien été publiée et activée ?

Merci !

**Comment by LaetitiaVerdier** [comment]
Je leur ai demandé.

Bien à toi,

**Comment by LaetitiaVerdier** [comment]
Bonjour,

Voici un autre ID déjà existant  : 358560267853850

Bonne journée,

**Comment by LucDelmon** [comment]
Il y a la même erreur sur l'id, Facebook indique que l'application n'est pas configuré

**Comment by LaetitiaVerdier** [comment]
Le service a configuré et activé une nouvelle app :   
237274573554169

Belle journée,

**Comment by LaetitiaVerdier** [comment]
Cela fonctionne-t-il ?

Merci

**Comment by LucDelmon** [comment]
Non,

j'ai toujours le même message d'erreur.

Application non configurée: Cette application est actuellement en cours de développement, et vous ne pouvez pas y accéder.

le lien est bon l'application ne semblent pas être dans le bon état.

**Comment by LaetitiaVerdier** [comment]
Faut-il configurer une API dessus ? L'app est bien activée du côté du community ?

Vous faut-il la clé ?

**Comment by LucDelmon** [comment]
Il semblerait que l'application n'est pas activé. 
Il y a normalement un switch a passer à On dans la configuration de l'application facebook pour l'activer.

**Comment by LaetitiaVerdier** [comment]
Ils me disent que c'est déjà sur On.

Avez-vous une procédure à respecter pour les aider ?

Merci

**Comment by LucDelmon** [comment]
En fait l'identifiant fonctionne. J'avais encore l'ancienne clé a cause du cache et elle est très similaire donc je n'ai pas vu la différence. Le dernier ID "237274573554169" fonctionne bien.

Par contre ce n'est pas rétro actif. Je vais mettre à jour les snippets pour inclure le bon ID dans les prochains articles mais si vous voulez aussi avoir le partage sur les anciens articles il faudra les mettre à jour.

**Comment by LaetitiaVerdier** [comment]
D'accord
