### ISSUE TITLE
Lien hypertexte 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#202]
Nicolas,

Est-ce que je procède de la même façon maintenant que le site est en ligne pour mettre un lien hypertexte - /accueil/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/cap-au-vert - ou est-ce que je mets le lien complet comme suit : https://www.ucpa.asso.fr/accueil/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/cap-au-vert

Merci

**Comment by nicolastrenti** [comment]
Les deux marcheront, mais dans l'absolu c'est préférable de continuer à indiquer /accueil/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/cap-au-vert, car si un jour le site change de nom de domaine (c'est peu probable, je te l'accorde...), on n'aura pas à repasser sur tous les liens.

**Comment by LaetitiaVerdier** [comment]
D'accord, je garde ce réflexe alors
