### ISSUE TITLE
Chevauchement mobile / guillemets snippet articles liés

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#203]
Sur la Home, j'ai remarqué un chevauchement des guillemets pour les articles liés

![screenshot_2018-08-21-12-27-38](https://user-images.githubusercontent.com/40030677/44396733-2a3d0e80-a53e-11e8-9d38-0495b35ae26a.png)

**Comment by nicolastrenti** [comment]
J'ai fait au mieux, mais en mobile cela passe le titre sur deux lignes pour éviter le chevauchement.

https://www.ucpa.asso.fr/?no-cache=true

**Comment by LaetitiaVerdier** [comment]
En mobile je ne le vois pas sur deux lignes mais sur une

Peux-tu a minima aligner le bas du chevron sur le bas de la majuscule de Découvrir

**Comment by LucDelmon** [comment]
le texte devrait être sur 2 lignes désormais et le chevron est aligné

**Comment by LaetitiaVerdier** [comment]
Oui c'est bon.

Merci
