### ISSUE TITLE
Home page / logo UCPA animation flou

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#204]
Le logo UCPA de l'animation de la Home page est complètement flou.

**Comment by nicolastrenti** [comment]
Laetitia,
C'est parce que nous avons utilisé le logo qui est dans le menu et dont les dimensions sont trop petites.
Peux-tu m'envoyer le logo blanc sur fond transparent dans une taille plus conséquente stp ? Je ne le trouve pas dans les fichiers fournis avec la créa.
Merci.

**Comment by LaetitiaVerdier** [comment]
Le voici.


![ucpa-logo-blanc](https://user-images.githubusercontent.com/40030677/44467719-dc9ad180-a623-11e8-9e70-b3bfdbdba324.png)

**Comment by nicolastrenti** [comment]
Merci Laetitia !
Normalement, c'est beaucoup mieux : https://www.ucpa.asso.fr/?no-cache=true

**Comment by LaetitiaVerdier** [comment]
Oui effectivement merci
