### ISSUE TITLE
Menu déroulant / Page contacts

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#205]
Il manque l'option "Tous les contacts" en début de menu déroulant de la page contacts desktop et mobile.

De même, sur la version mobile, le portrait, le nom de l'interlocuteur et le filet rouge qui le souligne sont trop tassés.

**Comment by nicolastrenti** [comment]
C'est fait : https://www.ucpa.asso.fr/accueil/contact?no-cache=true

**Comment by LaetitiaVerdier** [comment]
Merci beaucoup.
