### ISSUE TITLE
Problème picto / desktop et mobile

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#206]
A propos, il manque le picto sur le desktop et sur le mobile il est disproportionné.
https://www.ucpa.asso.fr/le-groupe/decouvrir/l-ucpa-c-est-quoi

Idem sur les A propos des Repères économiques
https://www.ucpa.asso.fr/le-groupe/decouvrir/reperes-economiques-et-juridiques

Idem sur les A propos la Gouvernance
https://www.ucpa.asso.fr/le-groupe/decouvrir/gouvernance

Idem dans le A propos UCPA Formation 
https://www.ucpa.asso.fr/formations/organisme-formation-UCPA-formation

**Comment by nicolastrenti** [comment]
C'est bon désormais (l'attribut de style "fixed size" avait sauté sur ces snippets) : 

https://www.ucpa.asso.fr/le-groupe/decouvrir/reperes-economiques-et-juridiques?no-cache=true
https://www.ucpa.asso.fr/le-groupe/decouvrir/l-ucpa-c-est-quoi?no-cache=true
https://www.ucpa.asso.fr/le-groupe/decouvrir/gouvernance?no-cache=true
https://www.ucpa.asso.fr/formations/organisme-formation-UCPA-formation?no-cache=true

**Comment by LaetitiaVerdier** [comment]
D'accord je vérifierai la prochaine fois.

Merci
