### ISSUE TITLE
Sous-menu / Nous rejoindre 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#207]
Sur le desktop, on a pas de sous-menu mais on en a un sur le mobile.

Peut-on en ajouter un sur le desktop et mettre de la même façon que pour la partie Formations : 
Pourquoi travailler à l'UCPA
Métiers

Merci

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,

Ça y est, c'est en place sur toutes les pages du site (moyennant expiration du cache) : https://www.ucpa.asso.fr/?no-cache=true

**Comment by LaetitiaVerdier** [comment]
Merci Nicolas.
