### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#208]
Footer - le lien financements ne fonctionne pas :
https://www.ucpa.asso.fr/formations/financements

Est-il possible d'ajouter un espace blanc par défaut avant le footer pour le mobile et le desktop ?

Dans certains cas, le snippet qui précède colle trop au footer. Nous aimerions éviter ce cas de figure.

Merci

**Comment by nicolastrenti** [comment]
Une marge a été ajoutée avant le footer : https://www.ucpa.asso.fr/formations/financements?no-cache=true

Par contre chez moi la page https://www.ucpa.asso.fr/formations/financements est bien accessible.

**Comment by LaetitiaVerdier** [comment]
Merci 

Je te confirme que cela fonctionne maintenant.
