### ISSUE TITLE
Problème d'espace persistant

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#209]
On a toujours un problème d'espace entre le menu et le premier titre sur le mobile pour l'article suivant (il y a beaucoup trop de blanc) :
https://www.ucpa.asso.fr/le-sport-des-territoires/management-espaces-sportifs

**Comment by nicolastrenti** [comment]
Normalement, c'est mieux désormais : https://www.ucpa.asso.fr/le-sport-des-territoires/management-espaces-sportifs?no-cache=true

**Comment by LaetitiaVerdier** [comment]
Merci C'est beaucoup mieux par contre sur mobile, le titre n'est pas très équilibré.
Peux-tu mettre comme ce qui suit :
Animer et manager
des espaces sportifs 
pour un sport au service de tous

Bien à toi

**Comment by nicolastrenti** [comment]
C'est fait : https://www.ucpa.asso.fr/le-sport-des-territoires/management-espaces-sportifs?no-cache=true

**Comment by LaetitiaVerdier** [comment]
Merci
