### ISSUE TITLE
Bug chapeau solidarité

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#21]
Il y a un bug dans le titre

**Comment by LucDelmon** [comment]
Bonjour,
Vous faites mention du titre qui se retrouve cassé sur plusieurs lignes ? C'est une conséquence de la police et de la position des éléments.

Pour qu'il se réaligne il va falloir baisser la police ou décaler des éléments. Que souhaitez vous faire ?

**Comment by LaetitiaVerdier** [comment]
Je pense que ça n'est pas nécessaire, j'ai fait la simulation hier et lorsque l'article est en ligne, le T apparaît à la bonne place
