### ISSUE TITLE
Bug visuel header / Marseille Pastré

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#210]
Nicolas,

J'ai un problème d'affichage de deux visuels header en mobile et en desktop 
https://www.ucpa.asso.fr/le-sport-des-territoires/projets-de-reference/projet-de-reference/centre-equestre-marseille-pastre

J'ai rechargé les fichiers avec la bonne chromie mais la modification ne s'opère pas chez moi même après avoir vidé le cache comme si le back office gardait en mémoire les fichiers cmjn qui étaient chargés dans la médiathèque.

Voici les bons fichiers avec les bons coloris. 
![loisirs-centre-equestre-marseille-pastre-ucpa jpg](https://user-images.githubusercontent.com/40030677/44462844-254b8e00-a616-11e8-8214-79a69bc52b52.jpg)
![loisirs-centre-equestre-marseille-pastre-ucpa-m jpg](https://user-images.githubusercontent.com/40030677/44462845-254b8e00-a616-11e8-9fa2-ab08c454f802.jpg)

Merci pour ton aide

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,

Il y a un cache, côté Google et côté AMPize, pour les pages AMP.
Les images seront bien mises à jour dans quelques minutes / heures.
Pour voir la page sans cache, il faut rajouter ?no-cache=true à la fin de l'URL. 
Ici : https://www.ucpa.asso.fr/le-sport-des-territoires/projets-de-reference/projet-de-reference/centre-equestre-marseille-pastre?no-cache=true

**Comment by LaetitiaVerdier** [comment]
Merci Nicolas
