### ISSUE TITLE
Sous-menu header / Le Groupe

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#211]
Nicolas,

Finalement, nous allons ajouter un sous-menu dans le header pour le Groupe également avec les titres et liens suivants à la fois sur le desktop et le mobile : 

- L'UCPA, C'EST QUOI => /le-groupe/decouvrir/l-ucpa-c-est-quoi
- UTILITÉ SOCIALE DE L’UCPA => /le-groupe/decouvrir/projet-associatif-modele-d-utilite-sociale
- MISSION ET VALEURS => /le-groupe/mission-valeurs-ucpa
- DOMAINES D'ACTIVITÉ => /le-groupe/domaines-d-activite

Merci 

Laëtitia

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,

Pour les demandes relatives au menu (#207 et #211), il s'agit d'évolutions qu'il faut que je fasse valider car elles représentent un charge de travail non négligeables pour nous (nécessité de repasser sur toutes les pages du site : au moins 2h de travail).

**Comment by LaetitiaVerdier** [comment]
Je comprends.

Je viens d'avoir la demande de la Direction.

Merci

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,
J'ai travaillé sur un rendu du menu pour résoudre les tickets #207 (section Nous rejoindre) et #211 (section Le Groupe).
Tu peux voir le résultat ici : https://www.ucpa.asso.fr/le-sport-des-territoires?no-cache=true
Avant que je reporte ces modifications sur l'intégralité des pages, ce qui prend pas mal de temps, j'aimerais que tu me valides que ça te convient.

Merci !

**Comment by LaetitiaVerdier** [comment]
Bonjour Nicolas,

Cela me va très bien.

Seule question, le texte Pourquoi travailler à l'UCPA ? n'apparaît pas en entier. Il est coupé sur la droite sur mon ordi.

Peux-tu le résoudre ou faut-il raccourcir le texte ?

Merci

**Comment by nicolastrenti** [comment]
Oui, tu as raison, sur des petits écrans ça pose problème, désolé je n'avais pas testé cette configuration.
Je fais quelques essais pour voir si j'arrive résoudre ça sans avoir à tronquer le texte.

**Comment by nicolastrenti** [comment]
Ça me semble mieux désormais : https://www.ucpa.asso.fr/le-sport-des-territoires?no-cache=true

**Comment by LaetitiaVerdier** [comment]
Oui en effet, par contre, peux-tu coller le bloc au bord du site comme c'est déjà le cas pour le Sport pour tous et me confirmer qu'il fait bien la même taille en largeur que le bloc Groupe et Formations ?

Merci

**Comment by nicolastrenti** [comment]
Pour chacun de ces blocs, la largeur est calquée sur le libellé le plus long, ils ont donc tous une largeur différente.
En testant sur mon écran d'ordinateur portable (résolution 1366 x 768), le bloc déroulant pour Nous rejoindre est déjà collé à la droite de l'écran en l'état : 
![image](https://user-images.githubusercontent.com/1919354/44723679-f9764f80-aad0-11e8-8d9b-243237c8d615.png)

**Comment by LaetitiaVerdier** [comment]
Voici ce qui s'affiche sur mon poste : 

![affichage](https://user-images.githubusercontent.com/40030677/44724199-545c7680-aad2-11e8-99f3-5c54ea7456af.png)

**Comment by nicolastrenti** [comment]
Le problème c'est que ta résolution d'écran est légèrement supérieure à la mienne.
Si je déplace le cadre plus à droite, il sera coupé sur un écran comme le mien par exemple.

**Comment by LaetitiaVerdier** [comment]
D'accord, alors on part comme cela.

Merci Nicolas

**Comment by nicolastrenti** [comment]
Parfait, je repasse sur l'intégralité des pages demain matin.

**Comment by LaetitiaVerdier** [comment]
Merci Nicolas

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,

Ça y est, c'est en place sur toutes les pages du site (moyennant expiration du cache) : https://www.ucpa.asso.fr/?no-cache=true
