### ISSUE TITLE
Titre Toutes nos implantations

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#212]
Dans le menu du Sport des territoires, peux-tu remplacer le libellé  "Toutes nos implantations" par "Implantations" en desktop et mobile.

Merci.

**Comment by nicolastrenti** [comment]
C'est fait, moyennant le temps de mise à jour du cache.

**Comment by LaetitiaVerdier** [comment]
Merci
