### ISSUE TITLE
URGENT / Bloc contact Page UCPA Formation

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#213]
J'ai rajouté un contact en urgence suite à un grand nombre d'appel 

L'enveloppe est énorme. Je n'arrive pas à la diminuer même avec Fixe size
https://www.ucpa.asso.fr/formations/organisme-formation-UCPA-formation

**Comment by nicolastrenti** [comment]
Laetitia,
As-tu pu résoudre le problème ? Chez moi le rendu est correct.
![image](https://user-images.githubusercontent.com/1919354/44535793-273b4d00-a6fb-11e8-83e1-1e3ecec012f0.png)

**Comment by LaetitiaVerdier** [comment]
c'est toujours déformé chez moi...

**Comment by nicolastrenti** [comment]
Même sans le cache ? 
https://www.ucpa.asso.fr/formations/organisme-formation-UCPA-formation?no-cache=true

**Comment by LaetitiaVerdier** [comment]
sans le cache, je ne le voyais pas correctement tout à l'heure et là c'est bon mais entre temps j'ai sélectionné Fixe size
