### ISSUE TITLE
Demande de conseils / usage lien sur site 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#214]
Nicolas,

Peux-tu me conseiller sur les liens hypertexte et CTA, est-il préférable de mettre "Ouvrir dans un nouvel onglet" ou laisser dans le même onglet ?

Merci pour ton conseil.

**Comment by nicolastrenti** [comment]
En général, l'ouverture dans un nouvel onglet est conseillée quand le lien permet d'accéder à des ressources externes complémentaires, de façon à laisser l'opportunité à l'utilisateur de retrouver la page de départ sans avoir à faire un "back" sur le navigateur. 

J'aurais tendance à les conseiller pour : 
- des liens vers des sites externes (autres que des pages du site Corpo, donc)
- l'ouverture de ressources internes comme les PDF (c'est toujours mieux que le PDF soit ouvert dans un nouvel onglet plutôt qu'il prenne la place de la page actuelle)

Dans tous les cas, je déconseille d'en abuser, sinon l'internaute va se retrouver rapidement avec de nombreux onglets ouverts alors qu'il ne l'a pas demandé (sur un lien, on peut toujours faire "ouvrir dans un nouvel onglet" de manière volontaire).

**Comment by LaetitiaVerdier** [comment]
Merci Nicolas.

Je vais prendre ce conseil et ajouter les liens mails à ta liste.
