### ISSUE TITLE
Portrait témoins N&B / problème d'affichage

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#215]
Bonjour,

J'ai un problème avec les témoins de chaque formation :
https://www.ucpa.asso.fr/formations/offres-de-formation

Les portraits ont été mis en noir et blanc, au lieu de la couleur la semaine passée.

Sauf que mes collègues les voient en couleur et moi avec le cache en noir et blanc.

Pouvez-vous regarder ce qui bloque  ?

Merci

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,
Je viens de regarder de mon côté, je les vois bien en n&b.
Peut-être un souci de cache navigateur chez tes collègues ?

**Comment by LaetitiaVerdier** [comment]
Bonjour Nicolas,

Moi aussi. Ils sont très bien.

Je leur ai dit de vérifier leur cache.

Ils me disent que cela ne fonctionne pas...
