### ISSUE TITLE
Finalisation des tickets

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#216]
Nicolas,

Peux-tu me dire quand les différents tickets restants seront résolus ?

Je dois préparer la communication globale sur la sortie du site.

Bien à toi,

Laëtitia.

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,
Désolé, j'ai eu pas mal de sujets à gérer ces derniers jours. Je fais en sorte de boucler les issues ouvertes d'ici mercredi, si c'est bon pour toi.

**Comment by LaetitiaVerdier** [comment]
Bonjour Nicolas,
C'est parfait.
Ne t'inquiète pas, j'ai jusqu'à la fin de cette semaine.
Bien à toi,
Laëtitia.

**Comment by nicolastrenti** [comment]
A priori, le seul point d'importance à résoudre reste la question du partage Facebook. As-tu pu avoir un retour par rapport à l'application Facebook UCPA ?

**Comment by LaetitiaVerdier** [comment]
Sur ce point, notre community manager en chef est en congés et son équipe n'a pas su le faire. Je m'en occupe lundi sans faute avec ton équipe.
