### ISSUE TITLE
Vitesse de chargement des pages du site

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#218]
Nicolas,

La vitesse de chargement du site est toujours très lente sur toutes les pages, en particulier la page 404.

Peux-tu voir si cela peut être amélioré ?

Merci

**Comment by Alexandru-Dobre** [comment]
Actuellement toutes les pages chargent en moins de 200ms.
Testez-vous avec du ?no-cache=true dans l'url ? Si oui telle est la cause. 
La première génération d'une page peut prendre un peu de temps mais une fois que c'est fait ce sera toujours sous les 200 ms pour vous et tout autre visiteur sur le site.

**Comment by LaetitiaVerdier** [comment]
Chez nous, la page 404 s'affiche beaucoup plus lentement.

Personnellement, j'utilise ?no-cache=true dans l'url mais pas mes collaborateurs qui m'ont montrée sur leur ordinateur des pages qui mettent du temps à charger, notamment au web chez nous. Ils sont trois à m'en avoir fait part.

**Comment by Alexandru-Dobre** [comment]
Pour la 404 c'est pas étonnant: elle contourne le cache par nature (vu que ce qui n'existe pas ne peut etre mis en cache). Le ?no-cache=true a le meme effet, est pratique pour tester mais les perfs sont faible vu le contournement du cache. Le cache (CDN Google) est la principale source de données pour le rendu d'un site AMPize : l'infra ne sert qu'à rendre des pages pour ce cache.
Il est probable que vos collaborateurs ait vu un premier rendu d'une page d'ou la lenteur. 
En général, si un rendu de page est lent la première fois il suffit de recharger la page une ou deux fois (temps de propagation dans le CDN Google) ou et elle ne sera plus jamais lente pour quel user que ce soit. La 404 est par nature une exception. 
Si cela ne marche pas sur une page (après 3 reloads et 30s de patience) autre que la 404 et sans ?no-cache=true n'hésitez pas à nous prevenir et on investiguera l'origine.

**Comment by LaetitiaVerdier** [comment]
C'est noté. 

Merci
