### ISSUE TITLE
URGENT / URL du site asso

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#219]
Quand je saisis ucpa.asso.fr dans l'URL, cela ne fonctionne pas si les WWW ne sont pas saisis.

https://ucpa.asso.fr

Peux-tu y remédier ?

Merci

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,
J'avais abordé ce sujet avec Hugues précédemment, la redirection est à faire au niveau du nom de domaine (et non côté AMPize). Nous n'avons pas la main sur le nom de domaine, c'est Hugues ou son équipe qui peuvent agir sur ce point.

**Comment by LaetitiaVerdier** [comment]
Merci Nicolas.

Je ne savais pas, je lui demande.

Bien à toi,
