### ISSUE TITLE
Contacts presse

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#22]
La flèche doit être à gauche de contacts presse et pas au dessus

![contacts presse](https://user-images.githubusercontent.com/39916838/41161981-c77b7266-6b34-11e8-81c9-452ed82b41b6.JPG)

**Comment by nicolastrenti** [comment]
Angèle,
Quel est le module concerné ?

**Comment by ANGELEROBLOT** [comment]
Pardon, chapeau article

**Comment by nicolastrenti** [comment]
Angèle,
Je ne suis pas sûr de bien comprendre ce ticket en fait. Qu'entendez-vous par "La flèche doit être à gauche de contacts presse et pas au dessus" ?
Voici le rendu de ce module après insertion dans l'éditeur de texte riche : 

![image](https://user-images.githubusercontent.com/1919354/41238153-96e19e60-6d95-11e8-94c0-d010d0ffcc0e.png)

Selon moi, c'est conforme avec la créa graphique : 

![image](https://user-images.githubusercontent.com/1919354/41238219-b380f098-6d95-11e8-8b23-ddd59438e561.png)

**Comment by ANGELEROBLOT** [comment]
Voici comment cela s'affiche sur mon écran : 
![image](https://user-images.githubusercontent.com/39916838/41239022-be547fa6-6d97-11e8-8360-47e4545d32ab.png)
Il ne s'agit vraiment d'une flèche mais du triangle tête en bas. Chez vous il est au dessus de "presse", mais chez moi il est détaché du cadre et au dessus du "C" de "contacts"
Est-ce simplement une erreur d'affichage ?

**Comment by LucDelmon** [comment]
Bonjour,

Il s'agit en effet d'un problème d'affichage. 

Cependant nous avions corrigé ce problème ( c'est pour cette raison que nous ne l'avons pas).

S'agit t'il d'un template que vous avez insérez depuis un moment ? Le problème est-il toujours présent si vous réinsérez  le template ?

**Comment by ANGELEROBLOT** [comment]
Oui il est toujours présent 
![image](https://user-images.githubusercontent.com/39916838/41240395-b1d2b39e-6d9a-11e8-8726-03f50cffd3e4.png)

**Comment by LucDelmon** [comment]
Sur quel page travaillez-vous ( dans l'arborescence de droite)? Je vais aller vérifier si j'ai le même rendu.

**Comment by ANGELEROBLOT** [comment]
Je le fais dans un contenu interne d'"actualités"

**Comment by LucDelmon** [comment]
En effet, j'ai le problème aussi.

C'est juste de l'affichage. Je vais le corriger.

**Comment by ANGELEROBLOT** [comment]
Merci :)

**Comment by LucDelmon** [comment]
C'est fait. Il faut cependant recharger le module.

**Comment by ANGELEROBLOT** [comment]
Merci, désormais cela s'affiche correctement
