### ISSUE TITLE
Breakpoint responsive / problème d'affichage 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#220]
Bonjour,

Sur Chrome, il y a un problème d'affichage du site sur les portables 1360 x 768, les titres et CTA sont coupés.

Je te mets deux exemples d'aperçu.

![02](https://user-images.githubusercontent.com/40030677/44858758-ffa43180-ac72-11e8-8b4b-b8d590c676e1.PNG)

![01](https://user-images.githubusercontent.com/40030677/44858764-03d04f00-ac73-11e8-80e9-e5362efa7b84.PNG)

Est-ce un problème de breakpoint ?

Peux-tu le solutionner ?

Merci

**Comment by nicolastrenti** [comment]
Luc, peux-tu voir ce qu'on peut faire sur le sujet ?
Changer le breakpoint me semble compliqué à ce stade.

**Comment by LucDelmon** [comment]
j'ai remonté le breakpoint, ca devrait passer en affichage de type mobile plus tôt et corriger le problème

**Comment by LaetitiaVerdier** [comment]
Effectivement, mes collègues qui ont ce format m'ont confirmée que cela fonctionnait bien.

Il n' y a pas de risques que le changement de breakpoint ait un impact sur les autres tailles d'écran ?

Merci

**Comment by LucDelmon** [comment]
Bonjour,

Les écrans très petits pourront passer en vue mobile mais ce n'est pas un mal. 

Il vaut mieux avoir un affiche mobile qu'un affichage desktop avec des éléments coupés ou qui se superposent.

**Comment by LaetitiaVerdier** [comment]
D'accord.

Merci
