### ISSUE TITLE
URGENT / Problème format de photos

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#222]
Bonjour,

Nous avons, depuis ce matin, un problème avec toutes les photos de format 518 x 571 px sur le mobile et le desktop.

![screenshot_2018-09-03-17-35-14](https://user-images.githubusercontent.com/40030677/44994788-9426d080-afa0-11e8-90af-5f9c49f78c5b.png)
![screenshot_2018-09-03-17-34-59](https://user-images.githubusercontent.com/40030677/44994789-9557fd80-afa0-11e8-9e52-cc177a9ccced.png)

Pouvez-vous rétablir les formats ?

Merci

**Comment by LaetitiaVerdier** [comment]
Sur le mobile c'est catastrophique

**Comment by LucDelmon** [comment]
Bonjour,

les formats d'images ont tous changés tout seul ?

**Comment by LaetitiaVerdier** [comment]
J'ai eu un message d'un collègue hier pour m'alerter.

J'ai vérifié et les formats sur mobile n'étaient effectivement plus bon alors que tout était correct vendredi.

Je n'en sais pas plus.

**Comment by LucDelmon** [comment]
J'ai identifié le problème.

le format n'a pas changé c'est l'attribute de l'image.

les images concernées sont en fixed sized. Elles se retrouvent donc étirées lorsque la taille de l'écran change.

![capture d ecran 2018-09-04 a 10 39 36](https://user-images.githubusercontent.com/35261367/45020318-eadaeb80-b02e-11e8-9742-93e0b80317f6.png)

Ce n'est pas normal elles devraient être en responsive size ( je ne sais pas ce qui les a modifiées).

Ils faut donc passer sur les images en question et changer cet attribut puis publier (je l'ai fait sur l'acceuil).

**Comment by LaetitiaVerdier** [comment]
Est-il possible de mettre par défaut dans les snippets responsive sizer sur les visuels ?

Merci

**Comment by LucDelmon** [comment]
c'est le cas ( c'est pour ca que le problème n'étaient pas présent au début). Je ne sais pas ce qui à pu affecter les visuels ( à part une modification manuelle)

**Comment by LaetitiaVerdier** [comment]
Je ne comprends pas non plus.

Pour les pictos et photos témoignages par contre, je reste bien sur une fixed size par défaut et cela est également paramétrer dans les snippets ?

**Comment by LucDelmon** [comment]
Oui,

les snippets sont tous configurés pour appliquer la bonne configuration ( ca faisait partie intégrante du développement des snippets).

il faut appliquer le style quand vous détectez une déformation forte en mobile.

**Comment by LaetitiaVerdier** [comment]
C'est bien noté. Parfois, je ne m'explique pas les bugs.
