### ISSUE TITLE
Fichier Search Console

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#223]
Les personnes en charge du SEO demande à ce que le fichier ci-après soit ajouté à la racine du site asso (accessible à l'adresse "ucpa.asso.fr/googled439fdca7a3c6d03.html" )

Merci

**Comment by dfanchon** [comment]
Pouvez-vous nous envoyer le fichier par mail ?

Merci

**Comment by LaetitiaVerdier** [comment]
Bonjour,

C'est fait à l'instant.

**Comment by dfanchon** [comment]
Bonjour, le fichier est normalement en place (https://www.ucpa.asso.fr/googled439fdca7a3c6d03.html), pouvez-vous vérifier que le site est bien validé par la search console ?

**Comment by LaetitiaVerdier** [comment]
Bonjour,

J'ai demandé à notre service de vérifier.

**Comment by LaetitiaVerdier** [comment]
Tout est bon.

Merci
