### ISSUE TITLE
Mobile / Dispositifs solidaires - logos

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#225]
Bonjour,

Nous avions acté de ne pas mettre les logos des partenaires sur le mobile dans les dispositifs solidaire et les offres de formation.

![screenshot_20180906-160213](https://user-images.githubusercontent.com/40030677/45165019-28d53c80-b1f4-11e8-99a7-f4660b049af3.jpg)

https://www.ucpa.asso.fr/le-sport-pour-tous/dispositifs-solidaires

https://www.ucpa.asso.fr/formations/offres-de-formation

Pouvez-vous les retirer quand ils sont apparents et ne les laisser que sur le desktop ?

Merci

**Comment by LucDelmon** [comment]
Bonjour,

Je ne trouve pas de page ou le comportement à lieu, pour moi les logos disparaissent en mobile

**Comment by LaetitiaVerdier** [comment]
j'ai le cas dans la Ville à la mer

**Comment by LaetitiaVerdier** [comment]
Le Phare

**Comment by LaetitiaVerdier** [comment]
Séjour Horizon Vaires Torcy

**Comment by LaetitiaVerdier** [comment]
Ville vie vacances.

En bref 
https://www.ucpa.asso.fr/accueil/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/ville-vie-vacances
https://www.ucpa.asso.fr/accueil/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/sejour-horizon-vaires-torcy-2024
https://www.ucpa.asso.fr/accueil/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/de-la-ville-a-la-mer
https://www.ucpa.asso.fr/accueil/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/le-phare

Nota Bene : **il y a toujours le mot "accueil" dans les URL alors que nous souhaitons que cela disparaisse.**

**Comment by LucDelmon** [comment]
c'est corrigé. Les attributs avaient sautés sur les images ( dans le snippet ils sont bons).

Il y a peut être un problèmes lors du remplacement de l'image. Je vais investiguer.

Pour l'histoire du mot Acceuil, les 2 versions existent, avec et sans acceuil.
 https://www.ucpa.asso.fr/le-sport-pour-tous/dispositifs-solidaires/dispositif-solidaire/le-phare  

Le lien depuis la liste est généré et renvoi vers la version avec acceuil.

On va voir s'il est possible d'améliorer le système actuel pour renvoyer vers le bon détail depuis la liste.

**Comment by LaetitiaVerdier** [comment]
Merci.

Décidément, j'ai dû repasser sur tous les contenus également car tous les visuels étaient en fixed size alors que je n'y avais jamais touché.

Pour les URLs, nous avons fait la demande en #217

Merci

**Comment by LucDelmon** [comment]
Je viens de tester, si on utilise bien l'option de remplacement sur l'image il n'y a pas de problèmes.

Je penses qu'il faut faire attention avec ce snippet à bien remplacer les images présentes de base

**Comment by LaetitiaVerdier** [comment]
Je ne sais pas comment faire pour changer l'image autrement que par le remplacement mais il est vrai que je n'ai pas été la seule à charger les dispositifs solidaires et je n'ai pas vu comment ma collègue s'y est prise
