### ISSUE TITLE
Slider / Diaporama

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#226]
J'ai regardé un de mes diaporamas sur mobile et le slider ne fonctionne pas.

![screenshot_20180906-155634 1](https://user-images.githubusercontent.com/40030677/45167585-c121f000-b1f9-11e8-8891-309ee83262e0.jpg)

Voici un exemple :
https://www.ucpa.asso.fr/le-sport-des-territoires/projets-de-reference/projet-de-reference/centre-equestre-marseille-pastre

**Comment by LaetitiaVerdier** [comment]
Bonjour,

Est-ce qu'il y a un blocage à ce sujet ?

Merci

**Comment by LucDelmon** [comment]
Bonjour,

Je n'ai pas réussi à recréer le problème. Le diaporama marche très bien pour moi. C'est sous Iphone qu'il ne fonctionne pas ?

**Comment by LaetitiaVerdier** [comment]
Non sous android, les photos ne changent pas automatiquement, le slider nécessite une action manuelle.

**Comment by LucDelmon** [comment]
Je n'avais compris que c'était la lecture automatique qui ne fonctionnait pas , je pensais que c'était les slides. Je vais vérifier.

**Comment by LucDelmon** [comment]
Je viens de vérifier et ca semble marcher, comme on l'a évoqué dans la #182 le diaporama défile automatiquement au bout de 5 secondes ( et on ne peut à priori pas changer ce délai).

Il est à noter aussi qu'a partir du moment ou l'on touche au diaporama il arrête l'autoplay ( il considère que si tu choisis une slide spécifique c'est que tu veux la lire).

Est-il possible de tester à nouveau en prenant en compte ces infos et me dire si le problème est toujours la ?

**Comment by LaetitiaVerdier** [comment]
Vous avez raison, cela fonctionne, j'avais dû toucher l'image.

Merci
