### ISSUE TITLE
Problème chargement photo

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#227]
Bonjour,

Je ne parviens pas à charger la photo suivante dans la médiathèque.

Pouvez-vous me dire ce qui bloque ?

Merci

![dispositif-solidaire-sejour-inclusion-vacances-a](https://user-images.githubusercontent.com/40030677/45290035-dabf8200-b4ee-11e8-9cb1-6fc2293f85a6.JPG)

**Comment by LucDelmon** [comment]
Bonjour,

A quel moment l'import échoue exactement ? Y a t'il un message d'erreur quelque part ?

**Comment by LaetitiaVerdier** [comment]
Bonjour,

Non aucun. Tout se passe normalement jusqu'à upload, puis la photo ne s'affiche jamais.

**Comment by LucDelmon** [comment]
Quel est la taille de la photo chez vous ( en mémoire ).

**Comment by LaetitiaVerdier** [comment]
275 Ko

**Comment by LucDelmon** [comment]
quel est l'extension de l'image (.jpeg, autres)

**Comment by LucDelmon** [comment]
Sinon est-il possible d'avoir l'image originale par mail (Github retraite l'image) a luc.delmon@webtales.fr

**Comment by LucDelmon** [comment]
C'est bon. le problème venait de l'extension .JPG qui étaient en majuscule. En passant à .jpg le problème c'est résolu. Il est étonnant qu'aucun message d'erreurs ne soit remontés. Je vais voir si on peut améliorer ca.

**Comment by LaetitiaVerdier** [comment]
Merci beaucoup.
