### ISSUE TITLE
Urgent - Taille des enveloppes - bloc contacts

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#228]
Bonjour,

j'ai une actualité à envoyer aux médias en urgence et ai un problème de taille d'enveloppe dans le bloc contacts.

https://www.ucpa.asso.fr/accueil/actualites/actualite/travaux-futur-complexe-aqualudique-reims-ont-demarre

Pouvez-vous m'aider ?

Merci

**Comment by LucDelmon** [comment]
Bonjour, 

c'est fait. Pour l'instant c'est visible avec no-cache=true.

Le problème venait encore de l'attribut des images. Elles n'étaient pas en fixed-size. 

J'ignore pourquoi les attributs sautent comme ça. On va essayer de voir ce qui peut causer ça.

**Comment by LaetitiaVerdier** [comment]
Merci Luc
