### ISSUE TITLE
Changement de favicon

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#229]
Bonjour,

Notre favicon vient de changer.

Je n'arrive pas à envoyer le fichier via GitHub.

Je l'envoie par mail.

Merci.

Laëtitia.

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,
C'est normalement bon : https://www.ucpa.asso.fr/?no-cache=true
Bonne journée,
Nicolas

**Comment by LaetitiaVerdier** [comment]
Merci
