### ISSUE TITLE
1 article lié + 1 photo

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#23]
Il y a un problème d'affichage, le format image ne devrait pas être en full screen mais dans le format ci-dessous

![image](https://user-images.githubusercontent.com/40030677/41162204-821f002e-6b35-11e8-886e-a5713a8f6c99.png)

**Comment by nicolastrenti** [comment]
Selon moi, c'est déjà bien le cas sur le module "1 article lié + 1 photo" : 

![image](https://user-images.githubusercontent.com/1919354/41219372-5c0821ec-6d5e-11e8-97a4-9e756aa4b8fe.png)

**Comment by LaetitiaVerdier** [comment]
Oui celui-ci s'affiche bien mais dans mon test en preview vendredi il s'agissait d'un full screen
