### ISSUE TITLE
Problème affichage - Page contact

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#230]
Bonjour,

Le mail de la Direction du développement ne s'affiche pas alors qu'il est saisi en internal content.

![image](https://user-images.githubusercontent.com/40030677/46602376-472ea080-caf0-11e8-9c97-ef7aba65f2c0.png)
![image](https://user-images.githubusercontent.com/40030677/46602387-501f7200-caf0-11e8-942b-db0aa016a44a.png)

Belle journée,

**Comment by nicolastrenti** [comment]
Laetitia,

C'est corrigé (erreur de notre côté sur la requête de ce bloc liste) :
https://www.ucpa.asso.fr/accueil/contact?no-cache=true

**Comment by LaetitiaVerdier** [comment]
merci
