### ISSUE TITLE
PDF Rapport annuel

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#231]
Bonjour,

Le rapport annuel finit sur une page 404.

https://www.ucpa-vacances.com/download/fstore/Documents_PDF/RAPPORT_ANNUEL/2018_009_dircom_rapport_global_BD.pdf

Merci

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,

Le lien que tu nous donnes ne correspond pas à un document hébergé chez nous (c'est sur www.ucpa-vacances.com, nous ne gérons pas ce site).

Nicolas.

**Comment by LaetitiaVerdier** [comment]
Bonjour Nicolas,

Effectivement, je me souviens maintenant avoir fait cela à la sortir du site car le PDF que vous aviez intégré au stade de la recette ne marchait pas en production.

Peux-tu l'intégrer ?

Merci
[Rapport_annuel_2017_BD.pdf](https://github.com/ampize/ampize-ucpa-corpo-recette/files/2477922/Rapport_annuel_2017_BD.pdf)

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,

Comme la nouvelle médiathèque est en place, je te conseille d'utiliser Cloudinary pour ce type de documents (ça te permettra d'uploader de nouvelles versions par la suite si nécessaire).
Une fois le PDF ajouté à la médiathèque, tu peux récupérer son URL par l'intermédiaire de ce bouton : 
![image](https://user-images.githubusercontent.com/1919354/46998966-75316780-d124-11e8-90d0-951fa5d29f20.png)
C'est cette URL qu'il faut coller dans le lien dans ton texte riche.

Bonne journée,
Nicolas
