### ISSUE TITLE
Template texte sans titre

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#24]
Pourriez-vous, s'il vous plait, créer un template de texte sans titre et l'appeler "Texte"
Merci

**Comment by nicolastrenti** [comment]
Angèle,
On part vraiment juste sur du texte, sur 1 colonne (toute la largeur), sans filet rouge avant ou après ?

**Comment by ANGELEROBLOT** [comment]
Bonjour Nicolas, 
Il faut garder le filet rouge avant et après. Simplement enlever le titre.
Merci
Angèle

**Comment by nicolastrenti** [comment]
Module "Texte" ajouté

**Comment by ANGELEROBLOT** [comment]
Merci Nicolas
