### ISSUE TITLE
Fermeture après avoir sauvegardé

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#25]
la fenêtre de création d'un article d'actualité se ferme à chaque fois que je "save". Cela fait perdre du temps. Y a-t-il un moyen pour que la page d'écriture ne se ferme plus quand on sauve ? 
Merci

**Comment by nicolastrenti** [comment]
Evolution en cours d'analyse : https://github.com/ampize/ampize/issues/133

**Comment by nicolastrenti** [comment]
Evolution déployée

**Comment by ANGELEROBLOT** [comment]
merci
