### ISSUE TITLE
Tags + liste thématique

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#26]
Comment fait-on pour créer des tags sur les articles d'actualité ? Et comment devrai-je procéder pour ranger les actualités dans la liste de thématique ? 
Merci

**Comment by nicolastrenti** [comment]
Pour les tags, nous allons rajouter un champ sur le type de contenu pour vous permettre de les saisir. Ces mots-clés seront automatiquement rajoutés dans la balise keywords de la page de détail pour le SEO.

Pour ranger les actualités par thématique, le champ à utiliser est "Catégorie".

**Comment by ANGELEROBLOT** [comment]
D'accord, merci beaucoup
