### ISSUE TITLE
Joindre un document

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#27]
Comment puis-je faire pour ajouter dans le corps de texte un lien de téléchargement d'un document (type dossier de presse)  ? 

Comme ici : 
![doc](https://user-images.githubusercontent.com/39916838/41162960-adeafcec-6b37-11e8-9804-75f2d7fb6d7d.JPG)

**Comment by nicolastrenti** [comment]
Evolution en cours d'analyse : https://github.com/ampize/ampize/issues/136

**Comment by LaetitiaVerdier** [comment]
Savez-vous si cet élément est réglé ?

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,

Non, notre refonte de la médiathèque n'a pas suffisamment avancé pour vous permettre d'uploader des documents autres que des images. Je laisse donc ce ticket ouvert.

Pour le lancement, deux solutions : 
- Tu peux m'envoyer les PDF à héberger et je les déposerai manuellement sur le serveurs
- Ou sinon il vous faudra passer par une solution d'hébergement externe (type dropbox), le temps que nous puissions uploader des PDF dans la médiathèque

**Comment by LaetitiaVerdier** [comment]
D'accord.

Pour le lancement, nous aurons une dizaine de PDF (rapport annuel, liste de la gouvernance et quelques dossiers de presse), je pense donc qu'on vous les transmettra.

Merci
