### ISSUE TITLE
remplacer les adresses mails par icone enveloppe

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#28]
Pouvez-vous, s'il vous plait, remplacer les adresses mails de tous les blocs contacts par l'icone enveloppe avec un lien mailto ? 

Merci

**Comment by nicolastrenti** [comment]
Corrigé dans les différents modules

**Comment by ANGELEROBLOT** [comment]
Merci, cependant l'enveloppe n'est pas alignée 
![image](https://user-images.githubusercontent.com/39916838/41238887-5dfddfb2-6d97-11e8-8c9c-59c948748489.png)

**Comment by LucDelmon** [comment]
Le problème d'alignement est un problème d'affichage présent uniquement dans l'éditeur de contenu. L'enveloppe sera correctement alignée lorsque le contenu sera visible sur le site.

**Comment by ANGELEROBLOT** [comment]
d'accord
Merci
