### ISSUE TITLE
Barre d'outils

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#29]
Est-il possible d'avoir une barre d'outils qui apparaissent au niveau du curseur ?

En effet, lorsque nous introduisons un module à la suite, il faut scroller pour remonter à la barre et plus l'article est long plus nous devons scroller pour ajouter un nouveau module.

Merci

**Comment by nicolastrenti** [comment]
Evolution en cours d'analyse : https://github.com/ampize/ampize/issues/134

**Comment by nicolastrenti** [comment]
Evolution déployée
