### ISSUE TITLE
Calage créa

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#3]
Bonjour,

Globalement, il y a trop de blancs (d'espaces) avant les tirets et après.

Dans le "A propos", il faut prévoir l'emplacement du picto sportif que l'on décide de le mettre ou pas.
![image](https://user-images.githubusercontent.com/40030677/41108669-7196f290-6a75-11e8-9736-a119be7ae5ca.png)

Parfois, la photo du témoignage est ovale au lieu de ronde (cf. maquette). 
![image](https://user-images.githubusercontent.com/40030677/41108586-3bda2870-6a75-11e8-9792-975555fc9315.png)

La trame (avec des les pictos à gauche et droite de la photo) doit être équilibrée de chaque côté 
![image](https://user-images.githubusercontent.com/40030677/41108739-912dccd2-6a75-11e8-9cf7-be4673207b9f.png)

Il y a un problème de taille sur les logos partenaires : beaucoup trop gros

Dans les articles liés projets, la photo est décalé sur la gauche 
![image](https://user-images.githubusercontent.com/40030677/41108831-d1e638ea-6a75-11e8-88a8-99a71de6315f.png)

Il manque le filet rouge du dessous dans les témoignages et le filet + le mot témoignage doivent être alignés sur le texte. Le texte des témoignages entre "" a une taille supérieure. 

Merci

**Comment by nicolastrenti** [comment]
Les différents points ont été scindés en plusieurs tickets pour faciliter le suivi.
