### ISSUE TITLE
1 chiffre clé + article 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#31]
Dans le snippet chiffre clé + article, il n'y a pas l'option slider pour faire défiler plusieurs chiffres clés.

![image](https://user-images.githubusercontent.com/40030677/41164115-b3eba06c-6b3a-11e8-819d-ca168799757b.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait. En contribution les différentes slides arrivent à la suite afin de pouvoir les éditer mais une fois publiés on à bien le visuel demandé.

**Comment by LaetitiaVerdier** [comment]
Parfait merci
