### ISSUE TITLE
Photo format classique 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#32]
Le module "photo" seul est le suivant : ![image](https://user-images.githubusercontent.com/40030677/41164224-f056100a-6b3a-11e8-8fe5-d93f16afe113.png)

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,
Ce module existe, c'est celui qui s'appelle "Photo" actuellement.

**Comment by LaetitiaVerdier** [comment]
Bonjour Nicolas,

Je viens de vérifier et ça n'est pas le bon format. 

Celui qui est intégré est un full screen, 2544 x 639 px

Celui que je cherche est un format photo article, 518 x 571 px

**Comment by nicolastrenti** [comment]
Je ne comprends pas : le module "Photo" intégré est bien celui qui figure dans les PSD des modules. La photo y prend la largeur de la "colonne principale" (environ 1180px de large), soit la même largeur que la vidéo.

Exemple dans les PSD (vidéo en haut, photo en dessous) : 
![image](https://user-images.githubusercontent.com/1919354/41293821-a5a42cd0-6e56-11e8-8d2f-e017feda04d4.png)


Résultat dans l'éditeur (vidéo en haut, photo en dessous) : 
![image](https://user-images.githubusercontent.com/1919354/41293715-5f619960-6e56-11e8-8d39-a30570e2b17a.png)

**Comment by LaetitiaVerdier** [comment]
Je n'ai pas vu les PSD mais voici les différents formats de visuels prévus :

[format_visuels_ucpa_corpo_desktop_2018_06_06 (3).pdf](https://github.com/ampize/ampize-ucpa-corpo-recette/files/2094264/format_visuels_ucpa_corpo_desktop_2018_06_06.3.pdf)

**Comment by LaetitiaVerdier** [comment]
On peut en parler jeudi et regarder ensemble si cela simplifie les choses.

**Comment by nicolastrenti** [comment]
Le 518x571 évoqué dans ce document correspond au template "Article + photo colonne gauche" par exemple. C'est la photo presque carrée, légèrement plus haute (571px) que large (518px). Le rendu est le suivant : 

![image](https://user-images.githubusercontent.com/1919354/41294433-560d087a-6e58-11e8-9924-19e653658f6b.png)

**Comment by LaetitiaVerdier** [comment]
Alors je vais en reparler à Françoise car il nous manque un format visuel simple 1200 x 591 px (identique à celui du diaporama mais avec un seul visuel à charger)

**Comment by LaetitiaVerdier** [comment]
Ce qui est sûr c'est que le format du visuel avec le nageur de dos ci-dessus ne correspond à rien dans notre DA. Il correspondait à un format full screen dans nos PSD utilisé avec les 3 articles liés pour les projets loisirs

**Comment by LaetitiaVerdier** [comment]
Sinon j'ai peut-être un problème d'affichage

**Comment by nicolastrenti** [comment]
OK, je comprends ce qui pose problème : c'est simplement que nous avons réutilisé l'image du nageur pour éviter d'avoir à charger l'image des coureurs.
J'ai modifié le template "Photo full screen" pour y intégrer l'image des coureurs pour être conforme au PSD.

**Comment by LaetitiaVerdier** [comment]
C'est tout bon je viens de le tester.
