### ISSUE TITLE
Dupliquer un contenu

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#33]
Evolution évoquée lors du kick-off recette : pouvoir dupliquer un contenu existant, car la structure des actualités (empilement des snippets) est très souvent la même

**Comment by nicolastrenti** [comment]
Evolution en cours d'analyse : https://github.com/ampize/ampize/issues/127

**Comment by nicolastrenti** [comment]
Evolution déployée

**Comment by LaetitiaVerdier** [comment]
Merci.

Comment cela fonctionne ?

**Comment by nicolastrenti** [comment]
Dans l'interface de gestion des contenus internes, il y a une petite icone dupliquer sur la ligne (à côté de modifier et supprimer)

**Comment by LaetitiaVerdier** [comment]
Top !

Merci
