### ISSUE TITLE
Enveloppe dans contacts

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#34]
Bonjour,

L'enveloppe s'affiche mal dans contacts, il y a un décalage

![image](https://user-images.githubusercontent.com/40030677/41299748-6e3b5f62-6e64-11e8-8ebb-a91303b35460.png)

**Comment by nicolastrenti** [comment]
C'est le cas uniquement dans l'éditeur de texte riche. Une fois le contenu publié, ce décalage n'est pas visible sur le site.

**Comment by LaetitiaVerdier** [comment]
D'accord merci
