### ISSUE TITLE
Problème dans contenu interne

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#35]
J'ai essayé de faire un gabarit type pour les dispositifs solidaires sur l'exemple des vacances handisport.

A chaque fois que je sélectionne le module "texte 2 colonnes", que je le complète, je ne peux pas l'enregistrer. J'ai bien l'option save mais quand je retourne sur l'article le module a disparu.

Merci

**Comment by LucDelmon** [comment]
Bonjour,

Il y a eu plusieurs modifications sur les saves récemment.

Le problème arrive t'il toujours ?

**Comment by LaetitiaVerdier** [comment]
Je n'ai pas eu l'occasion d'en refaire. J'ai travaillé dans l'espace Mentions légales.

Nous avons prévu d'en faire demain matin. 

Je vous tiens informé.

Bien à vous,
