### ISSUE TITLE
création module "nouveau séjour"

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#36]
Il me faudrait, s'il te plait, un module dédié aux nouveaux séjours qui sera utilisé dans les articles "actualités": 
**LE CRI DE LA MARMOTTE - Telligo**
**Val Cenis - 6/11 ans**
Durant leurs vacances, les enfants partent à la découverte de la faune et de la flore du Parc National de la Vanoise à pieds, à dos d'âne ou en cani-rando. Accompagnés par un guide, ils suivent les traces des marmottes, apprennent à reconnaître leur sifflement et tentent de les observer en toute discrétion. Après avoir découvert la mascotte de la montagne, les enfants partent en randonnée avec des ânes, avant cela, ils apprennent quel comportement adopter avec l’animal, comment le bâter puis comment le diriger. Pendant cette balade, ils découvrent de nombreuses espèces végétales et apprennent à les reconnaître : orchis des Alpes, renoncule des glaciers et bien d’autres. Cette journée se termine en observant les étoiles et les constellations, avant de passer une nuit sous tente. Les enfants découvrent un autre moyen de randonner en montagne : avec les chiens, ils partent en cani-rando ! Chacun harnaché à son chien, les enfants vivent un moment hors du commun et tissent des liens avec leur nouveau compagnon de balade !
_11 jours/10 nuits - Départs les 7 & 18 juillet et les 1er & 12 août 2018 - À partir de 865€*_

Voila : 
![capture](https://user-images.githubusercontent.com/39916838/41406207-54aa2aa8-6fbb-11e8-8c22-174440cb54b7.JPG)

**Comment by LucDelmon** [comment]
Bonjour,

Le module a été créé.

**Comment by ANGELEROBLOT** [comment]
merci beaucoup
