### ISSUE TITLE
Spécificité Menu + image / contenus

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#37]
Bonjour Nicolas,

Comme vu ensemble, nous avons besoin de modifier la photo du menu pour chaque contenu : 
- projet de référence
- dispositifs solidaires
- offres de formation

![image](https://user-images.githubusercontent.com/40030677/41411188-35069b3e-6fdc-11e8-8f0b-e358dad9fcd7.png)

Merci

**Comment by LucDelmon** [comment]
Bonjour,

Je suis en train de le faire.

Souhaitez-vous qu'une image par défaut soit présente dans le cas ou l'image n'est pas renseigné dans le contenu ?

Ou alors souhaitez-vous que le champ correspondant à cette image soir obligatoire dans la création du contenu ?

**Comment by LaetitiaVerdier** [comment]
Il s'agit d'un champ obligatoire.

Merci

**Comment by LucDelmon** [comment]
Bonjour,

C'est fait.

N'hésitez pas à m'indiquer si d'autres champs doivent être obligatoires dans les contenus internes  car rajouter des champs obligatoires implique de supprimer les contenus internes existants ( puisqu'ils deviennent invalides)

**Comment by LaetitiaVerdier** [comment]
La catégorie et la date sont obligatoires uniquement pour les actualités. 

Le titre, l'image et le résumé sont obligatoires dans tous les cas.

Merci

**Comment by LucDelmon** [comment]
Bonjour,

Avant que je le fasse, assurez vous que  tout les contenus que vous avez créés ( surtout les actualités) disposent de ces champs. Pour que je n'ai pas à les supprimer.

**Comment by LaetitiaVerdier** [comment]
Pouvez-vous me préciser comment apparaît le résumé et où en preview ?

Merci

**Comment by LucDelmon** [comment]
Le résumé apparait dans le chapeau a gauche a coté du trait rouge. Pour le voir en preview il faut aller sur une page de liste ( Actualités par exemple). Lancer le preview puis cliquer sur le contenu pour être amener sur la page de détail.

**Comment by LucDelmon** [comment]
J'ai modifié les contenus pour rendre le résumé et les images obligatoires .
