### ISSUE TITLE
Question des copyrights photo

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#38]
Comment conserver les copyrights pour les photos sur le web ?

Merci

**Comment by LaetitiaVerdier** [comment]
A date, nous n'avons les noms de photographes que dans la page Crédits du site, cela suffit-il ?

Merci

**Comment by nicolastrenti** [comment]
Après vérification, l'usage veut que les copyrights soient soit indiqué sous chaque image (dans une balise <small>), mais cela surcharge la mise en page, soit dans le footer, soit au sein d'une page Crédits. Je pense que c'est effectivement la meilleure solution dans notre cas.

**Comment by LaetitiaVerdier** [comment]
Top je vais donc faire une page crédits
