### ISSUE TITLE
Filtre / Header page Hub + contenus

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#39]
Bonjour,

Dans les PSD fournis par Françoise, il y a un filtre fourni pour améliorer la lisibilité du menu.

Pouvez-vous l'ajouter sur le menu header des pages Hub ainsi que sur les contenus : 
- projets de référence
- dispositifs solidaires
- offres de formation

Merci

**Comment by LucDelmon** [comment]
Bonjour,

Je ne vois pas de quel filtre il s'agit. Qu'est il sensé filtrer ?

Il s'agit du même menu à choix que dans contact ?

**Comment by LaetitiaVerdier** [comment]
Non il s'agit d'un filtre d'images, pas d'un filtre pour sélectionner des informations.

C'est un léger gris dégradé qui aide la lecture du menu quand une image est associée comme ci-dessous :
![image](https://user-images.githubusercontent.com/40030677/41461228-68affee0-708f-11e8-8aed-fd7d379dcc6d.png)

**Comment by LucDelmon** [comment]
c'est fait

**Comment by LaetitiaVerdier** [comment]
Merci
