### ISSUE TITLE
Format 1 photo manquant

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#4]
Le format 1 photo nécessaire dans les articles en dehors des projets loisirs est manquant

**Comment by LucDelmon** [comment]
Bonjour,

je n'arrive pas à identifier le format que vous évoquez. 
Il y a déjà un template "Photo" qui permet d'afficher une image seule. 
Je n'ai pas identifié d'autres modules pour les photos dans les maquettes

**Comment by LaetitiaVerdier** [comment]
![image](https://user-images.githubusercontent.com/40030677/41157070-aeb86f46-6b24-11e8-908d-bd64e27b466c.png)

Il s'agit de ce gabarit ci.

![ucpa_corpo_lot_6_desktop_modules_b_2018_04_26](https://user-images.githubusercontent.com/40030677/41157089-c79d2b1e-6b24-11e8-95db-e48969448511.jpg)
