### ISSUE TITLE
Format visuel header 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#40]
Pouvez-vous nous confirmer que le format des visuels en header sur les pages Hub + contenus font bien  2544 x 702 px ?

Si le format est différent pour raisons techniques, pouvez-vous nous fournir celui-ci ?

Merci

**Comment by LucDelmon** [comment]
Bonjour,

Si vous évoquez bien les visuels qui viennent se placer sous le menu, ils n'ont pas de format spécifique.

Le format est lié à l'image en elle même. l'image prend automatiquement toute la largeur et conserve son ratio d'origine ( entre hauteur et largeur).

Si vous souhaitez un format de 2544 x 702 px il vous suffit d'upload des images de cette taille la.

**Comment by LaetitiaVerdier** [comment]
D'accord merci

C'est noté
