### ISSUE TITLE
Espacement avant et après filet titre rouge

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#41]
Il nous semble que les espacements avant et après filet titre rouge demeurent trop importants. 

De même, pouvez-vous vous assurer que l'espace est toujours identique d'un snippet à l'autre ?

![image](https://user-images.githubusercontent.com/40030677/41415026-d4d71bce-6fe7-11e8-9638-043760a33778.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est ce que vous souhaitez ? ( c'est réduit de moitié) 

![capture d ecran 2018-06-15 a 11 51 41](https://user-images.githubusercontent.com/35261367/41462293-ad9ca24e-7092-11e8-8e32-0237914108bb.png)

**Comment by LaetitiaVerdier** [comment]
Oui, c'est mieux. 

Mais il faut que l'écart soit identique entre le texte et le filet au-dessus et en-dessous (je préfère que l'on garde la référence du dessous si possible).

Merci

**Comment by LucDelmon** [comment]
Bonjour,

je l'ai fait et j'ai uniformisé sur tout les snippets comprenant le filet

**Comment by LaetitiaVerdier** [comment]
Merci. Egalement sur la version mobile ?

Merci
