### ISSUE TITLE
Alignement chapeau loisirs

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#42]
Est-il possible d'aligner le bloc noir sur le haut de la capitale du premier mot du chapeau (cf. **T**emple dans l'exemple ci-dessous) ?

![image](https://user-images.githubusercontent.com/40030677/41415154-2766a814-6fe8-11e8-993b-54e4efd7677b.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait

**Comment by LaetitiaVerdier** [comment]
C'est en effet résolu sur le desktop mais j'ai le même problème sur le mobile.

![image](https://user-images.githubusercontent.com/40030677/41598597-e4948afa-73d0-11e8-90d7-4f839e6e93ac.png)

**Comment by LucDelmon** [comment]
Bonjour,

j'ai résolu le problème sur mobile également.
