### ISSUE TITLE
Manque picto activité / chapeau loisirs

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#43]
Dans le snippet, nous avons le picto cross de hockey apparent, cependant quand nous le regardons en ligne sur https://ucpa-corpo.recette.ampize.me/accueil/mentions-legales, il a disparu.

**Comment by LucDelmon** [comment]
Bonjour,

c'est corrigé.

Cordialement

**Comment by LaetitiaVerdier** [comment]
Merci
