### ISSUE TITLE
Chapeau Loisirs / puces losange bloc noir

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#44]
Les losanges ne sont pas centrés sur la hauteur de la capitale. 

![image](https://user-images.githubusercontent.com/40030677/41415675-67a201b6-6fe9-11e8-8b3d-821a80b70e05.png)

**Comment by LucDelmon** [comment]
Bonjour,

C'est corrigé

**Comment by LaetitiaVerdier** [comment]
Merci
