### ISSUE TITLE
Alignement bloc contact

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#45]
Est-il possible d'aligner le bloc contact sur le haut des caractères de la date pour le snippet "actualités chapeau" ?

![image](https://user-images.githubusercontent.com/40030677/41415934-018d9c68-6fea-11e8-8138-366d4a1392f3.png)

De même, il faut aligner le bloc contact pour le snippet "dispositif solidaire chapeau" sur le haut des capitales (cf. ci-dessous VACANCES)

![image](https://user-images.githubusercontent.com/40030677/41416127-7afc1890-6fea-11e8-9f28-ae94f559c9b5.png)

**Comment by LucDelmon** [comment]
Bonjour,

C'est fait.
