### ISSUE TITLE
Bloc contact / Taille des noms des contacts

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#46]
Le nom des personnes doit figurer dans un corps plus petit (- 3 points typo) que le texte courant :
Ci-dessous Angèle Roblot et Laëtitia Verdier

![image](https://user-images.githubusercontent.com/40030677/41416350-ec38f71c-6fea-11e8-8d65-5e05109bfb93.png)

**Comment by LaetitiaVerdier** [comment]
Idem pour l'identité des témoins dans le snippet "Témoignage"; il faut conserver le même corps 

![image](https://user-images.githubusercontent.com/40030677/41416879-31982c8c-6fec-11e8-88d9-5efb545635f1.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait.

Cordialement

**Comment by LaetitiaVerdier** [comment]
Merci
