### ISSUE TITLE
Espacement Texte / Snippet Texte + photo gauche

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#47]
A l'intérieur du paragraphe du snippet "Texte + photo gauche", l'espace avant le second sous-titre est trop petit.

Idem pour le snippet "Texte 2 colonne"

![image](https://user-images.githubusercontent.com/40030677/41416557-6d60c176-6feb-11e8-954d-c1fbcbb6e4d6.png)

**Comment by LaetitiaVerdier** [comment]
Idem snippet "texte 1 colonne"

**Comment by LaetitiaVerdier** [comment]
J'ai également un problème d'espace entre les paragraphes dans le snippet "fiche d'identité loisirs"

![image](https://user-images.githubusercontent.com/40030677/41584309-43efad88-73a7-11e8-85ca-6d1abcfda6ff.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait. A vous de me dire si les écarts vous conviennent.

**Comment by LaetitiaVerdier** [comment]
Oui tout à fait merci
