### ISSUE TITLE
Page Hub chiffres clés

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#48]
Dans le snippet "page hub chiffres clés", la marge du haut est trop petite et les filets doivent être très rapprochés.

![image](https://user-images.githubusercontent.com/40030677/41417289-2a4eead2-6fed-11e8-8684-8e2111c010ef.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait.
