### ISSUE TITLE
Alignement filets rouges / Snippet Chiffre clé + texte

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#49]
Dans le snippet "Chiffre clé + texte", il faut aligner le filet de droite sur le filet rouge plein de gauche

![image](https://user-images.githubusercontent.com/40030677/41417381-7f171cba-6fed-11e8-8dc7-ae2608b0a8ab.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait.
