### ISSUE TITLE
Remplacer l'URL d'une vidéo

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#5]
Comment remplacer l'URL de la vidéo ? J'ai touché à l'éditeur mais cela ajoute une vidéo, je veux simplement changer le lien You Tube fourni dans le module.

**Comment by LucDelmon** [comment]
Bonjour, 

Vous devriez maintenant voir une bande rouge sous les videos. Cliquer dessus permet d'accéder à un menu permettant de changer la video.

Cette bande rouge n'est visible que dans l'éditeur.

**Comment by LucDelmon** [comment]
Avez-vous eu l'occasion de tester ?

**Comment by LaetitiaVerdier** [comment]
Oui cela fonctionne bien.
