### ISSUE TITLE
Snippet Loisirs Fiche d'identité

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#50]
Est-il possible de centrer le bloc fiche sur la trame et pouvez-vous vérifier la largeur du bloc fiche ?

Normalement, il devrait être un peu plus large.

![image](https://user-images.githubusercontent.com/40030677/41417547-f6fb4512-6fed-11e8-8c51-3ca39867befa.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est corrigé
