### ISSUE TITLE
double chapeau actualité

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#51]
Est-ce normal le double chapeau ? j'en insère pourtant un seul...

![image](https://user-images.githubusercontent.com/39916838/41421162-68bb35f6-6ff6-11e8-8d61-6d79b8d78ff7.png)

**Comment by nicolastrenti** [comment]
Angèle,
Il ne faut pas l'insérer dans le body, le chapeau est automatiquement inséré par le template de détail à partir des différents champs du contenu (titre, résumé, date).

**Comment by ANGELEROBLOT** [comment]
aaahhh c'est bien ce que je me disais !

Merci
