### ISSUE TITLE
Chargement de la banque de pictos / Médiathèque

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#52]
Bonjour,

Est-ce que le format PNG convient pour intégrer les pictos à la médiathèque ?

Nous en avons une centaine, est-ce problématique ?

**Comment by LucDelmon** [comment]
Bonjour,

Il n'y a pas de problèmes avec l'utilisation du format PNG. Il y a déjà des images de ce format dans  la bibliothèque. Pour ce qui est du nombre pas de problèmes non plus. Il y a une limite sur la taille totale à importer en une seule fois mais si c'est des pictos je penses que ca ne pose pas de problèmes.

**Comment by LaetitiaVerdier** [comment]
Merci
