### ISSUE TITLE
Nouvelle fonctionnalité / snippet articles liés x 3

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#53]
J'ai vu l'animation sur les trois articles liés et c'est top !

Par contre, nous avons besoin de changer la photo du dessous en full screen pour chaque article, on ne peut pas mettre un unique visuel pour les 3

![image](https://user-images.githubusercontent.com/40030677/41459715-a07a2738-708a-11e8-8131-6b1165ed7652.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait.

En contribution vous aurez 3 images à la suite . La première correspond au premier article etc.

Les images se retrouveront automatiquement en plein écran et superposées  une fois publiées.

par défaut on ne verra que l'image du première article et les autres apparaissent au survol de l'article qui leur correspond.

**Comment by LaetitiaVerdier** [comment]
Merci

**Comment by LaetitiaVerdier** [comment]
Bonjour,

J'ai toujours un problème de filet sur le 3ème article lié qui coupe le texte au lieu d'être au dessus.


<img width="1292" alt="capture d ecran 2018-06-20 a 15 11 39" src="https://user-images.githubusercontent.com/40030677/41665618-a9f0077a-74a8-11e8-841a-993b1c61f205.png">

**Comment by LaetitiaVerdier** [comment]
Ici sur le mot complexe

**Comment by LucDelmon** [comment]
Oui c'est normal, il fallait recharger le module.

Je suis allé faire les modifications directement dans votre contenu. 
Le problème a disparu désormais

**Comment by LucDelmon** [comment]
#55
