### ISSUE TITLE
Snippet articles liés

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#55]
Bonjour,

Quand je change le nom ci-dessous Aren'Ice, le filet rouge disparaît. Vous pouvez regarder l'article dans Internal Contents / Complexe aqualudique de Reims

![sans titre1](https://user-images.githubusercontent.com/40030677/41586568-64a0ade2-73ad-11e8-95a0-5a73a5ea8b83.png)

**Comment by LaetitiaVerdier** [comment]
Et il est décalé dans l'exemple trois (Brazza) sous le texte 

![sans titre](https://user-images.githubusercontent.com/40030677/41586505-35b034da-73ad-11e8-9731-075bd1d93f28.png)

**Comment by LucDelmon** [comment]
Bonjour,

j'ai corrigé les problèmes.

Il faudra par contre recharger les modules concernés.
