### ISSUE TITLE
bug texte + photo droite

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#57]
Le module texte + photo droite doit mal fonctionner, le texte se met sous l'image. Est-ce normal ? 

Merci 

![image](https://user-images.githubusercontent.com/39916838/41586518-42a118e4-73ad-11e8-8d65-bf15a8f3d6ad.png)

**Comment by LucDelmon** [comment]
Bonjour,

le problème est résolu.

Il faudra cependant recharger le module.

**Comment by ANGELEROBLOT** [comment]
Merci
