### ISSUE TITLE
Problème éditeur photo

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#58]
Lorsque que je vais dans l'éditeur et que je sélectionne le crop pour changer mon visuel sur le snippet articles liés loisirs x 3, cela ne fonctionne pas. 

Mon format photo prévu est 2544 X 639 px.

![image](https://user-images.githubusercontent.com/40030677/41587209-e5e39332-73ae-11e8-976c-c7513b4b0c7f.png)

**Comment by nicolastrenti** [comment]
Laetitia, l'éditeur d'images intégrés ne permet malheureusement pas à l'heure actuelle de gérer des images de tailles aussi conséquentes.
Tu m'avais dit, je crois, que votre studio vous avait prévu toutes les images aux bonnes dimensions directement ? Cela résout-il le problème, du coup ?

**Comment by LaetitiaVerdier** [comment]
Oui j'ai fait cropper tous les headers
