### ISSUE TITLE
Snippet articles liés x 3 loisirs / changement de visuels

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#59]
Bonjour,

Je n'arrive pas à trouver comment mettre les trois visuels en lien avec les articles liés.

**Comment by LucDelmon** [comment]
Bonjour,

Vous parlez des images ? l'ordre vertical des images est lié a l'ordre horizontal des articles.

**Comment by LaetitiaVerdier** [comment]
C'est bon de mon côté à part le filet rouge sur le troisième article lié, le reste fonctionne.

**Comment by LucDelmon** [comment]
#55 duplicate
