### ISSUE TITLE
Version mobile / taille des pictos médias sociaux

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#61]
Bonjour,

Sur la version mobile, les pictos ne sont pas suffisamment espacés et la taille est trop grande.

Pouvez-vous diminuer un peu l'encombrement ?

![image](https://user-images.githubusercontent.com/40030677/41598647-138f0f2e-73d1-11e8-9c84-1949a8d244b6.png)

**Comment by LucDelmon** [comment]
c'est fait, 

Par contre il va falloir recharger les modules concernés pour l'espacement
