### ISSUE TITLE
Version mobile / Snippet chapeau loisirs / Taille et type de typo

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#62]
Pouvez-vous me confirmer que la typo au niveau du "Temple de hockey" est bien la nôtre ?

Et qu'il y a bien 34 px avant et après le filet rouge ?

![image](https://user-images.githubusercontent.com/40030677/41599041-3f5187bc-73d2-11e8-9fe5-8f467e2895d2.png)

**Comment by LucDelmon** [comment]
Bonjour,

La police sur votre image n'est en effet pas la bonne mais je pense qu'il s'agit d'un problème de chargement ponctuel ( ca peut arriver) car j'ai la bonne police de mon coté.

Pour ce qui est de l'écart, il y avait en effet que 16 pixel.

c'est corrigé
