### ISSUE TITLE
Version mobile / snippet article lié 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#63]
Il y a un problème d'affichage de l'article lié en version mobile 

![image](https://user-images.githubusercontent.com/40030677/41599337-22c4ebce-73d3-11e8-86f8-322c2185f56e.png)

Voici ce que nous voulons en résultat 

![image](https://user-images.githubusercontent.com/40030677/41599431-76c1e61e-73d3-11e8-8d25-5f9a02d9ccd6.png)

**Comment by LucDelmon** [comment]
Bonjour,

La modification a été effectuée
