### ISSUE TITLE
Preview Actualités

### ISSUE THREAD

**Issue by ANGELEROBLOT** [ampize/ampize-ucpa-corpo-recette#64]
Les rubriques de la page Actualités ne s'affichent pas dans la preview, est-ce normal ? 

![image](https://user-images.githubusercontent.com/39916838/41599559-e29f4d22-73d3-11e8-8aa1-7d92f2b0f55c.png)

**Comment by LucDelmon** [comment]
Bonjour,

Oui c'est normal. 

Pour un soucis de performance le titre est récupéré à partir des articles.

Il faut donc qu'il existe au moins un article dans la rubrique pour que le titre s'affiche ( comme pour espace sportif sur l'image).

Est-il possible que des rubriques soit vides ? je suis parti de l'idée qu'il y aurait au moins un article par rubrique.

**Comment by ANGELEROBLOT** [comment]
D'accord merci beaucoup.

Effectivement les rubriques sont vides, je n'ai pas eu le temps de créer autant d'articles.
