### ISSUE TITLE
Version mobile / snippet page hub chiffres clés

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#65]
Bonjour,

Nous avions demandé un slider pour les chiffres clés dans la version mobile, cela n'est-il pas possible ?

Les 3 blocs les uns sous les autres ne semblent pas très satisfaisants. 

![image](https://user-images.githubusercontent.com/40030677/41599617-04105ece-73d4-11e8-831a-3b6bbbad42eb.png)

**Comment by nicolastrenti** [comment]
Laetitia, 
Non, malheureusement ça n'est pas possible techniquement, désolé.
Par contre je reconnais que le rendu n'est pas forcément très clair en l'état. Peut-être cela serait-il mieux en augmentant l'espace entre le libellé du type" en parcours d'insertion professionnelle et de formation" et le rond suivant ?

**Comment by LaetitiaVerdier** [comment]
Nicolas,

Oui je suis d'accord et il faudrait aussi baisser la taille des filets rouge et des pictos.

Merci

**Comment by LucDelmon** [comment]
C'est fait, j'attends votre retour

**Comment by LaetitiaVerdier** [comment]
Oui c'est mieux mais j'ai l'impression que le premier liseret rouge et le deuxième ne font pas la même taille.

![image](https://user-images.githubusercontent.com/40030677/41769179-b994368a-760e-11e8-9cd8-3ac6ffacaabe.png)

**Comment by LucDelmon** [comment]
Je viens de vérifier. Ils font la même taille pour moi.

Vous avez peux être chargé le module pendant que je faisais des modifications.

**Comment by LaetitiaVerdier** [comment]
Très bien.

Je vous remercie.
