### ISSUE TITLE
Version mobile / snippet à propos

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#66]
Nous avons un gros problème d'affichage du logo avec le snippet "à propos"

![image](https://user-images.githubusercontent.com/40030677/41599782-756d3754-73d4-11e8-8eb7-19544671f831.png)

De même, le picto utilisé ne convient pas, il s'agit de la main avec le cœur à la place.

![image](https://user-images.githubusercontent.com/40030677/41599905-bf2df626-73d4-11e8-8818-1d96bd22540e.png)

**Comment by LucDelmon** [comment]
Bonjour,

Le problème est corrigé.

Par contre je n'ai pas ce logo. Pouvez-vous me l'envoyer ?

**Comment by LaetitiaVerdier** [comment]
J'essaie de le récupérer.

**Comment by LaetitiaVerdier** [comment]
J'ai les fichiers en ai. Pouvez-vous me donner une adresse où vous envoyé le fichier ?
