### ISSUE TITLE
Problème d'affichage chapeau / COMPLEXE AQUALUDIQUE DE REIMS

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#67]
Dans internal content, j'ai un article sous projet de référence qui s'appelle Complexe aqualudique de Reims.

Le chapeau ci-dessous n'a pas lieu d'être, il s'agit d'un chapeau actualité :

![image](https://user-images.githubusercontent.com/40030677/41650871-5bb9968a-747f-11e8-9337-6c283ec0bb12.png)

Le chapeau des projets est le suivant :
![image](https://user-images.githubusercontent.com/40030677/41650954-973cac38-747f-11e8-935b-f7959b92d075.png)

Merci

**Comment by LucDelmon** [comment]
#68

**Comment by LucDelmon** [comment]
Bonjour,

Je me rend compte que ce chapeau inclus des données supplémentaires (les éléments de la liste à droite) qui ne sont pas renseignés dans le contenu.

J'ai l'impression que vous préférez ajouter vous même le chapeau directement dans le body des articles afin de le personnaliser.

Je penses qu'on va restez sur ce fonctionnement car il semble vous convenir.

**Je vais donc retirer tout les chapeaux qui étaient automatiquement rajouté aux vues de détails**.
 Il faudra donc inclure les chapeaux dans le body des contenus créés ( comme vous le faites actuellement).

**Comment by LaetitiaVerdier** [comment]
C'est parfait.

Vous avez raison.

Merci
