### ISSUE TITLE
Page liste / Projets de référence

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#68]
Bonjour,

La page liste Projets de référence est différente de la page Actualités.

![image](https://user-images.githubusercontent.com/40030677/41651084-f8fd09b8-747f-11e8-9882-379fcdca7c8c.png)

Il ne devrait pas y avoir de contacts mais une cartographie en picto avec un CTA "Voir nos implantations dans nos régions." 

Le sous-titre "Projets de référence" doit être remplacé par "Découvrez nos projets" + les guillemets.

Cf. ci-dessous :

![ucpa_corpo_lot_3_desktop_page_projets_de_reference_2018_06_13](https://user-images.githubusercontent.com/40030677/41651278-78203418-7480-11e8-8b90-45f4d56d22c3.jpg)

Merci

**Comment by LucDelmon** [comment]
Bonjour,

Je vois également que les projets ont tous une région. Faut-il rajouter ce champ a l'internal content ?

**Comment by LucDelmon** [comment]
J'ai rajouté un champ region sur le contenu

**Comment by LucDelmon** [comment]
J'ai fait la modification. 

Par contre je n'ai pas le picto de la carte, ou puis-je le récupérer ? A ma connaissance il n'y a pas de PSA projets de référence.

**Comment by LucDelmon** [comment]
J'ai rajouté le picto

**Comment by LaetitiaVerdier** [comment]
Merci
