### ISSUE TITLE
Fil d'ariane / Complexe aqualudique de Reims

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#69]
Bonjour,

Dans mon article Projets de référence / Complexe aqualudique de Reims, je souhaite changer le texte "Détail Projets de référence" pour Complexe aqualudique de Reims

Comment changer le fil d'ariane ?

![image](https://user-images.githubusercontent.com/40030677/41658440-a3896b5e-7496-11e8-9c01-ca51d18097ae.png)

Merci

**Comment by nicolastrenti** [comment]
Laetitia,
On réfléchit à cette problématique, assez complexe techniquement. Pour l'instant, j'ai remplacé le titre de la page par un simple "Projet de référence" en attendant mieux.

**Comment by LaetitiaVerdier** [comment]
Merci beaucoup, pour la présentation, j'ai changé le nom de l'article sous l'arborescence du site

**Comment by LucDelmon** [comment]
Bonjour, c'est fait sur tout les détails

**Comment by LaetitiaVerdier** [comment]
Merci
