### ISSUE TITLE
Déformation des photos

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#7]
Dès que je change une photo, la photo est déformée. Je ne comprends pas comment utiliser l'éditeur pour éviter la déformation. Il n'y a pas de zone de sélection apparente.

**Comment by nicolastrenti** [comment]
En cours d'analyse : https://github.com/ampize/ampize/issues/135

**Comment by LucDelmon** [comment]
Une amélioration a été déployée, Il ne devrait plus y avoir de déformations
