### ISSUE TITLE
Mobile / Vidéo

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#70]
Bonjour,

Voici l'affichage mobile du snippet vidéo :

![image](https://user-images.githubusercontent.com/40030677/41722635-67fe4a7c-7569-11e8-9601-c2e23a08725b.png)

Et celui que nous souhaitons :

![image](https://user-images.githubusercontent.com/40030677/41722886-fdf10b28-7569-11e8-9edd-12cdb06a4421.png)

Il y a trop de blanc entre le texte et la vidéo et l'espace avant et après le liseret n'est pas proportionnel.

Merci

**Comment by LucDelmon** [comment]
Bonjour,

les modifications sont effectuées.

**Comment by LaetitiaVerdier** [comment]
Merci
