### ISSUE TITLE
Version mobile / tous snippets / filets rouge +  espace

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#71]
Bonjour,

J'ai sur la version mobile un problème d'espaces avant et après le filet rouge sur tous les snippets avec du texte comme c'était le cas sur le desktop. Nous voulons un espace proportionnel identique en dessous et au dessus de 34 px. 

Merci

![image](https://user-images.githubusercontent.com/40030677/42172487-63f4ea10-7e1c-11e8-8825-ed9826484b7f.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait.

Cordialement,

Luc Delmon
