### ISSUE TITLE
Version mobile / Snippet A propos

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#72]
Il y a un espace blanc trop conséquent après le texte du snippet à propos 

![image](https://user-images.githubusercontent.com/40030677/42172573-afb3fbf8-7e1c-11e8-82cb-dc6ea85c2882.png)

**Comment by LaetitiaVerdier** [comment]
De plus, il semble qu'il y ait un filet blanc entre le triangle gris et son bloc dans les snippets mobile Photo gauche + texte + fond

**Comment by LucDelmon** [comment]
Bonjour, 
L'espace après le texte du snippet a été réduit

**Comment by LucDelmon** [comment]
Je n'arrive pas à reproduire les problème de l'espace entre le triangle et le bloc. Quel navigateur utilisez-vous ?

**Comment by LaetitiaVerdier** [comment]
Chrome

**Comment by LucDelmon** [comment]
J'ai fait de nombreux test, impossible de reproduire le problème. Est-il toujours présent ?

**Comment by LaetitiaVerdier** [comment]
Non je ne l'ai plus.

Tout est bon.

Merci
