### ISSUE TITLE
Version mobile / vidéo

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#73]
Il manque un espace au-dessus du titre, le filet rouge semble trop graissé par rapport à la maquette ou aux autres filets.

![image](https://user-images.githubusercontent.com/40030677/42172939-d1d53da4-7e1d-11e8-9d24-adf00ab4b673.png)

**Comment by LucDelmon** [comment]
Bonjour,

j'ai rajouté un espace.

Le filet est le même que pour les autres snippet ( 3px).

**Comment by LaetitiaVerdier** [comment]
Merci cela doit venir de mon affichage.
