### ISSUE TITLE
Problème avec les CTA

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#74]
Bonjour, 

Lorsque je dois changer le texte, la case n'est pas extensible et refuse mes modifications de texte. Dans l'exemple ci-dessous, j'essayais de mettre toutes nos implantations au lieu de Projets de référence :

![image](https://user-images.githubusercontent.com/40030677/42173488-6e76ca8c-7e1f-11e8-85c9-89876c08a674.png)

**Comment by LucDelmon** [comment]
Je n'ai personnellement aucun problème.

![capture d ecran 2018-07-03 a 15 25 41](https://user-images.githubusercontent.com/35261367/42222420-74fcbd10-7ed5-11e8-95e3-e9eb37f0d499.png)

Il faut bien coller le curseur sur la fin du dernier mot avant d'effacer ou d'écrire un texte différent.

**Comment by LaetitiaVerdier** [comment]
C'est curieux, je ne pouvais pas écrire après l'espace
