### ISSUE TITLE
Changement d'ordre / Header

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#75]
Bonjour,

Nous souhaitons intervertir Formations et Nous rejoindre dans l'ordre d'apparition du Header de sorte que "Formations" arrive directement derrière "Actualités".

![image](https://user-images.githubusercontent.com/40030677/42173594-e149a8ae-7e1f-11e8-92d5-43ebcf8ceef8.png)

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait
