### ISSUE TITLE
Pages liste

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#76]
Les pages liste Dispositifs solidaires et offres de formation doivent être composées comme la page liste Projets de référence.

L'affichage actuel correspond à la page liste actualités 

![image](https://user-images.githubusercontent.com/40030677/42174719-8ec7e98e-7e23-11e8-8fd3-a271bfd68478.png)

Nous voulons cet affichage :  

![image](https://user-images.githubusercontent.com/40030677/42174789-b818f06c-7e23-11e8-93b4-58142e4c80d0.png)

Il faut bien sûr que le picto de la cartographie soit modifiable.

Merci

**Comment by LucDelmon** [comment]
C'est fait.

Il est possible de changer le picto mais il faudra nous le donner, vous ne pourrez pas le changer vous-même

**Comment by LaetitiaVerdier** [comment]
Très bien.

Voici les 2 pictos.  Par contre, nous n'avons pas besoin de CTA sur les offres de formation (picto prime) ni les dispositifs solidaires (picto solidarite) sur la page liste.

![p_solidarite 1](https://user-images.githubusercontent.com/40030677/42224902-81ee07bc-7edb-11e8-8b28-3f896c950334.png)

![copie de picto prime](https://user-images.githubusercontent.com/40030677/42225027-d8d2f39e-7edb-11e8-9fad-3d222b0c674d.png)

**Comment by LaetitiaVerdier** [comment]
Je peux changer moi-même le texte en haut à gauche ?

**Comment by LucDelmon** [comment]
C'est fait.

Pour le texte, oui mais ca sera directement dans les templates de liste.

Nicolas va ajouter la procédure au support de formation.

**Comment by LaetitiaVerdier** [comment]
Je vous remercie.

Je ne sais en effet pas comment y accéder.
