### ISSUE TITLE
Version mobile / problème affichage visuels header

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#77]
Bonjour,

Le visuel doit garder une certaine hauteur pour les pages Hub et les pages projets de référence, dispositifs solidaires et offres de formation (cf. maquettes page mobile).

![image](https://user-images.githubusercontent.com/40030677/42207596-94fef23e-7eaa-11e8-899c-0a9c39c1827b.png)

Comme suit : 
![image](https://user-images.githubusercontent.com/40030677/42207703-d88c8a66-7eaa-11e8-9783-6508c66369e6.png)

**Comment by LucDelmon** [comment]
Bonjour,

Je ne comprends pas trop la solution que vous souhaitez, 

Si je force une certaine hauteur l'image se retrouve soit fortement déformé soit zoomé sur une partie de l'image. 

Je l'ai fait sur la page sport des territoires mais je ne pense pas que le résultat soit satisfaisant.

**Comment by LaetitiaVerdier** [comment]
Effectivement le résultat ne nous convient pas.

Au moment du chargement de l'image peut-on prévoir une fonction qui nous permette de recadrer l'image pour l'affichage mobile ?

Merci

**Comment by LucDelmon** [comment]
Bonjour,

Une autre solution que je vois serait d'indiquer 2 images dans le contenu. Une pour le desktop et une pour le mobile.

Cela vous conviendrait t'il?

**Comment by LaetitiaVerdier** [comment]
Oui tout à fait  

Merci

**Comment by LucDelmon** [comment]
J'ai rajouté un champ obligatoire imageMenuMobile dans les contenus.

A vous donc d'y indiquer une image dans un format qui vous convient.

J'ai mit une image au hasard sur les contenus existant pour qu'il ne se retrouve pas supprimés.

Ca régle donc le problème pour toutes les pages issues de contenus internes

**Comment by LaetitiaVerdier** [comment]
Bonjour,

Merci.

C'est super.
