### ISSUE TITLE
Version mobile / trame des photos

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#78]
Bonjour,

Il faut réduire la hauteur des trames des photos à droite et à gauche (cf. maquettes) sur tous les snippets avec photo + texte.

![image](https://user-images.githubusercontent.com/40030677/42208068-904e6e6c-7eab-11e8-8ca0-8f39fe933e6c.png)

**Comment by LucDelmon** [comment]
Bonjour, 

cet effet ou les trames se retrouvent trop grandes n'arrivent que sur les très petits téléphones.

Notre intégration mobile est plutôt focalisé sur des écrans de types Iphone 6,7,8 et Iphone X.

Si on réduit la hauteur des trames elles risquent de se retrouver trop petite pour ces types d'écrans.

**Comment by LaetitiaVerdier** [comment]
Très bien.

Je vous fais confiance.

Nous pouvons clôturer le ticket.

Merci
