### ISSUE TITLE
Version mobile / Snippet Hub chiffres clés et chiffres clés + texte

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#79]
Bonjour,

Sur les Snippets Hub chiffres clés et chiffres clés + texte, le triangle noir est trop conséquent et doit être diminué. De plus, les marges haut et bas doivent être rééquilibrées et identiques.

![image](https://user-images.githubusercontent.com/40030677/42208323-371764f6-7eac-11e8-9085-f388f32cdfee.png)

**Comment by LaetitiaVerdier** [comment]
Le triangle est trop conséquent également dans le snippet page hub chapeau

![image](https://user-images.githubusercontent.com/40030677/42209324-abfd5274-7eae-11e8-8ade-62aa118a3ceb.png)

**Comment by LaetitiaVerdier** [comment]
Idem
![image](https://user-images.githubusercontent.com/40030677/42209432-e2abedd0-7eae-11e8-885b-e889af444d1e.png)

**Comment by LaetitiaVerdier** [comment]
![image](https://user-images.githubusercontent.com/40030677/42210720-02cf1904-7eb2-11e8-9611-33f927c9bd71.png)
Idem dans les blocs contacts

**Comment by LucDelmon** [comment]
Bonjour, c'est fait pour le 1 er problème

**Comment by LucDelmon** [comment]
c'est fait pour tous

**Comment by LaetitiaVerdier** [comment]
Merci beaucoup
