### ISSUE TITLE
Version desktop / pages listes alignement à la marge

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#80]
Il y a un problème d'alignement à la marge gauche dans les pages listes "actualités", projets de référence, dispositifs solidaires et offres de formation

![image](https://user-images.githubusercontent.com/40030677/42208623-ec7610ae-7eac-11e8-81d2-7c95e72cf985.png)

**Comment by LucDelmon** [comment]
C'est corrigé
