### ISSUE TITLE
Affichage desktop + mobile / Visuel header 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#82]
Bonjour,

Le bandeau noir sous le menu ne doit pas apparaître lorsqu'il y a une photo associée (ex: article complexe aqualudique de Reims). Merci de prévoir une mise en forme conditionnelle (cf. maquettes)

![image](https://user-images.githubusercontent.com/40030677/42209057-fef82342-7ead-11e8-8848-da5936a2feb5.png)

![image](https://user-images.githubusercontent.com/40030677/42209071-089f669e-7eae-11e8-963d-e6fdda310818.png)

**Comment by LucDelmon** [comment]
Bonjour, 
c'est fait
