### ISSUE TITLE
Version mobile / snippet témoignage

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#83]
Bonjour,

La photo du snippet témoignage est ronde et non ovale (cela vaut pour la version desktop et mobile)

![image](https://user-images.githubusercontent.com/40030677/42209518-21f88a98-7eaf-11e8-918b-0a4e93bdf6c2.png)

Côté mobile, il manque le filet lire la suite (cf. maquette), nous avons prévu uniquement de laisser apparaître le début du témoignage (les 4-5 premières lignes)

![image](https://user-images.githubusercontent.com/40030677/42209716-a4f28ea8-7eaf-11e8-9f35-26fbd553bec5.png)

**Comment by LucDelmon** [comment]
Bonjour,

La forme de la photo est lié aux dimensions de la photo.

La meilleure façon de résoudre le problème est d'utiliser l'éditeur de photo pour recouper les photos et en faire des photos carrés.

Peu importe la dimension l'important étant que largeur=hauteur.

Si je force moi-même un rond la photo sera déformé.

**Comment by LaetitiaVerdier** [comment]
D'accord.

Merci
