### ISSUE TITLE
Version mobile / Snippet Aller plus loin

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#84]
Bonjour,

Il y a un gros problème de mise en page : 
- les call-to-action ne doivent pas passer sur 2 lignes, peut-être doit-on revoir la taille du corps de texte 
- la taille du triangle trop grande + le filet blanc qui devrait ne pas être apparent
- l'espace avant le titre et après le CTA
- la marge doit être plus importante entre les chevrons et le texte

![image](https://user-images.githubusercontent.com/40030677/42209949-454650d8-7eb0-11e8-9332-23d73b240bb3.png)

**Comment by LucDelmon** [comment]
c'est fait

**Comment by LaetitiaVerdier** [comment]
Merci
