### ISSUE TITLE
Version mobile / snippet articles liés loisirs x 3

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#85]
Bonjour,

Voici les ajustements souhaités :
- le CTA est cassé en 2 lignes, il doit être sur une seule ligne 
- les espaces avant et après le filet rouge doivent être équivalents et identiques à tous les autres snippets
- les espaces entre les 3 articles liés sont trop grands
- le visuel n'a pas la bonne taille
- la trame n'est pas à la bonne échelle

![image](https://user-images.githubusercontent.com/40030677/42210283-0297de54-7eb1-11e8-945c-972ab3396733.png)

Voici ce que nous souhaitons en résultat (cf. Maquettes) mais il n'est pas utile de rajouter les 3 puces de défilement, votre proposition actuelle nous convient

![image](https://user-images.githubusercontent.com/40030677/42210449-57ec437c-7eb1-11e8-819c-131de10db95e.png)

**Comment by LucDelmon** [comment]
c'est fait.

Cordialement.
