### ISSUE TITLE
Version mobile / snippet à propos

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#86]
Il manque le filet de séparation entre le titre et le texte cf. ci-dessous

![image](https://user-images.githubusercontent.com/40030677/42210858-5c2ce9cc-7eb2-11e8-8064-86b75c9b370c.png)

**Comment by LaetitiaVerdier** [comment]
![image](https://user-images.githubusercontent.com/40030677/42210902-78a95d24-7eb2-11e8-809c-2edf248e590e.png)

**Comment by LucDelmon** [comment]
Bonjour,

Il y est pour moi.
