### ISSUE TITLE
Version mobile / Articles liés x 3

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#87]
Voici ce qui s'affiche :
![image](https://user-images.githubusercontent.com/40030677/42211061-df2bd70c-7eb2-11e8-8f25-4dfffe30d643.png)

Voici ce que nous voulons :

![image](https://user-images.githubusercontent.com/40030677/42211093-f6f62c0c-7eb2-11e8-8ac7-a3ab24115716.png)

**Comment by nicolastrenti** [comment]
Cette intégration n'est pas techniquement possible.

**Comment by LaetitiaVerdier** [comment]
Est-il possible de proposer une autre présentation que les 3 les uns en-dessous des autres ?

![image](https://user-images.githubusercontent.com/40030677/42332898-8705ee5a-8079-11e8-9dbd-c411380e7281.png)

**Comment by LucDelmon** [comment]
Il me semble avoir vu au début du projet un visuel ou les deux premiers se retrouvaient cote à cote ( et le 3 éme n'était pas affiché en mobile). Avez-vous encore ce visuel quelque part ?

**Comment by LaetitiaVerdier** [comment]
Cette solution n'a pas été retenue car elle n'était pas réalisable en développement.

**Comment by LucDelmon** [comment]
Qu'entendez-vous par la ?

**Comment by LaetitiaVerdier** [comment]
Il nous a été demandé de changer la mise en page par notre DSI.

J'étais en congés à cette période et n'en sais pas plus.

**Comment by nicolastrenti** [comment]
Laetitia, 
Sur ce point je suis un peu embêté. Effectivement, on avait conclu avec Hugues qu'on souhaitait dans tous les cas rester sur le même nombre d'éléments, en desktop et en mobile.
Le carrousel en mobile uniquement n'est pas possible techniquement non plus.
Du coup je ne vois pas d'autre présentation que je pourrais te proposer...

**Comment by LaetitiaVerdier** [comment]
On reste sur cette présentation si nous n'avons pas d'autres options.

Merci d'avoir regardé.
