### ISSUE TITLE
Pages listes

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#88]
Nous souhaitons supprimer cet élément et le filet noir des pages listes sur le desktop et le mobile :

![image](https://user-images.githubusercontent.com/40030677/42211242-687a2ef0-7eb3-11e8-8610-8d61102abf37.png)

**Comment by LucDelmon** [comment]
Bonjour,

Je ne comprends pas. Il ne sera plus possible de changer de pages après cela

**Comment by LaetitiaVerdier** [comment]
Combien de projets peuvent apparaître sur une même page ?

De toute façon, nous souhaitons supprimer le filet noir

**Comment by LucDelmon** [comment]
On peut changer le nombre d'éléments par pages dans la configuration du bloc "List". ( Actuellement 10).

On peut aussi choisir d'afficher le paginator ou non.

![image](https://user-images.githubusercontent.com/35261367/42283565-27911e42-7faa-11e8-9605-f3cdb6cbe2d4.png)

Je vais enlever les filets noirs

**Comment by LaetitiaVerdier** [comment]
Nous avons besoin d'avoir au moins 15 items par page.

Dans ce cas, nous pouvons avoir la pagination si les items vont au-delà.

merci

**Comment by LucDelmon** [comment]
J'ai retiré les filets noirs.

J'ai passé les listes à 15 items par pages.

Par contre il n'est pas possible de conditionner l'affichage de la pagination. 

Vous pouvez le désactiver et le réactiver à la main quand vous dépasserez les 15 items.

**Comment by LaetitiaVerdier** [comment]
C'est parfait.

Merci
