### ISSUE TITLE
Problème espaces / Home page Desktop

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#89]
Bonjour,

Nous retrouvons de nombreux problèmes d'espaces et avons donc fait une synthèse pour vous aider à identifier nos problèmes de calage. 

[Desktop_Home_Page_2018_07_03.pdf](https://github.com/ampize/ampize-ucpa-corpo-recette/files/2159978/Desktop_Home_Page_2018_07_03.pdf)

**Comment by LucDelmon** [comment]
Bonjour,

C'est corrigé
