### ISSUE TITLE
Header et photo

### ISSUE THREAD

**Issue by nicolastrenti** [ampize/ampize-ucpa-corpo-recette#9]
Concernant le header, je n'ai pas trouvé comment ajouter la photo qui est collée au menu normalement

**Comment by LaetitiaVerdier** [comment]
![image](https://user-images.githubusercontent.com/40030677/41157594-99270dd4-6b26-11e8-9d04-db856824ec91.png)

**Comment by LucDelmon** [comment]
Il faut indiquer la photo dans les paramètres du menu, la ou on indique le logo
