### ISSUE TITLE
Problème espaces / Home page Mobile

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#90]
Idem ticket précédent :

[Mobile_Home_Page_2018_07_03.pdf](https://github.com/ampize/ampize-ucpa-corpo-recette/files/2159980/Mobile_Home_Page_2018_07_03.pdf)

**Comment by LucDelmon** [comment]
Bonjour,

La majorité des problèmes sont corrigés.

Cependant je ne peux pas placer l'image comme vous le souhaitez. L'image ne peux pas être dézoomé et garder autant de hauteur sur un format téléphone ( plus haut que large). La version de l'image que j'ai n'a pas autant de ciel. 

Je pense que vous avez une image sous un autre format pour le mobile. Il faudrait me l'envoyer

**Comment by LaetitiaVerdier** [comment]
Je vais me renseigner.

Merci

**Comment by LaetitiaVerdier** [comment]
La voici pour la home page et la page hub.

Comme nous avons conscience qu'il n'est pas possible de charger un double format pour chaque cas, que pouvez-vous nous proposer ?

![00070504_mobile_home_640x766px](https://user-images.githubusercontent.com/40030677/42379729-f5cc4c96-812b-11e8-8bba-9a0058481c81.jpg)

![00070650_mobile_hub_640x470px](https://user-images.githubusercontent.com/40030677/42379754-064276c2-812c-11e8-903b-918daa515f6a.jpg)

Merci beaucoup.

**Comment by LucDelmon** [comment]
Bonjour, 

Il est possible de charger un double format par le code ( je l'ai fait sur la page d'acceuil).

Il faut que l'on définisse avec Nicolas comment vous permettre de définir cette 2éme image.

**Comment by LaetitiaVerdier** [comment]
Merci Luc.

**Comment by LucDelmon** [comment]
A quel page faites-vous reference lorsque vous évoquez la "page HUB" ?

**Comment by LaetitiaVerdier** [comment]
A celle-ci par exemple

https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires

**Comment by LucDelmon** [comment]
J'ai un solution. A faire valider par Nicolas mais qui fonctionne.

j'ai rajouté un bloc image sous le menu.
![image](https://user-images.githubusercontent.com/35261367/42450646-2dc2898e-8385-11e8-93ae-83871476fe60.png)

Il suffit d'indiquer dans ce bloc l'image que l'on souhaite pour l'affichage mobile ( A vous ensuite d'adapter le format et la position de l'image que vous choisissez).

Si vous souhaitez faire la même chose sur d'autre pages, indiquez les moi que je rajoute le bloc en question.

Attention à ne pas créer de menus transparents sans ce bloc car ils n'auront pas d'images pour le mobile. Même si c'est pour remettre la même image ce bloc est nécessaire dans le cas d'un menu transparent.

**Comment by LaetitiaVerdier** [comment]
Parfait.

A l'exception de la Home, des pages Hub et des pages Dispositifs solidaires, Projets de référence et offres de formation, liées à une page liste, je ne pense pas avoir ce besoin ailleurs.

Merci

**Comment by LucDelmon** [comment]
Je laisse ouvert car Nicolas doit valider,
 même si cela fonctionne ca ne reste pas très clair d'indiquer une image dans le bloc menu et l'autre dans un bloc image. Ca reste à améliorer.

Je vais rajouter le bloc sur les pages ques vous m'indiquez

**Comment by LaetitiaVerdier** [comment]
Pour les contenus, vous avez déjà solutionné le problème en ajoutant l'image menu mobile dans les champs obligatoires

**Comment by LucDelmon** [comment]
Oui la solution pour les contenus est satisfaisante

**Comment by LucDelmon** [comment]
J'ai rajouté le bloc sur les pages "Le sport pour tous" "Le sport de Demain" et "Le groupe".

**Comment by LaetitiaVerdier** [comment]
Merci c'est parfait.

J'en ai aussi besoin sur Formations et Nous rejoindre

Merci

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait
