### ISSUE TITLE
Version mobile / espaces Footer

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#91]
Voici les problèmes identifiés sur le footer en version mobile.

[Mobile_Footer_2018_07_03.pdf](https://github.com/ampize/ampize-ucpa-corpo-recette/files/2162494/Mobile_Footer_2018_07_03.pdf)

**Comment by LucDelmon** [comment]
Bonjour,

c'est fait.

Certains espaces me semblent néanmoins particuliérement grand. Pensez à vérifier.

**Comment by LaetitiaVerdier** [comment]
Je vais regarder avec notre créa.

merci

**Comment by LaetitiaVerdier** [comment]
Bonjour Luc,

Effectivement, cela ne correspond pas aux maquettes, je crains que nous n'ayons pas le même référentiel pour les pixels ce que je ne m'explique pas.

Voici ce que Françoise, notre créa, m'a renvoyée pour essayer de vous aider dans les ajustements. 

[Desktop_Mobile_Footer_2018_07_09.pdf](https://github.com/ampize/ampize-ucpa-corpo-recette/files/2176862/Desktop_Mobile_Footer_2018_07_09.pdf)

**Comment by LucDelmon** [comment]
Bonjour,

Votre rendu visuel surtout en mobile ne correspond pas aux espaces en pixel indiquées dans les maquettes.

Je pense que vous n'avez pas la bonne échelle pour vos maquettes mobiles.

Un téléphone à une résolution plus petites et donc des pixels plus gros (ce qui aggrandi les espaces).

Le footer que j'ai fait respecte scrupuleusement le fichier Mobile_Footer_2018_07_03.pdf que vous avez envoyés.

Je peux soit essayer d'avoir le même rendu visuel que les maquettes ( ce qui était fait au début). Soit respecter les espacements que vous m'indiquez ( ce qui est fait maintenant) mais pas les deux.

**Comment by LaetitiaVerdier** [comment]
Je vais prévenir notre service.

J'en suis sincèrement désolée.

Nous souhaitons effectivement être plus proche du rendu visuel des maquettes.

**Comment by LaetitiaVerdier** [comment]
J'espère que nous n'avons pas eu le même problème sur tous les autres retours mobiles.

**Comment by LucDelmon** [comment]
J'ai corrigé le visuel du footer

**Comment by LaetitiaVerdier** [comment]
Merci Luc.

Encore navrée pour ce temps perdu.

**Comment by LaetitiaVerdier** [comment]
Cela nous va bien.

Il y a juste un picto qui n’apparaît pas bien à la fin

![image](https://user-images.githubusercontent.com/40030677/42513634-b7de927a-8457-11e8-8721-ab0196bfe0ae.png)

**Comment by LucDelmon** [comment]
J'ai réduit les espaces

**Comment by LaetitiaVerdier** [comment]
Merci

**Comment by LaetitiaVerdier** [comment]
Comment puis-je ajouter le footer au contenu ?

Merci

**Comment by LucDelmon** [comment]
Il sera possible de l'inclure sur toutes les pages automatiquement.

Mais ce feature n'est pas développé encore. Il arrive bientôt.

**Comment by LaetitiaVerdier** [comment]
Parfait merci
