### ISSUE TITLE
Version desktop / espaces Footer

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#92]
Idem pour la version desktop du footer.

[Desktop_Footer_2018_07_03.pdf](https://github.com/ampize/ampize-ucpa-corpo-recette/files/2162505/Desktop_Footer_2018_07_03.pdf)

**Comment by LucDelmon** [comment]
c'est fait

**Comment by LaetitiaVerdier** [comment]
Merci
