### ISSUE TITLE
Version desktop / Marges et espaces

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#93]
Bonjour,

Notre équipe créa a fait une synthèse sur les marges et les espaces au global sur la version desktop.

[Desktop_Marges_et_Espaces_2018_07_03.pdf](https://github.com/ampize/ampize-ucpa-corpo-recette/files/2163453/Desktop_Marges_et_Espaces_2018_07_03.pdf)

**Comment by LucDelmon** [comment]
Bonjour,

Vous m'avez déja demandé de réduire les espaces autour des filets rouges, ce qui prend beaucoup de temps.
 #41 

Votre fichier indique des marges de 70px avant et après, ce qui est très grand, plus même qu'avant la réduction.

Êtes-vous sure de vouloir autant d'espace ?

**Comment by LucDelmon** [comment]
C'est fait. Y compris les marges de 70 autour des filets rouges

**Comment by LaetitiaVerdier** [comment]
Bonjour,

Je vous remercie. 

J'avoue être surprise également mais il s'agit des retours de la responsable de la DA du site pour tous les PDF fournis qui a des outils dont je ne dispose pas pour vérifier ce type d'espaces. 

Je lui fais confiance sur ce point. En revanche, si certains ajustements demandés vous semblent anecdotiques, n'hésitez pas à nous en faire part que je lui en reparle avant.
