### ISSUE TITLE
Version mobile / Marges et espaces

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#94]
Idem sur la version mobile :

[Mobile_Marges_et_Espaces_2018_07_03.pdf](https://github.com/ampize/ampize-ucpa-corpo-recette/files/2163461/Mobile_Marges_et_Espaces_2018_07_03.pdf)

**Comment by LucDelmon** [comment]
La parti concernant l'espacement entre les modules est faites

**Comment by LucDelmon** [comment]
Bonjour,

J'avais déjà refait un passage pour égaliser les espaces autour des filets.

Ils sont a 32 px donc je les ai laissé. Pour 3 pixel ca me prendrait trop de temps.

Sinon j'ai bien mit un espace de 52 pixels aux endroits indiqués.

**Comment by LaetitiaVerdier** [comment]
Merci Luc,

Je ne sais pas si nous avons (notre service créa et vous) les mêmes références quand nous parlons de pixels.

J'ai refait des tests ce matin et il y a toujours des problèmes d'espaces qui ne sont pas identiques / proportionnels au-dessus et en-dessous de chaque texte. Par exemple, voici le résultat sur les desktop.

Je ne comprends pas ce qui pose cette différence d'affichage car j'ai bien conscience que vous faites les modifications mais le résultat ne correspond pas à nos PSD fournis. 

https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires

**Comment by LucDelmon** [comment]
On ne pourra jamais être précis au pixel prés. La taille de la css est limité est on est obligé de généraliser pour ne pas dépasser et on ne peut pas faire de cas par cas.

Il y a plusieurs éléments qui aménent des différences.

Par exemple : 
![image](https://user-images.githubusercontent.com/35261367/42459061-5db6c5ae-839b-11e8-835b-c3fdafc7cb03.png)

l'espace crée au dessus du filet est en vert. L'espace correspondant au texte est en bleu.

Le texte n'est pas collé en bas de l'espace qui lui est réservé. C'est lié à sa line-height (qu'on a prit de vos PSD) qui sert à faire l'espace entre les 2 lignes et qui est inévitable.

Lors d'une contribution. Les paragraphes sont séparés entre eux par un espace rajouté par l'éditeur à chaque appuie sur entrée. Cela permet de rédiger facilement un texte aéré. 

![image](https://user-images.githubusercontent.com/35261367/42459950-11aaa5e8-839d-11e8-8825-915d5bc12d59.png)

Le dernier paragraphe se retrouve suivi d'un espace. Comme il n'est pas possible de savoir à l'avance si vous allez écrire 1, 2, 3 ou plus paragraphe on ne peut pas désactiver cet effet.

Essayez de préciser quelles sont les plus grosse différence que j'essaye de voir s'il y a vraiment un problèmes à ces endroits précis.

**Comment by LaetitiaVerdier** [comment]
Je le comprends très bien mais ce qui nous gêne le plus ce sont les espaces qui devraient être quasi identiques dans chaque snippet, nous sommes plutôt satisfaits des espacements texte. 

En revanche, les blancs entre snippets nous posent problèmes (avant le titre ou le visuel, après les CTA, il y a de gros écarts entre chaque snippet...) : 

![image](https://user-images.githubusercontent.com/40030677/42460484-4aa24d0a-839e-11e8-8ccf-bec73230d030.png)

ou cela 
![image](https://user-images.githubusercontent.com/40030677/42460602-96726184-839e-11e8-8b8c-d90f16813acb.png)

![image](https://user-images.githubusercontent.com/40030677/42460619-a361049a-839e-11e8-85f7-8bf4d03f0dfb.png)

![image](https://user-images.githubusercontent.com/40030677/42460654-b657ecbc-839e-11e8-9531-fe27c342bbd1.png)

![image](https://user-images.githubusercontent.com/40030677/42460735-edfbce54-839e-11e8-9dca-a508b809740e.png)

![image](https://user-images.githubusercontent.com/40030677/42460755-fd88ded4-839e-11e8-9b09-c9035c6c4b8b.png)

**Comment by LaetitiaVerdier** [comment]
Il n'y a quasiment pas d'espace avant le titre dans le snippet vidéo 
- un très gros espace avant la photo du snippet texte + photo droite + CTA, 
- un gros espace après le CTA 
- un bien plus petit après la photo du snippet photo gauche + texte + CTA + fond

Dans chaque module, le premier espace et le dernier devrait être identique.

**Comment by LucDelmon** [comment]
J'ai corrigé cela récemment? Avez-vous recharger les snippets récemment ? Car le code à changé.

**Comment by LucDelmon** [comment]
Chaque snippets est entouré de 70 pixels en haut et en bas

**Comment by LaetitiaVerdier** [comment]
J'ai refait un nouvel article ce matin même après avoir vidé le cache de mon poste. 

C'est ce qui s'affiche chez moi. Je vous crois.

Savez-vous ce que je peux faire pour voir la dernière version à jour ?

**Comment by LucDelmon** [comment]
Vous devriez avoir la dernière version. Le problème vient peut être du fait que vous trouvez que 70pixels est trop grand. Pouvez-vous m'indiquez sur quel page vous avez fait ce test que je regarde ? Vos photos ce sont mélangées et j'ai du mal à comprendre le problème.

**Comment by LaetitiaVerdier** [comment]
https://ucpa-corpo.recette.ampize.me/le-sport-des-territoires

**Comment by LaetitiaVerdier** [comment]
Sur ma version, les écarts haut et bas ne sont pas proportionnels

**Comment by LucDelmon** [comment]
Bonjour,

Lors de la contribution sur Froala des paragraphes sont ajoutés entre les snippets ( c'est ce qui permet de cliquer entre les snippets) Ils créent un espace un peu aléatoire. Je les ai désactivés  lorsque le site est publié ce qui devrait résoudre des problèmes d'espaces.

Ensuite il est vrai que sur certains modules il y avait un espace sous le CTA  puis un espace de 70 pixel de fin de snippet. J'ai enlevé l'espace en trop sous le CTA.

Le résultat est sur la même page. Dites moi si c'est mieux.

Il y a effectivement un problème d'espace sur le snippet Video aussi , je vais corriger ca.

**Comment by LaetitiaVerdier** [comment]
Merci Luc

**Comment by LucDelmon** [comment]
Je me suis trompé l'espace entre les snippets est de 100 pixels ( comme vous demandez)

**Comment by LaetitiaVerdier** [comment]
Oui c'est bien ça.

Par contre, il est de 70 pixels entre les titres, les paragraphes, les filets et les CTA.

Pour le mobile, comme nous n'avons pas le même référentiel, nous vous faisons confiance pour approcher au mieux le rendu des maquettes.

Merci encore.

Laëtitia.

**Comment by LucDelmon** [comment]
Oui c'est bien le cas.

J'ai corrigé le snippet video également.

Pour le mobile:
 J'ai fait une grosse passe pour appliquer les espaces indiqués dans votre fichier de correction. 

Si les espaces ne vous conviennent pas (trop grand) merci de me l'indiquer de manière précise ( espace entre les snippets, espace entre les titres et les images, espaces autour des CTAs). 

Je préfère ca plutôt que de repasser dessus avec les maquettes en essayant de voir si ca ressemble. Vous savez mieux que moi ce que vous souhaitez.

**Comment by LaetitiaVerdier** [comment]
Luc,

Nous avons tout regardé et finalisé tous nos retours sous forme de tickets.

Merci pour tout
