### ISSUE TITLE
Snippet Diaporama

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#95]
Bonjour,

Sur le snippet Diaporama, je ne trouve pas le zoning photo 1200 x 591 px, uniquement le zoning texte.

![image](https://user-images.githubusercontent.com/40030677/42332210-b5ded9fa-8077-11e8-9309-1141f5b11482.png)

Et dans la version mobile, il manque le slider ou les trois boutons des chiffres clés pour comprendre qu'il y a plusieurs photos qui se succèdent.

Merci

**Comment by LucDelmon** [comment]
Bonjour,

c'est corrigé pour les images.

Les fléches du Slider sont désactivés en mobile oui, c'est pour gagner de la place. C'est le mode autoplay qui montrent qu'il y en a plusieurs. Souhaitez vous les réactiver ?

**Comment by LaetitiaVerdier** [comment]
c'est parfait.

Je ne souhaite pas le réactiver

Merci
