### ISSUE TITLE
Version mobile / Snippet chiffre clé + texte 

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#96]
Le snippet est très bien mais on ne voit pas le défilement s'il y a plusieurs chiffres à balayer

![image](https://user-images.githubusercontent.com/40030677/42333306-aa7ef75e-807a-11e8-847f-8c6ff6d7da5c.png)

**Comment by LaetitiaVerdier** [comment]
C'est en mode autoplay également ?

**Comment by LucDelmon** [comment]
Oui, c'est peut-être moins visible car les 3 slides sont identiques.

**Comment by LaetitiaVerdier** [comment]
Parfait merci
