### ISSUE TITLE
Home Page / contribution

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#97]
Bonjour,

J'ai besoin d'apprendre comment modifier l'ITW sur la Home, pouvez-vous le prévoir dans le guide ?

Merci

![image](https://user-images.githubusercontent.com/40030677/42512113-0875241e-8454-11e8-877b-c5354893550c.png)

**Comment by nicolastrenti** [comment]
Bonjour Laetitia,
J'ai ajouté une slide au support de formation pour préciser ce point (slide 37).

**Comment by LaetitiaVerdier** [comment]
Merci Nicolas
