### ISSUE TITLE
Version mobile / Snippet Hub chapeau + vidéo

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#98]
Dans le snippet hub chapeau, le CTA est trop collé à l'article

![image](https://user-images.githubusercontent.com/40030677/42514096-d9cdca62-8458-11e8-875e-da758d72248d.png)

Pour la vidéo, le filet n'est pas centré : 
![image](https://user-images.githubusercontent.com/40030677/42514149-feb2d322-8458-11e8-9011-66c5152ea62f.png)

**Comment by LucDelmon** [comment]
Bonjour,
Pour le chapeau pour moi il n'y a pas de problèmes. C'est un changement que j'ai fait récemment. Vous êtes sur d'avoir rechargé le snippet ?

**Comment by LaetitiaVerdier** [comment]
Sûre à 100% je viens de le refaire.

J'ai parfois des différences d'affichage avec vous que je ne m'explique pas.

**Comment by LucDelmon** [comment]
J'ai corrigé la video

**Comment by LucDelmon** [comment]
Sur quel page faites vous le test ?

**Comment by LaetitiaVerdier** [comment]
La page le sport des territoires et mentions légales

**Comment by LucDelmon** [comment]
La version sur le sport des territoire n'était pas la bonne, je viens de changer le snippet et j'ai le bon affichage désormais

**Comment by LaetitiaVerdier** [comment]
j'avais la bonne version dans mentions légales il me semble

**Comment by LaetitiaVerdier** [comment]
J'ai tout rechargé et vais vous faire un dernier retour global après avoir tout vérifié.

Merci

**Comment by LucDelmon** [comment]
L'affichage est correcte pour moi, pensez à recharger l'outil

**Comment by LaetitiaVerdier** [comment]
Nous avons tout rechargé pour la dernière vérification en cours
