### ISSUE TITLE
Chevauchement / snippets

### ISSUE THREAD

**Issue by LaetitiaVerdier** [ampize/ampize-ucpa-corpo-recette#99]
Quand je mets le snippet "articles liés x 3 loisirs" et un autre snippet vidéo ou aller plus loin par exemple, ils se chevauchent 

![image](https://user-images.githubusercontent.com/40030677/42515327-d25b98ba-845b-11e8-9752-6357f6a1315c.png)

**Comment by LucDelmon** [comment]
En effet; je vais essayer de corriger ca

**Comment by LucDelmon** [comment]
Bonjour, 

Le problème vient du snippet articles liés*3 loisirs.

Il est bien plus difficile à régler qu'il n'y parait.

Pensez-vous que l'on pourrait définir un format de photo unique (rapport largeur hauteur) pour ce snippet ?

**Comment by LaetitiaVerdier** [comment]
Bien sûr Luc,

Il s'agit du format 2544 x 702 px

Merci

**Comment by LucDelmon** [comment]
C'est fait.

Attention à bien respecter le format sinon le phénoméne de dépassement reviendra

**Comment by LaetitiaVerdier** [comment]
C'est noté merci
